services:
  backend:
    restart: always
    environment:
      USE_RUNSERVER: 0
    # In production, we don't expose ports globally here if using Nginx/ReverseProxy,
    # or expose minimal ports in cloudflare. But currently, the user doesn't use reverse proxy inside Docker.
    ports:
      - "8000:8000"

  frontend:
    build:
      target: production
    command: npm run start
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production

  postgres:
    restart: always

  redis:
    restart: always

  opensearch:
    restart: always

  qdrant:
    restart: always

  celeryworker:
    restart: always

  celery_ai:
    restart: always

  celerybeat:
    restart: always
