# Generated by Django 5.2.5 on 2025-08-10 10:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="email address"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="дата рождения"),
                ),
                ("is_verified", models.BooleanField(default=False, verbose_name="подтвержден")),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=6, verbose_name="код подтверждения"),
                ),
                (
                    "verification_code_expires",
                    models.DateTimeField(blank=True, null=True, verbose_name="срок действия кода"),
                ),
                (
                    "email_notifications",
                    models.BooleanField(default=True, verbose_name="email уведомления"),
                ),
                (
                    "telegram_notifications",
                    models.BooleanField(default=False, verbose_name="telegram уведомления"),
                ),
                (
                    "push_notifications",
                    models.BooleanField(default=True, verbose_name="push уведомления"),
                ),
                (
                    "telegram_id",
                    models.CharField(blank=True, max_length=50, verbose_name="telegram ID"),
                ),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=50, verbose_name="telegram username"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="дата обновления")),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="последний IP входа"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "English"), ("tr", "Türkçe")],
                        default="ru",
                        max_length=10,
                        verbose_name="язык",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "Рубль"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("TRY", "Турецкая лира"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="валюта",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[("home", "Дом"), ("work", "Работа"), ("other", "Другое")],
                        default="home",
                        max_length=10,
                        verbose_name="тип адреса",
                    ),
                ),
                ("contact_name", models.CharField(max_length=150, verbose_name="имя получателя")),
                (
                    "contact_phone",
                    models.CharField(max_length=17, verbose_name="телефон получателя"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="страна")),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="область/регион"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="город")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="почтовый индекс"),
                ),
                ("street", models.CharField(max_length=200, verbose_name="улица")),
                ("house", models.CharField(max_length=20, verbose_name="дом")),
                ("apartment", models.CharField(blank=True, max_length=20, verbose_name="квартира")),
                ("entrance", models.CharField(blank=True, max_length=10, verbose_name="подъезд")),
                ("floor", models.CharField(blank=True, max_length=10, verbose_name="этаж")),
                ("intercom", models.CharField(blank=True, max_length=20, verbose_name="домофон")),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="адрес по умолчанию"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="активен")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="дата обновления")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес пользователя",
                "verbose_name_plural": "адреса пользователей",
                "db_table": "user_addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="имя")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="фамилия")),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=150, verbose_name="отчество"),
                ),
                ("country", models.CharField(blank=True, max_length=100, verbose_name="страна")),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="город")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="почтовый индекс"),
                ),
                ("address", models.TextField(blank=True, verbose_name="адрес")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="аватар"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="о себе")),
                (
                    "is_public_profile",
                    models.BooleanField(default=False, verbose_name="публичный профиль"),
                ),
                ("show_email", models.BooleanField(default=False, verbose_name="показывать email")),
                (
                    "show_phone",
                    models.BooleanField(default=False, verbose_name="показывать телефон"),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(default=0, verbose_name="всего заказов"),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="общая сумма покупок",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="дата обновления")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль пользователя",
                "verbose_name_plural": "профили пользователей",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, unique=True, verbose_name="ключ сессии"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP адрес")),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                ("country", models.CharField(blank=True, max_length=100, verbose_name="страна")),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="город")),
                ("is_active", models.BooleanField(default=True, verbose_name="активна")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="последняя активность"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="истекает"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "сессия пользователя",
                "verbose_name_plural": "сессии пользователей",
                "db_table": "user_sessions",
                "ordering": ["-last_activity"],
            },
        ),
    ]
