# Generated by Django 5.2.5 on 2025-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "Доллар США"),
                    ("RUB", "Рубль"),
                    ("EUR", "Евро"),
                    ("TRY", "Турецкая лира"),
                ],
                default="USD",
                max_length=3,
                verbose_name="валюта",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Русский"), ("tr", "Türkçe")],
                default="en",
                max_length=10,
                verbose_name="язык",
            ),
        ),
    ]
