# Generated by Django 5.2.8 on 2025-11-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_update_language_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apple_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Apple ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Facebook ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Google ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="vk_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="VK ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="yandex_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Yandex ID"
            ),
        ),
    ]
