# Generated by Django 5.2.9 on 2025-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_delete_userprofile_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=50, verbose_name="Telegram"),
        ),
    ]
