# Generated by Django 5.2.10 on 2026-01-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_telegram_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "Доллар США"),
                    ("RUB", "Рубль"),
                    ("EUR", "Евро"),
                    ("TRY", "Турецкая лира"),
                    ("KZT", "Казахстанский тенге"),
                ],
                default="USD",
                max_length=3,
                verbose_name="валюта",
            ),
        ),
    ]
