# Generated by Django 5.2.10 on 2026-01-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "👥 пользователь",
                "verbose_name_plural": "👥 Пользователи — Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="useraddress",
            options={
                "ordering": ["-is_default", "-created_at"],
                "verbose_name": "👥 адрес пользователя",
                "verbose_name_plural": "👥 Пользователи — Адреса пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="usersession",
            options={
                "ordering": ["-last_activity"],
                "verbose_name": "👥 сессия пользователя",
                "verbose_name_plural": "👥 Пользователи — Сессии пользователей",
            },
        ),
    ]
