# Generated by Django 5.2.11 on 2026-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_options_alter_useraddress_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_public_profile",
            field=models.BooleanField(default=True, verbose_name="публичный профиль"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(default=True, verbose_name="показывать email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_phone",
            field=models.BooleanField(default=True, verbose_name="показывать телефон"),
        ),
    ]
