# Generated by Django 5.2.12 on 2026-03-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_is_public_profile_alter_user_show_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "Доллар США"),
                    ("RUB", "Рубль"),
                    ("EUR", "Евро"),
                    ("TRY", "Турецкая лира"),
                    ("KZT", "Казахстанский тенге"),
                    ("USDT", "USDT (Tether)"),
                ],
                default="USD",
                max_length=10,
                verbose_name="валюта",
            ),
        ),
    ]
