# Generated by Django 5.2.12 on 2026-03-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_add_usdt_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_sync_token",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="токен привязки Telegram",
            ),
        ),
    ]
