# Generated by Django 5.2.11 on 2026-02-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productvector",
            new_name="recommendat_categor_25ecfa_idx",
            old_name="rec_pv_cat_active",
        ),
        migrations.RenameIndex(
            model_name="productvector",
            new_name="recommendat_price_18e73b_idx",
            old_name="rec_pv_price_active",
        ),
        migrations.RenameIndex(
            model_name="productvector",
            new_name="recommendat_color_e8f60f_idx",
            old_name="rec_pv_color_active",
        ),
        migrations.RenameIndex(
            model_name="recommendationevent",
            new_name="recommendat_session_a030e8_idx",
            old_name="rec_ev_sess_created",
        ),
        migrations.RenameIndex(
            model_name="recommendationevent",
            new_name="recommendat_algorit_ffd7f9_idx",
            old_name="rec_ev_algo_type",
        ),
        migrations.RenameIndex(
            model_name="recommendationevent",
            new_name="recommendat_source__8c6f01_idx",
            old_name="rec_ev_src_type",
        ),
        migrations.AlterField(
            model_name="productvector",
            name="brand_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="productvector",
            name="category_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
