# Generated by Django 5.2.10 on 2026-01-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ("-updated_at",),
                "verbose_name": "📄 Статическая страница",
                "verbose_name_plural": "📄 Контент — Статические страницы",
            },
        ),
    ]
