# Generated by Django 5.2.12 on 2026-04-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_page_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ("footer_order", "-updated_at"),
                "verbose_name": "📄 Статическая страница",
                "verbose_name_plural": "📄 Контент — Статические страницы",
            },
        ),
        migrations.AddField(
            model_name="page",
            name="footer_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок в футере"),
        ),
        migrations.AddField(
            model_name="page",
            name="show_in_footer",
            field=models.BooleanField(default=False, verbose_name="Показывать в футере"),
        ),
    ]
