# Generated by Django 5.2.12 on 2026-04-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_page_options_page_footer_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="show_in_footer",
        ),
    ]
