# Generated by Django 5.2.12 on 2026-04-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_remove_page_show_in_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="meta_description_en",
            field=models.TextField(blank=True, verbose_name="SEO Description (EN)"),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description_ru",
            field=models.TextField(blank=True, verbose_name="SEO Description (RU)"),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title_en",
            field=models.CharField(blank=True, max_length=255, verbose_name="SEO Title (EN)"),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title_ru",
            field=models.CharField(blank=True, max_length=255, verbose_name="SEO Title (RU)"),
        ),
        migrations.AddField(
            model_name="page",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Изображение для превью в соцсетях (1200x630px)",
                null=True,
                upload_to="pages/og/",
                verbose_name="OG Image",
            ),
        ),
    ]
