# Generated by Django 5.2.10 on 2026-01-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_cartitem_chosen_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "🛒 Корзина", "verbose_name_plural": "🛒 Заказы — Корзины"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "🛒 Позиция корзины",
                "verbose_name_plural": "🛒 Заказы — Позиции корзины",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "🛒 Заказ",
                "verbose_name_plural": "🛒 Заказы — Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "🛒 Позиция заказа",
                "verbose_name_plural": "🛒 Заказы — Позиции заказа",
            },
        ),
        migrations.AlterModelOptions(
            name="promocode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "🛒 Промокод",
                "verbose_name_plural": "🛒 Заказы — Промокоды",
            },
        ),
    ]
