# Generated by Django 5.2.10 on 2026-01-30 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="max_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Максимальная скидка (RUB)",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="min_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Минимальная сумма заказа (RUB)",
            ),
        ),
    ]
