# Generated by Django 5.2.10 on 2026-03-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_promocode_max_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt_url",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="Ссылка на чек (PDF)"
            ),
        ),
    ]
