# Generated by Django 5.2.12 on 2026-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_receipt_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="currency",
            field=models.CharField(default="USD", max_length=10, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="currency",
            field=models.CharField(default="USD", max_length=10, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(default="USD", max_length=10, verbose_name="Валюта"),
        ),
    ]
