# Generated by Django 5.2.10 on 2026-02-04 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0088_product_keywords_product_seo_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "processing_type",
                    models.CharField(
                        choices=[
                            ("description_only", "Только описание"),
                            ("categorization_only", "Только категоризация"),
                            ("full", "Полная обработка"),
                            ("image_analysis", "Анализ изображений"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="Тип обработки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("processing", "Обработка"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                            ("moderation", "На модерации"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        help_text="Сырые данные от парсера: title, description, specs, images_urls и т.д.",
                        verbose_name="Входные данные",
                    ),
                ),
                (
                    "input_images_urls",
                    models.JSONField(
                        default=list,
                        help_text="Ссылки на R2 или оригинальные URL",
                        verbose_name="URL изображений (вход)",
                    ),
                ),
                (
                    "generated_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Сгенерированный заголовок",
                    ),
                ),
                (
                    "generated_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сгенерированное описание"
                    ),
                ),
                (
                    "generated_seo_title",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="SEO заголовок"
                    ),
                ),
                (
                    "generated_seo_description",
                    models.CharField(
                        blank=True, max_length=160, null=True, verbose_name="SEO описание"
                    ),
                ),
                (
                    "generated_keywords",
                    models.JSONField(default=list, verbose_name="Ключевые слова"),
                ),
                (
                    "category_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="0.0 - 1.0",
                        null=True,
                        verbose_name="Уверенность в категории",
                    ),
                ),
                (
                    "category_alternatives",
                    models.JSONField(
                        default=list,
                        help_text="Топ-3 альтернативы с confidence score",
                        verbose_name="Альтернативные категории",
                    ),
                ),
                (
                    "extracted_attributes",
                    models.JSONField(
                        default=dict,
                        help_text='{"color": "красный", "material": "хлопок", "size": "M-L"}',
                        verbose_name="Извлеченные атрибуты",
                    ),
                ),
                (
                    "image_analysis",
                    models.JSONField(
                        default=dict,
                        help_text='{"dominant_colors": ["#FF0000"], "detected_objects": ["dress"], "quality_score": 0.85}',
                        verbose_name="Анализ изображений",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        default="gpt-4o-mini", max_length=50, verbose_name="Использованная модель"
                    ),
                ),
                (
                    "tokens_used",
                    models.JSONField(
                        default=dict,
                        help_text='{"prompt": 150, "completion": 200, "total": 350}',
                        verbose_name="Использовано токенов",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="Время обработки (мс)"),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость ($)",
                    ),
                ),
                (
                    "raw_llm_response",
                    models.JSONField(blank=True, null=True, verbose_name="Полный ответ LLM"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "stack_trace",
                    models.TextField(
                        blank=True, null=True, verbose_name="Stack trace (при ошибке)"
                    ),
                ),
                (
                    "moderation_notes",
                    models.TextField(blank=True, null=True, verbose_name="Заметки модератора"),
                ),
                (
                    "moderation_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата модерации"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_processed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обработал (модератор)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_logs",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "suggested_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_suggestions",
                        to="catalog.category",
                        verbose_name="Предложенная категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог AI обработки",
                "verbose_name_plural": "Логи AI обработки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIModerationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Низкий"), (2, "Средний"), (3, "Высокий")], default=2
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Причина отправки на модерацию: low_confidence, sensitive_content и т.д.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_moderation_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "log_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_queue",
                        to="ai.aiprocessinglog",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AITemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("description", "Описание товара"),
                            ("category_example", "Пример категории"),
                            ("attribute_extraction", "Извлечение атрибутов"),
                            ("image_prompt", "Анализ изображения"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Текст шаблона или примера")),
                (
                    "embedding_vector",
                    models.JSONField(
                        blank=True, help_text="Кеш эмбеддинга (опционально)", null=True
                    ),
                ),
                ("language", models.CharField(default="ru", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_templates",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI шаблон",
                "verbose_name_plural": "AI шаблоны",
            },
        ),
        migrations.AddIndex(
            model_name="aiprocessinglog",
            index=models.Index(
                fields=["status", "created_at"], name="ai_aiproces_status_90c158_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiprocessinglog",
            index=models.Index(
                fields=["product", "created_at"], name="ai_aiproces_product_d5b8c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiprocessinglog",
            index=models.Index(
                fields=["suggested_category", "category_confidence"],
                name="ai_aiproces_suggest_f92f66_idx",
            ),
        ),
    ]
