# Generated by Django 5.2.11 on 2026-02-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("description", "Описание товара"),
                    ("category_example", "Пример категории"),
                    ("attribute_extraction", "Извлечение атрибутов"),
                    ("image_prompt", "Анализ изображения"),
                    ("category_instruction", "Инструкция для категории"),
                ],
                max_length=20,
            ),
        ),
    ]
