# Generated by Django 5.2.11 on 2026-02-10 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_alter_aitemplate_template_type"),
        ("catalog", "0088_product_keywords_product_seo_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitemplate",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Если указана: шаблон используется только для товаров с этой категорией. Пусто = общий шаблон для всех.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_templates",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="aitemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("description", "Описание товара"),
                    ("category_example", "Пример категории"),
                    ("attribute_extraction", "Извлечение атрибутов"),
                    ("image_prompt", "Анализ изображения"),
                    ("category_instruction", "Инструкция для категории"),
                ],
                help_text="«Инструкция для категории» и «Анализ изображения» подставляются по категории товара; остальные — через RAG по похожести текста.",
                max_length=20,
            ),
        ),
    ]
