# Generated by Django 5.2.12 on 2026-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_alter_aitemplate_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprocessinglog",
            name="image_analysis",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"dominant_colors": ["#FF0000"], "detected_objects": ["dress"], "quality_score": 0.85}',
                verbose_name="Анализ изображений",
            ),
        ),
        migrations.AlterField(
            model_name="aiprocessinglog",
            name="input_images_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ссылки на R2 или оригинальные URL",
                verbose_name="URL изображений (вход)",
            ),
        ),
    ]
