# Generated by Django 5.2.8 on 2025-12-01 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("author_name", models.CharField(max_length=100, verbose_name="Имя автора")),
                (
                    "author_avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/avatars/",
                        verbose_name="Аватар автора",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Рейтинг (1-5)",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("none", "Нет"), ("image", "Изображение"), ("video", "Видео")],
                        default="none",
                        max_length=10,
                        verbose_name="Тип медиа",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL видео (YouTube, Vimeo)"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/videos/",
                        verbose_name="Файл видео",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
    ]
