# Generated by Django 5.2.8 on 2025-12-01 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="testimonials/images/",
                verbose_name="Изображение (устаревшее)",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="media_type",
            field=models.CharField(
                choices=[("none", "Нет"), ("image", "Изображение"), ("video", "Видео")],
                default="none",
                max_length=10,
                verbose_name="Тип медиа (устаревшее)",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="testimonials/videos/",
                verbose_name="Файл видео (устаревшее)",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL видео (YouTube, Vimeo) (устаревшее)"
            ),
        ),
        migrations.CreateModel(
            name="TestimonialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Изображение"),
                            ("video", "Видео (YouTube/Vimeo URL)"),
                            ("video_file", "Видео файл"),
                        ],
                        max_length=20,
                        verbose_name="Тип медиа",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL видео (YouTube/Vimeo)",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/videos/",
                        verbose_name="Видео файл",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "testimonial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="feedback.testimonial",
                        verbose_name="Отзыв",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиа отзыва",
                "verbose_name_plural": "Медиа отзывов",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
