# Generated by Django 5.2.8 on 2025-12-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_testimonial_image_alter_testimonial_media_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активен"),
        ),
    ]
