# Generated by Django 5.2.8 on 2025-12-02 03:54

from django.db import migrations


def migrate_old_media_to_new(apps, schema_editor):
    """
    Переносит данные из старых полей медиа в новую таблицу TestimonialMedia.
    """
    Testimonial = apps.get_model('feedback', 'Testimonial')
    TestimonialMedia = apps.get_model('feedback', 'TestimonialMedia')
    
    for testimonial in Testimonial.objects.all():
        # Пропускаем, если уже есть медиа в новой таблице
        if TestimonialMedia.objects.filter(testimonial=testimonial).exists():
            continue
        
        # Проверяем старые поля и переносим данные
        if testimonial.image:
            # Переносим изображение
            TestimonialMedia.objects.create(
                testimonial=testimonial,
                media_type='image',
                image=testimonial.image,
                order=0
            )
        elif testimonial.video_file:
            # Переносим видео файл
            TestimonialMedia.objects.create(
                testimonial=testimonial,
                media_type='video_file',
                video_file=testimonial.video_file,
                order=0
            )
        elif testimonial.video_url:
            # Переносим URL видео
            TestimonialMedia.objects.create(
                testimonial=testimonial,
                media_type='video',
                video_url=testimonial.video_url,
                order=0
            )


def reverse_migration(apps, schema_editor):
    """
    Обратная миграция - не требуется, так как старые поля остаются.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_testimonial_is_active'),
    ]

    operations = [
        migrations.RunPython(migrate_old_media_to_new, reverse_migration),
    ]
