# Generated by Django 5.2.8 on 2025-12-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_migrate_old_media_to_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="image",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="media_type",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="video_file",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="video_url",
        ),
    ]
