# Generated by Django 5.2.10 on 2026-01-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_add_user_to_testimonial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "💬 Отзыв",
                "verbose_name_plural": "💬 Отзывы — Отзывы",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonialmedia",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "💬 Медиа отзыва",
                "verbose_name_plural": "💬 Отзывы — Медиа отзывов",
            },
        ),
    ]
