# Generated by Django 5.2.12 on 2026-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_testimonialsectionsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonialsectionsettings",
            name="show_on_homepage",
            field=models.BooleanField(
                default=False,
                help_text="Управляет показом карусели отзывов на главной странице сайта.",
                verbose_name="Показывать блок отзывов на главной",
            ),
        ),
    ]
