# Generated by Django 5.2.10 on 2026-08-26 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_productquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='homepage_priority',
            field=models.PositiveSmallIntegerField(default=100, help_text='Чем меньше число, тем раньше отзыв показывается в блоке на главной.', verbose_name='Приоритет на главной'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Добавляет опубликованный отзыв в общий блок отзывов на главной странице.', verbose_name='Показывать на главной'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['status', 'show_on_homepage', 'homepage_priority'], name='feedback_pr_home_idx'),
        ),
    ]
