# Generated by Django 5.2.5 on 2025-08-10 03:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("logo", models.URLField(blank=True, verbose_name="Логотип")),
                ("website", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                ("main_image", models.URLField(blank=True, verbose_name="Главное изображение")),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                ("barcode", models.CharField(blank=True, max_length=50, verbose_name="Штрихкод")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя синхронизация"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена"),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата записи"),
                ),
                ("source", models.CharField(default="api", max_length=50, verbose_name="Источник")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "История цен",
                "verbose_name_plural": "История цен",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("composition", "Состав"),
                            ("indications", "Показания"),
                            ("contraindications", "Противопоказания"),
                            ("side_effects", "Побочные эффекты"),
                            ("dosage", "Дозировка"),
                            ("storage", "Условия хранения"),
                            ("expiry", "Срок годности"),
                            ("manufacturer", "Производитель"),
                            ("country", "Страна производства"),
                            ("form", "Форма выпуска"),
                            ("weight", "Вес/объем"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Тип атрибута",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("value", models.TextField(verbose_name="Значение")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут товара",
                "verbose_name_plural": "Атрибуты товаров",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image_url", models.URLField(verbose_name="URL изображения")),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["external_id"], name="catalog_pro_externa_e8c827_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_pro_is_acti_f6baa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "brand"], name="catalog_pro_categor_a6606d_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="catalog_pro_price_2d2a4c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together={("product", "attribute_type", "name")},
        ),
    ]
