# Generated by Django 5.2.5 on 2025-08-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="margin_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Процент наценки для бренда; перекрывает категорию и наследуется товарами",
                max_digits=5,
                verbose_name="Маржа, %",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="margin_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Процент наценки для категории; перекрывается на уровне бренда/товара",
                max_digits=5,
                verbose_name="Маржа, %",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="converted_price_rub",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Цена в RUB (конверт.)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="converted_price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Цена в USD (конверт.)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="final_price_rub",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Итоговая цена RUB",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="final_price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Итоговая цена USD",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="last_external_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Изменён во внешнем API"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="margin_percent_applied",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Применённая маржа, %"
            ),
        ),
    ]
