# Generated by Django 5.2.5 on 2025-08-19 16:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_brand_margin_percent_category_margin_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClothingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        default="unisex",
                        max_length=10,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "clothing_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Тип одежды"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.clothingcategory",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория одежды",
                "verbose_name_plural": "Категории одежды",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ElectronicsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Тип устройства"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.electronicscategory",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория электроники",
                "verbose_name_plural": "Категории электроники",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShoeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        default="unisex",
                        max_length=10,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "shoe_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Тип обуви"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.shoecategory",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория обуви",
                "verbose_name_plural": "Категории обуви",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClothingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=20, verbose_name="Размер")),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                ("material", models.CharField(blank=True, max_length=100, verbose_name="Материал")),
                ("season", models.CharField(blank=True, max_length=50, verbose_name="Сезон")),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                ("main_image", models.URLField(blank=True, verbose_name="Главное изображение")),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clothing_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.clothingcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар одежды",
                "verbose_name_plural": "Товары одежды",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["external_id"], name="catalog_clo_externa_71f3d4_idx"),
                    models.Index(
                        fields=["is_active", "is_available"], name="catalog_clo_is_acti_a5126d_idx"
                    ),
                    models.Index(
                        fields=["category", "brand"], name="catalog_clo_categor_4fd110_idx"
                    ),
                    models.Index(fields=["price"], name="catalog_clo_price_a3fd0b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ElectronicsProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100, verbose_name="Модель")),
                (
                    "specifications",
                    models.JSONField(blank=True, default=dict, verbose_name="Характеристики"),
                ),
                ("warranty", models.CharField(blank=True, max_length=100, verbose_name="Гарантия")),
                (
                    "power_consumption",
                    models.CharField(blank=True, max_length=50, verbose_name="Потребление энергии"),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                ("main_image", models.URLField(blank=True, verbose_name="Главное изображение")),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="electronics_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.electronicscategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар электроники",
                "verbose_name_plural": "Товары электроники",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["external_id"], name="catalog_ele_externa_8c84aa_idx"),
                    models.Index(
                        fields=["is_active", "is_available"], name="catalog_ele_is_acti_d8fa18_idx"
                    ),
                    models.Index(
                        fields=["category", "brand"], name="catalog_ele_categor_640242_idx"
                    ),
                    models.Index(fields=["price"], name="catalog_ele_price_ce6b67_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShoeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=20, verbose_name="Размер")),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                ("material", models.CharField(blank=True, max_length=100, verbose_name="Материал")),
                (
                    "heel_height",
                    models.CharField(blank=True, max_length=50, verbose_name="Высота каблука"),
                ),
                (
                    "sole_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Тип подошвы"),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                ("main_image", models.URLField(blank=True, verbose_name="Главное изображение")),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shoe_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.shoecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар обуви",
                "verbose_name_plural": "Товары обуви",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["external_id"], name="catalog_sho_externa_d7bd4a_idx"),
                    models.Index(
                        fields=["is_active", "is_available"], name="catalog_sho_is_acti_1deee1_idx"
                    ),
                    models.Index(
                        fields=["category", "brand"], name="catalog_sho_categor_b6700a_idx"
                    ),
                    models.Index(fields=["price"], name="catalog_sho_price_efc46a_idx"),
                ],
            },
        ),
    ]
