# Generated by Django 5.2.8 on 2025-12-01 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.contenttypes.models import ContentType


def migrate_favorite_data(apps, schema_editor):
    """Перенос данных из старого поля product в GenericForeignKey."""
    Favorite = apps.get_model('catalog', 'Favorite')
    Product = apps.get_model('catalog', 'Product')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Получаем ContentType для Product
    product_content_type = ContentType.objects.get(
        app_label='catalog',
        model='product'
    )
    
    # Переносим данные из старого поля product в новые поля
    # Используем raw SQL для доступа к старому полю product_id
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE catalog_favorite 
            SET content_type_id = %s, object_id = product_id
            WHERE product_id IS NOT NULL
        """, [product_content_type.id])


def reverse_migrate_favorite_data(apps, schema_editor):
    """Обратный перенос данных."""
    # В обратной миграции просто очищаем новые поля
    Favorite = apps.get_model('catalog', 'Favorite')
    Favorite.objects.all().update(content_type=None, object_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_favorite"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Сначала удаляем старый unique_together
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together=set(),
        ),
        # Добавляем новые поля
        migrations.AddField(
            model_name="favorite",
            name="_old_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_favorites",
                to="catalog.product",
                verbose_name="Старый товар (для миграции)",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Тип товара",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="ID товара"),
        ),
        # Переносим данные из старого поля в новые
        migrations.RunPython(migrate_favorite_data, reverse_migrate_favorite_data),
        # Удаляем старое поле
        migrations.RemoveField(
            model_name="favorite",
            name="product",
        ),
        # Обновляем unique_together
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={
                ("session_key", "content_type", "object_id"),
                ("user", "content_type", "object_id"),
            },
        ),
        # Добавляем индекс
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["content_type", "object_id"], name="catalog_fav_content_3dd593_idx"
            ),
        ),
        # Удаляем временное поле
        migrations.RemoveField(
            model_name="favorite",
            name="_old_product",
        ),
        # Делаем поля обязательными
        migrations.AlterField(
            model_name="favorite",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Тип товара",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="object_id",
            field=models.PositiveIntegerField(verbose_name="ID товара"),
        ),
    ]
