# Generated by Django 5.2.8 on 2025-12-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_migrate_favorite_to_generic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Необязательный заголовок для баннера",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("main", "Главный баннер (вверху страницы)"),
                            ("after_brands", 'После блока "Популярные бренды"'),
                            ("before_footer", "Перед футером"),
                        ],
                        default="main",
                        help_text="Где на странице отображается баннер",
                        max_length=20,
                        verbose_name="Позиция",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Изображение"),
                            ("video", "Видео"),
                            ("gif", "GIF анимация"),
                        ],
                        default="image",
                        help_text="Тип медиа-контента баннера",
                        max_length=10,
                        verbose_name="Тип контента",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для баннера (JPG, PNG)",
                        null=True,
                        upload_to="banners/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Внешний URL изображения (если не загружено локально)",
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL видео (YouTube, Vimeo или прямой ссылка на видеофайл)",
                        verbose_name="URL видео",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Локальный видеофайл (MP4, WebM)",
                        null=True,
                        upload_to="banners/videos/",
                        verbose_name="Видеофайл",
                    ),
                ),
                (
                    "gif_url",
                    models.URLField(
                        blank=True, help_text="Внешний URL GIF анимации", verbose_name="URL GIF"
                    ),
                ),
                (
                    "gif_file",
                    models.FileField(
                        blank=True,
                        help_text="Локальный GIF файл",
                        null=True,
                        upload_to="banners/gifs/",
                        verbose_name="GIF файл",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="URL для перехода при клике на баннер",
                        verbose_name="Ссылка при клике",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        help_text="Текст кнопки/ссылки (если нужен)",
                        max_length=100,
                        verbose_name="Текст ссылки",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше баннер в карусели",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
                "ordering": ["position", "sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["position", "is_active", "sort_order"],
                        name="catalog_ban_positio_d45ecd_idx",
                    )
                ],
            },
        ),
    ]
