# Generated by Django 5.2.8 on 2025-12-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="gif_file",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="gif_url",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="image",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="video_file",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="video_url",
        ),
        migrations.AlterField(
            model_name="banner",
            name="link_text",
            field=models.CharField(
                blank=True,
                help_text="Текст кнопки, отображаемой поверх медиа-контента",
                max_length=100,
                verbose_name="Текст кнопки",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Заголовок, отображаемый поверх медиа-контента",
                max_length=200,
                verbose_name="Заголовок",
            ),
        ),
        migrations.CreateModel(
            name="BannerMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Изображение"),
                            ("video", "Видео"),
                            ("gif", "GIF анимация"),
                        ],
                        default="image",
                        help_text="Тип медиа-контента",
                        max_length=10,
                        verbose_name="Тип контента",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для баннера (JPG, PNG)",
                        null=True,
                        upload_to="banners/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Внешний URL изображения (если не загружено локально)",
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL видео (YouTube, Vimeo или прямой ссылка на видеофайл)",
                        verbose_name="URL видео",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Локальный видеофайл (MP4, WebM)",
                        null=True,
                        upload_to="banners/videos/",
                        verbose_name="Видеофайл",
                    ),
                ),
                (
                    "gif_url",
                    models.URLField(
                        blank=True, help_text="Внешний URL GIF анимации", verbose_name="URL GIF"
                    ),
                ),
                (
                    "gif_file",
                    models.FileField(
                        blank=True,
                        help_text="Локальный GIF файл",
                        null=True,
                        upload_to="banners/gifs/",
                        verbose_name="GIF файл",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем раньше отображается в карусели",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="catalog.banner",
                        verbose_name="Баннер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиа баннера",
                "verbose_name_plural": "Медиа баннеров",
                "ordering": ["banner", "sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["banner", "sort_order"], name="catalog_ban_banner__d7d921_idx"
                    )
                ],
            },
        ),
    ]
