# Generated by Django 5.2.8 on 2025-12-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_banner_content_type_remove_banner_gif_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="position",
            field=models.CharField(
                choices=[
                    ("main", "Главный баннер (вверху страницы)"),
                    ("after_brands", 'После блока "Популярные бренды"'),
                    ("before_footer", "Перед футером"),
                    ("after_popular_products", "После популярных товаров"),
                ],
                db_index=True,
                default="main",
                max_length=50,
                verbose_name="Позиция баннера",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок баннера"),
        ),
    ]
