# Generated by Django 5.2.9 on 2025-12-03 23:46
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_banner_position_alter_banner_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannermedia",
            name="link_url",
            field=models.URLField(
                verbose_name="Ссылка на баннер",
                blank=True,
                help_text="Ссылка, на которую переходит пользователь при клике по этому медиа-элементу",
            ),
        ),
    ]

