# Generated by Django 5.2.9 on 2025-12-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_add_link_url_to_bannermedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannermedia",
            name="link_url",
            field=models.URLField(
                blank=True,
                help_text="URL для перехода при клике на этот конкретный медиа-элемент. Если пусто, используется ссылка баннера.",
                verbose_name="Ссылка при клике на медиа",
            ),
        ),
    ]
