# Generated by Django 5.2.9 on 2025-12-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_bannermedia_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannermedia",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание для этого медиа-элемента (H3). Если пусто, используется текст ссылки баннера.",
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="bannermedia",
            name="link_text",
            field=models.CharField(
                blank=True,
                help_text="Текст для кнопки ссылки. Если пусто, используется текст ссылки баннера.",
                max_length=100,
                verbose_name="Текст кнопки",
            ),
        ),
        migrations.AddField(
            model_name="bannermedia",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Заголовок для этого медиа-элемента (H2). Если пусто, используется заголовок баннера.",
                max_length=200,
                verbose_name="Заголовок",
            ),
        ),
    ]
