# Generated by Django 5.2.9 on 2025-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_bannermedia_description_bannermedia_link_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание баннера (используется как fallback для медиа-файлов, если у них не указано свое описание)",
                verbose_name="Описание баннера",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Заголовок баннера (используется как fallback для медиа-файлов, если у них не указан свой заголовок)",
                max_length=200,
                verbose_name="Заголовок баннера",
            ),
        ),
        migrations.AlterField(
            model_name="bannermedia",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание для этого медиа-элемента (H3). Если пусто, используется описание баннера.",
                verbose_name="Описание",
            ),
        ),
    ]
