# Generated by Django 5.2.9 on 2025-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_rename_accessories_to_medical_accessories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Категория (медицина/БАДы/медтехника/аксессуары)",
                "verbose_name_plural": "Категории (медицина/БАДы/медтехника/аксессуары)",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Товар (медицина/БАДы/медтехника/аксессуары)",
                "verbose_name_plural": "Товары (медицина/БАДы/медтехника/аксессуары)",
            },
        ),
        migrations.RenameIndex(
            model_name="clothingproductimage",
            new_name="catalog_clo_product_dd32bd_idx",
            old_name="catalog_clo_product_b05bc4_idx",
        ),
        migrations.RenameIndex(
            model_name="electronicsproductimage",
            new_name="catalog_ele_product_4ec4f6_idx",
            old_name="catalog_ele_product_f42259_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="catalog_pro_product_9ecdd3_idx",
            old_name="catalog_product_product_type_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="catalog_pro_availab_eadfd8_idx",
            old_name="catalog_product_availability_status_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="catalog_pro_country_dde460_idx",
            old_name="catalog_product_country_of_origin_idx",
        ),
        migrations.RenameIndex(
            model_name="shoeproductimage",
            new_name="catalog_sho_product_929bf9_idx",
            old_name="catalog_sh_product_sort_9bce1d_idx",
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("GBP", "GBP"),
                    ("USDT", "USDT"),
                ],
                default="RUB",
                help_text="Выбирается из списка расчётных валют, используемых в прайсах.",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("in_stock", "В наличии"),
                    ("backorder", "Под заказ"),
                    ("preorder", "Предзаказ"),
                    ("out_of_stock", "Нет в наличии"),
                    ("discontinued", "Снят с производства"),
                ],
                db_index=True,
                default="in_stock",
                max_length=32,
                verbose_name="Статус доступности",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="country_of_origin",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="Страна происхождения"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Описание (англ.)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.URLField(
                blank=True,
                help_text="URL основного изображения (ссылка на CDN или внутреннее хранилище).",
                verbose_name="Главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(blank=True, max_length=500, verbose_name="Название (англ.)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                verbose_name="URL изображения",
            ),
        ),
    ]
