# Generated by Django 5.2.9 on 2025-12-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_alter_category_options_alter_product_options_and_more"),
        ("catalog", "0024_add_category_presets"),
    ]

    operations = []
