# Generated by Django 5.2.9 on 2025-12-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_merge_20251208_1919"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryAccessories",
            fields=[],
            options={
                "verbose_name": "Категория — Аксессуары",
                "verbose_name_plural": "Категории — Аксессуары",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="CategoryFurniture",
            fields=[],
            options={
                "verbose_name": "Категория — Мебель",
                "verbose_name_plural": "Категории — Мебель",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="CategoryJewelry",
            fields=[],
            options={
                "verbose_name": "Категория — Украшения",
                "verbose_name_plural": "Категории — Украшения",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="CategoryMedicalEquipment",
            fields=[],
            options={
                "verbose_name": "Категория — Медтехника",
                "verbose_name_plural": "Категории — Медтехника",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="CategoryMedicines",
            fields=[],
            options={
                "verbose_name": "Категория — Медицина",
                "verbose_name_plural": "Категории — Медицина",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="CategorySupplements",
            fields=[],
            options={
                "verbose_name": "Категория — БАДы",
                "verbose_name_plural": "Категории — БАДы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="CategoryTableware",
            fields=[],
            options={
                "verbose_name": "Категория — Посуда",
                "verbose_name_plural": "Категории — Посуда",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="ProductAccessories",
            fields=[],
            options={
                "verbose_name": "Товар — Аксессуары",
                "verbose_name_plural": "Товары — Аксессуары",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="ProductFurniture",
            fields=[],
            options={
                "verbose_name": "Товар — Мебель",
                "verbose_name_plural": "Товары — Мебель",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="ProductJewelry",
            fields=[],
            options={
                "verbose_name": "Товар — Украшения",
                "verbose_name_plural": "Товары — Украшения",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="ProductMedicalEquipment",
            fields=[],
            options={
                "verbose_name": "Товар — Медтехника",
                "verbose_name_plural": "Товары — Медтехника",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="ProductMedicines",
            fields=[],
            options={
                "verbose_name": "Товар — Медицина",
                "verbose_name_plural": "Товары — Медицина",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="ProductSupplements",
            fields=[],
            options={
                "verbose_name": "Товар — БАДы",
                "verbose_name_plural": "Товары — БАДы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="ProductTableware",
            fields=[],
            options={
                "verbose_name": "Товар — Посуда",
                "verbose_name_plural": "Товары — Посуда",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
    ]
