# Generated by Django 5.2.9 on 2025-12-08 23:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_reset_shoe_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClothingVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="Название варианта"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Автогенерация по названию/цвету/размеру, можно переопределить.",
                        max_length=600,
                        unique=True,
                        verbose_name="Slug варианта",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                ("size", models.CharField(blank=True, max_length=50, verbose_name="Размер")),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                ("barcode", models.CharField(blank=True, max_length=100, verbose_name="Штрихкод")),
                ("gtin", models.CharField(blank=True, max_length=100, verbose_name="GTIN")),
                ("mpn", models.CharField(blank=True, max_length=100, verbose_name="MPN")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("GBP", "GBP"),
                            ("USDT", "USDT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(blank=True, verbose_name="Главное изображение варианта"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.clothingproduct",
                        verbose_name="Товар одежды (родитель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант одежды",
                "verbose_name_plural": "Варианты одежды",
                "ordering": ["product", "sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClothingVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.clothingvariant",
                        verbose_name="Вариант одежды",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта одежды",
                "verbose_name_plural": "Изображения вариантов одежды",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoeVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="Название варианта"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Автогенерация по названию/цвету/размеру, можно переопределить.",
                        max_length=600,
                        unique=True,
                        verbose_name="Slug варианта",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="Используйте EU размер; можно оставить пустым, если не применяется.",
                        max_length=20,
                        verbose_name="Размер",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                ("barcode", models.CharField(blank=True, max_length=100, verbose_name="Штрихкод")),
                ("gtin", models.CharField(blank=True, max_length=100, verbose_name="GTIN")),
                ("mpn", models.CharField(blank=True, max_length=100, verbose_name="MPN")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("GBP", "GBP"),
                            ("USDT", "USDT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(blank=True, verbose_name="Главное изображение варианта"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.shoeproduct",
                        verbose_name="Товар (родитель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант обуви",
                "verbose_name_plural": "Варианты обуви",
                "ordering": ["product", "sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoeVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.shoevariant",
                        verbose_name="Вариант обуви",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта обуви",
                "verbose_name_plural": "Изображения вариантов обуви",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="clothingvariant",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_clo_product_1c9c67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clothingvariant",
            index=models.Index(fields=["slug"], name="catalog_clo_slug_16945d_idx"),
        ),
        migrations.AddIndex(
            model_name="clothingvariant",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_clo_is_acti_109ad3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clothingvariantimage",
            index=models.Index(
                fields=["variant", "sort_order"], name="catalog_clo_variant_9e3c15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoevariant",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_sho_product_9b1683_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoevariant",
            index=models.Index(fields=["slug"], name="catalog_sho_slug_67fbe0_idx"),
        ),
        migrations.AddIndex(
            model_name="shoevariant",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_sho_is_acti_5e4cc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoevariantimage",
            index=models.Index(
                fields=["variant", "sort_order"], name="catalog_sho_variant_cab383_idx"
            ),
        ),
    ]
