# Generated by Django 5.2.9 on 2025-12-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_variant_sizes_per_color"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="clothingvariantsize",
            new_name="catalog_clo_variant_080b88_idx",
            old_name="catalog_clothin_vari_492d2c_idx",
        ),
        migrations.RenameIndex(
            model_name="clothingvariantsize",
            new_name="catalog_clo_variant_329389_idx",
            old_name="catalog_clothin_vari_a93e34_idx",
        ),
        migrations.RenameIndex(
            model_name="shoevariantsize",
            new_name="catalog_sho_variant_f0b012_idx",
            old_name="catalog_shoe_vari_685ad7_idx",
        ),
        migrations.RenameIndex(
            model_name="shoevariantsize",
            new_name="catalog_sho_variant_cc1594_idx",
            old_name="catalog_shoe_vari_d259d1_idx",
        ),
        migrations.AlterField(
            model_name="clothingvariant",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Используйте таблицу размеров ниже; поле оставлено для совместимости.",
                max_length=50,
                verbose_name="Размер (устарело)",
            ),
        ),
        migrations.AlterField(
            model_name="shoevariant",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Используйте таблицу размеров ниже; поле оставлено для совместимости.",
                max_length=20,
                verbose_name="Размер (устарело)",
            ),
        ),
    ]
