# Generated by Django 5.2.9 on 2025-12-09 03:45

import apps.catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_card_media_for_marketing_cards"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryHeadwear",
            fields=[],
            options={
                "verbose_name": "Категория — Головные уборы",
                "verbose_name_plural": "Категории — Головные уборы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="CategoryUnderwear",
            fields=[],
            options={
                "verbose_name": "Категория — Нижнее бельё",
                "verbose_name_plural": "Категории — Нижнее бельё",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="ProductHeadwear",
            fields=[],
            options={
                "verbose_name": "Товар — Головные уборы",
                "verbose_name_plural": "Товары — Головные уборы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.CreateModel(
            name="ProductUnderwear",
            fields=[],
            options={
                "verbose_name": "Товар — Нижнее бельё",
                "verbose_name_plural": "Товары — Нижнее бельё",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.AlterField(
            model_name="brand",
            name="card_media",
            field=models.FileField(
                blank=True,
                help_text="Изображение, GIF или видео для карточки бренда (до 50 МБ).",
                null=True,
                upload_to="marketing/cards/brands/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                            "gif",
                            "mp4",
                            "mov",
                            "webm",
                        ]
                    ),
                    apps.catalog.models.validate_card_media_file_size,
                ],
                verbose_name="Медиа для карточки",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="card_media",
            field=models.FileField(
                blank=True,
                help_text="Изображение, GIF или видео для карточки категории (до 50 МБ).",
                null=True,
                upload_to="marketing/cards/categories/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                            "gif",
                            "mp4",
                            "mov",
                            "webm",
                        ]
                    ),
                    apps.catalog.models.validate_card_media_file_size,
                ],
                verbose_name="Медиа для карточки",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("medicines", "Медицина"),
                    ("supplements", "БАДы"),
                    ("medical_equipment", "Медтехника"),
                    ("clothing", "Одежда"),
                    ("underwear", "Нижнее бельё"),
                    ("headwear", "Головные уборы"),
                    ("shoes", "Обувь"),
                    ("electronics", "Электроника"),
                    ("furniture", "Мебель"),
                    ("tableware", "Посуда"),
                    ("accessories", "Аксессуары"),
                    ("jewelry", "Украшения"),
                ],
                db_index=True,
                default="medicines",
                help_text="Определяет домен: медицина, БАДы, медтехника, посуда, мебель, аксессуары, украшения и т.д.",
                max_length=32,
                verbose_name="Тип категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("medicines", "Медицина"),
                    ("supplements", "БАДы"),
                    ("medical_equipment", "Медтехника"),
                    ("clothing", "Одежда"),
                    ("underwear", "Нижнее бельё"),
                    ("headwear", "Головные уборы"),
                    ("shoes", "Обувь"),
                    ("electronics", "Электроника"),
                    ("furniture", "Мебель"),
                    ("tableware", "Посуда"),
                    ("accessories", "Аксессуары"),
                    ("jewelry", "Украшения"),
                ],
                db_index=True,
                default="medicines",
                max_length=32,
                verbose_name="Тип товара",
            ),
        ),
    ]
