# Generated by Django 5.2.9 on 2025-12-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_brand_primary_category_slug"),
        ("catalog", "0032_categoryheadwear_categoryunderwear_productheadwear_and_more"),
    ]

    operations = []
