# Generated by Django 5.2.9 on 2025-12-13 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0036_add_category_type_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.ForeignKey(
                help_text="Выберите тип категории. Если нужного типа нет, создайте его в разделе 'Типы категорий'.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="catalog.categorytype",
                verbose_name="Тип категории",
            ),
        ),
    ]
