# Generated by Django 5.2.9 on 2025-12-13 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0037_alter_category_category_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Переведенное название категории",
                        max_length=200,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Переведенное описание категории",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод категории",
                "verbose_name_plural": "Переводы категорий",
                "ordering": ["category", "locale"],
                "indexes": [
                    models.Index(
                        fields=["category", "locale"], name="catalog_cat_categor_5a65c2_idx"
                    )
                ],
                "unique_together": {("category", "locale")},
            },
        ),
    ]
