# Generated by Django 5.2.9 on 2025-12-13 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0038_categorytranslation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="clothing_type",
            field=models.CharField(
                blank=True,
                help_text="Для категорий одежды: платья, блузки, джинсы и т.д.",
                max_length=100,
                verbose_name="Тип одежды",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="device_type",
            field=models.CharField(
                blank=True,
                help_text="Для категорий электроники: телефоны, ноутбуки, планшеты и т.д.",
                max_length=100,
                verbose_name="Тип устройства",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("men", "Мужская"),
                    ("women", "Женская"),
                    ("unisex", "Унисекс"),
                    ("kids", "Детская"),
                ],
                help_text="Для категорий одежды и обуви: мужская, женская, унисекс, детская",
                max_length=10,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="shoe_type",
            field=models.CharField(
                blank=True,
                help_text="Для категорий обуви: туфли, кроссовки, сапоги и т.д.",
                max_length=100,
                verbose_name="Тип обуви",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите тип категории для медицины/БАДов/медтехники. Для одежды/обуви/электроники не обязательно.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="catalog.categorytype",
                verbose_name="Тип категории",
            ),
        ),
    ]
