# Generated by Django 5.2.9 on 2025-12-13 23:58

import django.db.models.deletion
from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0043_update_product_category_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clothing_products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="electronics_products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
    ]
