# Generated by Django 5.2.9 on 2025-12-13 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_change_product_category_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoeproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите категорию обуви.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shoe_products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
    ]
