# Generated by Django 5.2.9 on 2025-12-14 00:16

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def update_product_category_links(apps, schema_editor):
    """Обновляет связи продуктов с категориями перед изменением ForeignKey."""
    Category = apps.get_model('catalog', 'Category')
    ClothingCategory = apps.get_model('catalog', 'ClothingCategory')
    ShoeCategory = apps.get_model('catalog', 'ShoeCategory')
    ElectronicsCategory = apps.get_model('catalog', 'ElectronicsCategory')
    
    # Создаем маппинг старых категорий на новые на основе slug и типа
    category_mapping = {}
    
    # Маппинг для ClothingCategory
    for old_cat in ClothingCategory.objects.all():
        # Ищем соответствующую Category по name и clothing_type (более надежно)
        new_cat = Category.objects.filter(
            name=old_cat.name,
            clothing_type=old_cat.clothing_type,
            gender=old_cat.gender
        ).first()
        if not new_cat:
            # Пробуем по slug
            new_cat = Category.objects.filter(
                slug=old_cat.slug,
                clothing_type=old_cat.clothing_type
            ).first()
        if not new_cat:
            # Пробуем по slug с суффиксом
            new_cat = Category.objects.filter(
                slug__startswith=old_cat.slug,
                clothing_type=old_cat.clothing_type
            ).first()
        if new_cat:
            category_mapping[('clothing', old_cat.id)] = new_cat.id
            logger.info(f"Маппинг ClothingCategory {old_cat.id} ({old_cat.slug}) -> Category {new_cat.id} ({new_cat.slug})")
        else:
            logger.warning(f"Не найдена Category для ClothingCategory {old_cat.id} (slug: {old_cat.slug}, name: {old_cat.name})")
    
    # Маппинг для ShoeCategory
    for old_cat in ShoeCategory.objects.all():
        new_cat = Category.objects.filter(
            name=old_cat.name,
            shoe_type=old_cat.shoe_type,
            gender=old_cat.gender
        ).first()
        if not new_cat:
            new_cat = Category.objects.filter(
                slug=old_cat.slug,
                shoe_type=old_cat.shoe_type
            ).first()
        if not new_cat:
            new_cat = Category.objects.filter(
                slug__startswith=old_cat.slug,
                shoe_type=old_cat.shoe_type
            ).first()
        if new_cat:
            category_mapping[('shoe', old_cat.id)] = new_cat.id
            logger.info(f"Маппинг ShoeCategory {old_cat.id} ({old_cat.slug}) -> Category {new_cat.id} ({new_cat.slug})")
        else:
            logger.warning(f"Не найдена Category для ShoeCategory {old_cat.id} (slug: {old_cat.slug}, name: {old_cat.name})")
    
    # Маппинг для ElectronicsCategory
    for old_cat in ElectronicsCategory.objects.all():
        new_cat = Category.objects.filter(
            name=old_cat.name,
            device_type=old_cat.device_type
        ).first()
        if not new_cat:
            new_cat = Category.objects.filter(
                slug=old_cat.slug,
                device_type=old_cat.device_type
            ).first()
        if not new_cat:
            new_cat = Category.objects.filter(
                slug__startswith=old_cat.slug,
                device_type=old_cat.device_type
            ).first()
        if new_cat:
            category_mapping[('electronics', old_cat.id)] = new_cat.id
            logger.info(f"Маппинг ElectronicsCategory {old_cat.id} ({old_cat.slug}) -> Category {new_cat.id} ({new_cat.slug})")
        else:
            logger.warning(f"Не найдена Category для ElectronicsCategory {old_cat.id} (slug: {old_cat.slug}, name: {old_cat.name})")
    
    # Обновляем связи в продуктах через SQL
    # Временно отключаем триггеры для обновления ForeignKey
    with schema_editor.connection.cursor() as cursor:
        # Отключаем триггеры для временного обхода проверки ForeignKey
        cursor.execute("ALTER TABLE catalog_clothingproduct DISABLE TRIGGER ALL")
        cursor.execute("ALTER TABLE catalog_shoeproduct DISABLE TRIGGER ALL")
        cursor.execute("ALTER TABLE catalog_electronicsproduct DISABLE TRIGGER ALL")
        # Обновляем ClothingProduct
        clothing_updated = 0
        for (cat_type, old_id), new_id in category_mapping.items():
            if cat_type == 'clothing':
                try:
                    cursor.execute(
                        "UPDATE catalog_clothingproduct SET category_id = %s WHERE category_id = %s",
                        [new_id, old_id]
                    )
                    clothing_updated += cursor.rowcount
                except Exception as e:
                    logger.error(f"Ошибка при обновлении ClothingProduct: {e}")
        
        logger.info(f"Обновлено {clothing_updated} ClothingProduct")
        
        # Устанавливаем NULL для продуктов с категориями, которые не были найдены
        old_clothing_ids = set(ClothingCategory.objects.values_list('id', flat=True))
        mapped_clothing_ids = {old_id for (cat_type, old_id) in category_mapping.keys() if cat_type == 'clothing'}
        unmapped_ids = old_clothing_ids - mapped_clothing_ids
        if unmapped_ids:
            for old_id in unmapped_ids:
                try:
                    cursor.execute(
                        "UPDATE catalog_clothingproduct SET category_id = NULL WHERE category_id = %s",
                        [old_id]
                    )
                    if cursor.rowcount > 0:
                        logger.warning(f"Установлен NULL для {cursor.rowcount} ClothingProduct с категорией {old_id}")
                except Exception as e:
                    logger.error(f"Ошибка при установке NULL для ClothingProduct: {e}")
        
        # Обновляем ShoeProduct
        shoe_updated = 0
        for (cat_type, old_id), new_id in category_mapping.items():
            if cat_type == 'shoe':
                try:
                    cursor.execute(
                        "UPDATE catalog_shoeproduct SET category_id = %s WHERE category_id = %s",
                        [new_id, old_id]
                    )
                    shoe_updated += cursor.rowcount
                except Exception as e:
                    logger.error(f"Ошибка при обновлении ShoeProduct: {e}")
        
        logger.info(f"Обновлено {shoe_updated} ShoeProduct")
        
        old_shoe_ids = set(ShoeCategory.objects.values_list('id', flat=True))
        mapped_shoe_ids = {old_id for (cat_type, old_id) in category_mapping.keys() if cat_type == 'shoe'}
        unmapped_ids = old_shoe_ids - mapped_shoe_ids
        if unmapped_ids:
            for old_id in unmapped_ids:
                try:
                    cursor.execute(
                        "UPDATE catalog_shoeproduct SET category_id = NULL WHERE category_id = %s",
                        [old_id]
                    )
                    if cursor.rowcount > 0:
                        logger.warning(f"Установлен NULL для {cursor.rowcount} ShoeProduct с категорией {old_id}")
                except Exception as e:
                    logger.error(f"Ошибка при установке NULL для ShoeProduct: {e}")
        
        # Обновляем ElectronicsProduct
        electronics_updated = 0
        for (cat_type, old_id), new_id in category_mapping.items():
            if cat_type == 'electronics':
                try:
                    cursor.execute(
                        "UPDATE catalog_electronicsproduct SET category_id = %s WHERE category_id = %s",
                        [new_id, old_id]
                    )
                    electronics_updated += cursor.rowcount
                except Exception as e:
                    logger.error(f"Ошибка при обновлении ElectronicsProduct: {e}")
        
        logger.info(f"Обновлено {electronics_updated} ElectronicsProduct")
        
        old_electronics_ids = set(ElectronicsCategory.objects.values_list('id', flat=True))
        mapped_electronics_ids = {old_id for (cat_type, old_id) in category_mapping.keys() if cat_type == 'electronics'}
        unmapped_ids = old_electronics_ids - mapped_electronics_ids
        if unmapped_ids:
            for old_id in unmapped_ids:
                try:
                    cursor.execute(
                        "UPDATE catalog_electronicsproduct SET category_id = NULL WHERE category_id = %s",
                        [old_id]
                    )
                    if cursor.rowcount > 0:
                        logger.warning(f"Установлен NULL для {cursor.rowcount} ElectronicsProduct с категорией {old_id}")
                except Exception as e:
                    logger.error(f"Ошибка при установке NULL для ElectronicsProduct: {e}")
        
        # Включаем триггеры обратно
        cursor.execute("ALTER TABLE catalog_clothingproduct ENABLE TRIGGER ALL")
        cursor.execute("ALTER TABLE catalog_shoeproduct ENABLE TRIGGER ALL")
        cursor.execute("ALTER TABLE catalog_electronicsproduct ENABLE TRIGGER ALL")


def reverse_update_product_category_links(apps, schema_editor):
    """Обратная миграция - не реализована."""
    logger.warning("Обратная миграция не поддерживается")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0040_migrate_category_data"),
    ]

    operations = [
        migrations.RunPython(update_product_category_links, reverse_update_product_category_links),
    ]
