# Generated by Django 5.2.9 on 2025-12-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0042_change_shoe_product_category"),
        ("catalog", "0043_update_product_category_links"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClothingCategory",
        ),
        migrations.DeleteModel(
            name="ShoeCategory",
        ),
        migrations.DeleteModel(
            name="ElectronicsCategory",
        ),
    ]
