# Generated by Django 5.2.9 on 2025-12-14 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0044_remove_old_category_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryClothing",
            fields=[],
            options={
                "verbose_name": "Категория — Одежда",
                "verbose_name_plural": "Категории — Одежда",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="CategoryElectronics",
            fields=[],
            options={
                "verbose_name": "Категория — Электроника",
                "verbose_name_plural": "Категории — Электроника",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="CategoryShoes",
            fields=[],
            options={
                "verbose_name": "Категория — Обувь",
                "verbose_name_plural": "Категории — Обувь",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
    ]
