# Generated by Django 5.2.9 on 2025-12-14 03:55

from django.db import migrations, models
import logging

logger = logging.getLogger(__name__)


def fix_category_hierarchy(apps, schema_editor):
    """Исправляет иерархию категорий: устанавливает правильные parent для подкатегорий."""
    Category = apps.get_model('catalog', 'Category')
    
    # Находим корневые категории
    root_clothing = Category.objects.filter(slug='clothing', parent__isnull=True).first()
    root_shoes = Category.objects.filter(slug='shoes', parent__isnull=True).first()
    root_electronics = Category.objects.filter(slug='electronics', parent__isnull=True).first()
    
    if not root_clothing or not root_shoes or not root_electronics:
        logger.warning("Не найдены корневые категории. Пропускаем исправление иерархии.")
        return
    
    updated_count = 0
    
    # Исправляем категории одежды
    clothing_keywords = ['men-clothing', 'women-clothing', 'мужская одежда', 'женская одежда']
    wrong_clothing = Category.objects.filter(
        parent__isnull=True
    ).exclude(id=root_clothing.id).filter(
        models.Q(slug__icontains='clothing') | models.Q(name__icontains='одежда')
    )
    
    for cat in wrong_clothing:
        # Проверяем, что это действительно подкатегория одежды
        if any(kw in cat.slug.lower() or kw in cat.name.lower() for kw in clothing_keywords):
            cat.parent_id = root_clothing.id
            cat.save(update_fields=['parent_id'])
            updated_count += 1
            logger.info(f"Исправлена категория одежды: {cat.name} (id={cat.id}) -> parent={root_clothing.id}")
    
    # Исправляем категории обуви
    shoes_keywords = ['men-shoes', 'women-shoes', 'kids-shoes', 'unisex-shoes', 
                     'мужская обувь', 'женская обувь', 'детская обувь', 'унисекс обувь']
    wrong_shoes = Category.objects.filter(
        parent__isnull=True
    ).exclude(id=root_shoes.id).filter(
        models.Q(slug__icontains='shoe') | models.Q(name__icontains='обувь')
    )
    
    for cat in wrong_shoes:
        # Проверяем, что это действительно подкатегория обуви
        if any(kw in cat.slug.lower() or kw in cat.name.lower() for kw in shoes_keywords):
            cat.parent_id = root_shoes.id
            cat.save(update_fields=['parent_id'])
            updated_count += 1
            logger.info(f"Исправлена категория обуви: {cat.name} (id={cat.id}) -> parent={root_shoes.id}")
    
    # Исправляем категории электроники
    electronics_keywords = ['смартфон', 'ноутбук', 'телевизор', 'планшет', 
                           'smartphone', 'laptop', 'tv', 'tablet']
    wrong_electronics = Category.objects.filter(
        parent__isnull=True
    ).exclude(id=root_electronics.id).filter(
        models.Q(name__icontains='смартфон') | models.Q(name__icontains='ноутбук') | 
        models.Q(name__icontains='телевизор') | models.Q(name__icontains='планшет') |
        models.Q(slug__icontains='smartphone') | models.Q(slug__icontains='laptop') |
        models.Q(slug__icontains='tv') | models.Q(slug__icontains='tablet')
    )
    
    for cat in wrong_electronics:
        # Проверяем, что это действительно подкатегория электроники
        if any(kw in cat.slug.lower() or kw in cat.name.lower() for kw in electronics_keywords):
            cat.parent_id = root_electronics.id
            cat.save(update_fields=['parent_id'])
            updated_count += 1
            logger.info(f"Исправлена категория электроники: {cat.name} (id={cat.id}) -> parent={root_electronics.id}")
    
    logger.info(f"Исправлено категорий: {updated_count}")


def reverse_fix_category_hierarchy(apps, schema_editor):
    """Обратная миграция - не реализована."""
    logger.warning("Обратная миграция не поддерживается")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0045_categoryclothing_categoryelectronics_categoryshoes"),
    ]

    operations = [
        migrations.RunPython(fix_category_hierarchy, reverse_fix_category_hierarchy),
    ]

