# Generated by Django 5.2.9 on 2025-12-14 03:56

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def fix_duplicate_clothing_categories(apps, schema_editor):
    """Исправляет дубликаты категорий одежды: делает их подкатегориями или удаляет."""
    Category = apps.get_model('catalog', 'Category')
    
    # Находим корневую категорию "Одежда"
    root_clothing = Category.objects.filter(slug='clothing', parent__isnull=True).first()
    
    if not root_clothing:
        logger.warning("Не найдена корневая категория 'Одежда'. Пропускаем исправление дубликатов.")
        return
    
    # Находим дубликаты
    duplicate_slugs = ['women-fashion', 'women-fashion-clothing-1']
    duplicates = Category.objects.filter(
        parent__isnull=True,
        slug__in=duplicate_slugs
    ).exclude(id=root_clothing.id)
    
    updated_count = 0
    deleted_count = 0
    
    for cat in duplicates:
        # Проверяем, есть ли у категории продукты или подкатегории
        has_products = False
        has_children = False
        
        try:
            # Проверяем продукты (через разные типы продуктов)
            from apps.catalog.models import ClothingProduct, ShoeProduct, ElectronicsProduct
            has_products = (
                ClothingProduct.objects.filter(category=cat).exists() or
                ShoeProduct.objects.filter(category=cat).exists() or
                ElectronicsProduct.objects.filter(category=cat).exists()
            )
        except:
            pass
        
        has_children = Category.objects.filter(parent=cat).exists()
        
        if has_products or has_children:
            # Если есть продукты или подкатегории - делаем подкатегорией
            cat.parent_id = root_clothing.id
            cat.save(update_fields=['parent_id'])
            updated_count += 1
            logger.info(f"Категория '{cat.name}' (slug: {cat.slug}, id={cat.id}) сделана подкатегорией 'Одежда'")
        else:
            # Если нет продуктов и подкатегорий - удаляем
            cat.delete()
            deleted_count += 1
            logger.info(f"Удалена дублирующая категория '{cat.name}' (slug: {cat.slug}, id={cat.id})")
    
    logger.info(f"Исправлено: {updated_count} + удалено: {deleted_count}")


def reverse_fix_duplicate_clothing_categories(apps, schema_editor):
    """Обратная миграция - не реализована."""
    logger.warning("Обратная миграция не поддерживается")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0046_fix_category_hierarchy"),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_clothing_categories, reverse_fix_duplicate_clothing_categories),
    ]

