# Generated by Django 5.2.9 on 2025-12-14 04:01

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def remove_duplicate_subcategories(apps, schema_editor):
    """Удаляет дубликаты подкатегорий, оставляя только одну с самым коротким slug."""
    Category = apps.get_model('catalog', 'Category')
    
    # Находим все корневые категории
    root_categories = Category.objects.filter(parent__isnull=True, is_active=True)
    
    deleted_count = 0
    
    for root in root_categories:
        # Получаем все подкатегории
        subcategories = Category.objects.filter(parent=root.id)
        
        # Группируем по названию
        from collections import defaultdict
        by_name = defaultdict(list)
        for cat in subcategories:
            by_name[cat.name].append(cat)
        
        # Для каждой группы с дубликатами оставляем одну (с самым коротким slug или самым ранним id)
        for name, cats in by_name.items():
            if len(cats) > 1:
                # Сортируем: сначала по длине slug, потом по id
                cats_sorted = sorted(cats, key=lambda c: (len(c.slug or ''), c.id))
                # Оставляем первую, остальные удаляем
                to_keep = cats_sorted[0]
                to_delete = cats_sorted[1:]
                
                for cat in to_delete:
                    # Проверяем, есть ли продукты или подкатегории
                    has_products = False
                    has_children = False
                    
                    try:
                        # Проверяем продукты
                        from apps.catalog.models import ClothingProduct, ShoeProduct, ElectronicsProduct, Product
                        has_products = (
                            ClothingProduct.objects.filter(category=cat).exists() or
                            ShoeProduct.objects.filter(category=cat).exists() or
                            ElectronicsProduct.objects.filter(category=cat).exists() or
                            Product.objects.filter(category=cat).exists()
                        )
                    except:
                        pass
                    
                    has_children = Category.objects.filter(parent=cat).exists()
                    
                    if has_products or has_children:
                        # Если есть продукты или подкатегории - переносим их в категорию, которую оставляем
                        logger.info(f"Категория '{cat.name}' (slug: {cat.slug}, id={cat.id}) имеет продукты/подкатегории, пропускаем удаление")
                        continue
                    
                    # Удаляем дубликат
                    logger.info(f"Удаляем дубликат '{cat.name}' (slug: {cat.slug}, id={cat.id}), оставляем '{to_keep.name}' (slug: {to_keep.slug}, id={to_keep.id})")
                    cat.delete()
                    deleted_count += 1
    
    logger.info(f"Удалено дубликатов: {deleted_count}")


def reverse_remove_duplicate_subcategories(apps, schema_editor):
    """Обратная миграция - не реализована."""
    logger.warning("Обратная миграция не поддерживается")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0047_fix_duplicate_clothing_categories"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_subcategories, reverse_remove_duplicate_subcategories),
    ]
