# Generated by Django 5.2.9 on 2025-12-14 04:03

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def merge_duplicate_subcategories_with_products(apps, schema_editor):
    """Объединяет дубликаты подкатегорий, перенося продукты в основную категорию."""
    Category = apps.get_model('catalog', 'Category')
    
    # Находим все корневые категории
    root_categories = Category.objects.filter(parent__isnull=True, is_active=True)
    
    merged_count = 0
    deleted_count = 0
    
    for root in root_categories:
        # Получаем все подкатегории
        subcategories = Category.objects.filter(parent=root.id)
        
        # Группируем по названию
        from collections import defaultdict
        by_name = defaultdict(list)
        for cat in subcategories:
            by_name[cat.name].append(cat)
        
        # Для каждой группы с дубликатами
        for name, cats in by_name.items():
            if len(cats) > 1:
                # Сортируем: сначала по длине slug, потом по id
                cats_sorted = sorted(cats, key=lambda c: (len(c.slug or ''), c.id))
                # Оставляем первую, остальные объединяем
                to_keep = cats_sorted[0]
                to_merge = cats_sorted[1:]
                
                for cat in to_merge:
                    # Переносим продукты
                    try:
                        from apps.catalog.models import ClothingProduct, ShoeProduct, ElectronicsProduct, Product
                        
                        # Переносим ClothingProduct
                        clothing_products = ClothingProduct.objects.filter(category=cat)
                        if clothing_products.exists():
                            clothing_products.update(category=to_keep)
                            logger.info(f"Перенесено {clothing_products.count()} ClothingProduct из '{cat.name}' (id={cat.id}) в '{to_keep.name}' (id={to_keep.id})")
                        
                        # Переносим ShoeProduct
                        shoe_products = ShoeProduct.objects.filter(category=cat)
                        if shoe_products.exists():
                            shoe_products.update(category=to_keep)
                            logger.info(f"Перенесено {shoe_products.count()} ShoeProduct из '{cat.name}' (id={cat.id}) в '{to_keep.name}' (id={to_keep.id})")
                        
                        # Переносим ElectronicsProduct
                        electronics_products = ElectronicsProduct.objects.filter(category=cat)
                        if electronics_products.exists():
                            electronics_products.update(category=to_keep)
                            logger.info(f"Перенесено {electronics_products.count()} ElectronicsProduct из '{cat.name}' (id={cat.id}) в '{to_keep.name}' (id={to_keep.id})")
                        
                        # Переносим Product (общие)
                        products = Product.objects.filter(category=cat)
                        if products.exists():
                            products.update(category=to_keep)
                            logger.info(f"Перенесено {products.count()} Product из '{cat.name}' (id={cat.id}) в '{to_keep.name}' (id={to_keep.id})")
                        
                    except Exception as e:
                        logger.warning(f"Ошибка при переносе продуктов из '{cat.name}' (id={cat.id}): {e}")
                    
                    # Переносим подкатегории
                    children = Category.objects.filter(parent=cat)
                    if children.exists():
                        children.update(parent=to_keep)
                        logger.info(f"Перенесено {children.count()} подкатегорий из '{cat.name}' (id={cat.id}) в '{to_keep.name}' (id={to_keep.id})")
                    
                    # Удаляем дубликат
                    logger.info(f"Удаляем дубликат '{cat.name}' (slug: {cat.slug}, id={cat.id}), оставляем '{to_keep.name}' (slug: {to_keep.slug}, id={to_keep.id})")
                    cat.delete()
                    deleted_count += 1
                    merged_count += 1
    
    logger.info(f"Объединено дубликатов: {merged_count}, удалено: {deleted_count}")


def reverse_merge_duplicate_subcategories_with_products(apps, schema_editor):
    """Обратная миграция - не реализована."""
    logger.warning("Обратная миграция не поддерживается")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0048_remove_duplicate_subcategories"),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_subcategories_with_products, reverse_merge_duplicate_subcategories_with_products),
    ]
