# Generated by Django 5.2.9 on 2025-12-14 04:04

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def remove_generic_clothing_subcategory(apps, schema_editor):
    """Удаляет лишнюю подкатегорию 'Одежда' (women-fashion), оставляя только специфичные (Мужская, Женская, Детская, Унисекс)."""
    Category = apps.get_model('catalog', 'Category')
    
    # Находим корневую категорию "Одежда"
    root_clothing = Category.objects.filter(slug='clothing', parent__isnull=True).first()
    
    if not root_clothing:
        logger.warning("Не найдена корневая категория 'Одежда'. Пропускаем удаление.")
        return
    
    # Находим лишнюю подкатегорию "Одежда" (women-fashion)
    generic_clothing = Category.objects.filter(
        parent=root_clothing,
        slug='women-fashion',
        name='Одежда'
    ).first()
    
    if not generic_clothing:
        logger.info("Не найдена подкатегория 'Одежда' (women-fashion). Пропускаем.")
        return
    
    # Проверяем, есть ли продукты или подкатегории
    has_products = False
    has_children = False
    
    try:
        from apps.catalog.models import ClothingProduct, ShoeProduct, ElectronicsProduct, Product
        has_products = (
            ClothingProduct.objects.filter(category=generic_clothing).exists() or
            ShoeProduct.objects.filter(category=generic_clothing).exists() or
            ElectronicsProduct.objects.filter(category=generic_clothing).exists() or
            Product.objects.filter(category=generic_clothing).exists()
        )
    except:
        pass
    
    has_children = Category.objects.filter(parent=generic_clothing).exists()
    
    if has_products or has_children:
        # Если есть продукты или подкатегории - переносим их в корневую категорию "Одежда"
        try:
            from apps.catalog.models import ClothingProduct, ShoeProduct, ElectronicsProduct, Product
            
            # Переносим продукты
            clothing_products = ClothingProduct.objects.filter(category=generic_clothing)
            if clothing_products.exists():
                clothing_products.update(category=root_clothing)
                logger.info(f"Перенесено {clothing_products.count()} ClothingProduct в корневую категорию 'Одежда'")
            
            shoe_products = ShoeProduct.objects.filter(category=generic_clothing)
            if shoe_products.exists():
                shoe_products.update(category=root_clothing)
                logger.info(f"Перенесено {shoe_products.count()} ShoeProduct в корневую категорию 'Одежда'")
            
            electronics_products = ElectronicsProduct.objects.filter(category=generic_clothing)
            if electronics_products.exists():
                electronics_products.update(category=root_clothing)
                logger.info(f"Перенесено {electronics_products.count()} ElectronicsProduct в корневую категорию 'Одежда'")
            
            products = Product.objects.filter(category=generic_clothing)
            if products.exists():
                products.update(category=root_clothing)
                logger.info(f"Перенесено {products.count()} Product в корневую категорию 'Одежда'")
        except Exception as e:
            logger.warning(f"Ошибка при переносе продуктов: {e}")
        
        # Переносим подкатегории
        children = Category.objects.filter(parent=generic_clothing)
        if children.exists():
            children.update(parent=root_clothing)
            logger.info(f"Перенесено {children.count()} подкатегорий в корневую категорию 'Одежда'")
    
    # Удаляем лишнюю подкатегорию
    logger.info(f"Удаляем лишнюю подкатегорию 'Одежда' (slug: {generic_clothing.slug}, id={generic_clothing.id})")
    generic_clothing.delete()
    logger.info("Лишняя подкатегория 'Одежда' удалена")


def reverse_remove_generic_clothing_subcategory(apps, schema_editor):
    """Обратная миграция - не реализована."""
    logger.warning("Обратная миграция не поддерживается")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0049_merge_duplicate_subcategories_with_products"),
    ]

    operations = [
        migrations.RunPython(remove_generic_clothing_subcategory, reverse_remove_generic_clothing_subcategory),
    ]
