# Generated by Django 5.2.9 on 2025-12-14 04:11

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def remove_duplicate_dresses_categories(apps, schema_editor):
    """Удаляет дубликаты категории 'Платья', оставляя только основную (dresses)."""
    Category = apps.get_model('catalog', 'Category')
    
    # Основная категория "Платья" (должна остаться)
    main_dresses = Category.objects.filter(id=93, slug='dresses').first()
    
    # Дубликаты для удаления
    duplicate_ids = [158, 193]  # dresses-turkish, dresses-turkish-clothing-1
    duplicates = Category.objects.filter(id__in=duplicate_ids)
    
    if not main_dresses:
        logger.warning("Не найдена основная категория 'Платья' (id=93). Пропускаем.")
        return
    
    deleted_count = 0
    
    for cat in duplicates:
        # Переносим продукты в основную категорию
        try:
            from apps.catalog.models import ClothingProduct, ShoeProduct, ElectronicsProduct, Product
            
            # Переносим ClothingProduct
            clothing_products = ClothingProduct.objects.filter(category=cat)
            if clothing_products.exists():
                clothing_products.update(category=main_dresses)
                logger.info(f"Перенесено {clothing_products.count()} ClothingProduct из '{cat.name}' (id={cat.id}) в основную категорию 'Платья' (id={main_dresses.id})")
            
            # Переносим ShoeProduct
            shoe_products = ShoeProduct.objects.filter(category=cat)
            if shoe_products.exists():
                shoe_products.update(category=main_dresses)
                logger.info(f"Перенесено {shoe_products.count()} ShoeProduct из '{cat.name}' (id={cat.id}) в основную категорию 'Платья' (id={main_dresses.id})")
            
            # Переносим ElectronicsProduct
            electronics_products = ElectronicsProduct.objects.filter(category=cat)
            if electronics_products.exists():
                electronics_products.update(category=main_dresses)
                logger.info(f"Перенесено {electronics_products.count()} ElectronicsProduct из '{cat.name}' (id={cat.id}) в основную категорию 'Платья' (id={main_dresses.id})")
            
            # Переносим Product
            products = Product.objects.filter(category=cat)
            if products.exists():
                products.update(category=main_dresses)
                logger.info(f"Перенесено {products.count()} Product из '{cat.name}' (id={cat.id}) в основную категорию 'Платья' (id={main_dresses.id})")
        except Exception as e:
            logger.warning(f"Ошибка при переносе продуктов из '{cat.name}' (id={cat.id}): {e}")
        
        # Переносим подкатегории
        children = Category.objects.filter(parent=cat)
        if children.exists():
            children.update(parent=main_dresses)
            logger.info(f"Перенесено {children.count()} подкатегорий из '{cat.name}' (id={cat.id}) в основную категорию 'Платья' (id={main_dresses.id})")
        
        # Удаляем дубликат
        logger.info(f"Удаляем дубликат '{cat.name}' (slug: {cat.slug}, id={cat.id})")
        cat.delete()
        deleted_count += 1
    
    logger.info(f"Удалено дубликатов 'Платья': {deleted_count}")


def reverse_remove_duplicate_dresses_categories(apps, schema_editor):
    """Обратная миграция - не реализована."""
    logger.warning("Обратная миграция не поддерживается")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0050_remove_generic_clothing_subcategory"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_dresses_categories, reverse_remove_duplicate_dresses_categories),
    ]
