# Generated by Django 5.2.9 on 2025-12-14 04:16

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def activate_women_clothing_category(apps, schema_editor):
    """Активирует категорию 'Женская одежда' и устанавливает правильный порядок сортировки."""
    Category = apps.get_model('catalog', 'Category')
    
    # Находим категорию "Женская одежда"
    women_clothing = Category.objects.filter(id=8, slug='womens-wear').first()
    
    if not women_clothing:
        logger.warning("Не найдена категория 'Женская одежда' (id=8). Пропускаем.")
        return
    
    # Активируем категорию
    women_clothing.is_active = True
    women_clothing.sort_order = 1  # Первая в списке подкатегорий по полу
    women_clothing.save(update_fields=['is_active', 'sort_order'])
    
    logger.info(f"Активирована категория 'Женская одежда' (id={women_clothing.id}, sort_order={women_clothing.sort_order})")


def reverse_activate_women_clothing_category(apps, schema_editor):
    """Обратная миграция - не реализована."""
    logger.warning("Обратная миграция не поддерживается")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0051_remove_duplicate_dresses_categories"),
    ]

    operations = [
        migrations.RunPython(activate_women_clothing_category, reverse_activate_women_clothing_category),
    ]
