# Generated by Django 5.2.9 on 2025-12-14 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0052_activate_women_clothing_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Переведенное название бренда",
                        max_length=200,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Переведенное описание бренда",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод бренда",
                "verbose_name_plural": "Переводы брендов",
                "ordering": ["brand", "locale"],
                "indexes": [
                    models.Index(fields=["brand", "locale"], name="catalog_bra_brand_i_00030b_idx")
                ],
                "unique_together": {("brand", "locale")},
            },
        ),
    ]
