# Generated by Django 5.2.9 on 2025-12-14 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0053_add_brand_translation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Переведенное описание товара",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод товара",
                "verbose_name_plural": "Переводы товаров",
                "ordering": ["product", "locale"],
                "indexes": [
                    models.Index(
                        fields=["product", "locale"], name="catalog_pro_product_91e48b_idx"
                    )
                ],
                "unique_together": {("product", "locale")},
            },
        ),
    ]
