# Generated by Django 5.2.9 on 2025-12-14 23:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0054_producttranslation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FurnitureProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("GBP", "GBP"),
                            ("USDT", "USDT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("material", models.CharField(blank=True, max_length=100, verbose_name="Материал")),
                (
                    "furniture_type",
                    models.CharField(
                        blank=True,
                        help_text="Например: диван, стол, стул",
                        max_length=100,
                        verbose_name="Тип мебели",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="Например: 200x100x80 см",
                        max_length=200,
                        verbose_name="Размеры",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                ("main_image", models.URLField(blank=True, verbose_name="Главное изображение")),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="furniture_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="furniture_products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар мебели",
                "verbose_name_plural": "Товары мебели",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FurnitureProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Переведенное описание товара мебели",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.furnitureproduct",
                        verbose_name="Товар мебели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод товара мебели",
                "verbose_name_plural": "Переводы товаров мебели",
                "ordering": ["product", "locale"],
            },
        ),
        migrations.CreateModel(
            name="FurnitureVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="Название варианта"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Автогенерация по названию/цвету, можно переопределить.",
                        max_length=600,
                        unique=True,
                        verbose_name="Slug варианта",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                ("barcode", models.CharField(blank=True, max_length=100, verbose_name="Штрихкод")),
                ("gtin", models.CharField(blank=True, max_length=100, verbose_name="GTIN")),
                ("mpn", models.CharField(blank=True, max_length=100, verbose_name="MPN")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("GBP", "GBP"),
                            ("USDT", "USDT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(blank=True, verbose_name="Главное изображение варианта"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.furnitureproduct",
                        verbose_name="Товар мебели (родитель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант мебели",
                "verbose_name_plural": "Варианты мебели",
                "ordering": ["product", "sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FurnitureVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.furniturevariant",
                        verbose_name="Вариант мебели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта мебели",
                "verbose_name_plural": "Изображения вариантов мебели",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название услуги")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Стоимость услуги",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("GBP", "GBP"),
                            ("USDT", "USDT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Например: '1 час', '30 минут', '1 день'",
                        max_length=100,
                        verbose_name="Длительность",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        help_text="Например: 'Консультация', 'Диагностика', 'Лечение'",
                        max_length=100,
                        verbose_name="Тип услуги",
                    ),
                ),
                (
                    "main_image",
                    models.URLField(
                        blank=True,
                        help_text="URL основного изображения (ссылка на CDN или внутреннее хранилище).",
                        verbose_name="Главное изображение",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемая")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Переведенное описание услуги",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод услуги",
                "verbose_name_plural": "Переводы услуг",
                "ordering": ["service", "locale"],
            },
        ),
        migrations.CreateModel(
            name="ShoeProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Переведенное описание товара обуви",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.shoeproduct",
                        verbose_name="Товар обуви",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод товара обуви",
                "verbose_name_plural": "Переводы товаров обуви",
                "ordering": ["product", "locale"],
            },
        ),
        migrations.CreateModel(
            name="ClothingProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Переведенное описание товара одежды",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.clothingproduct",
                        verbose_name="Товар одежды",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод товара одежды",
                "verbose_name_plural": "Переводы товаров одежды",
                "ordering": ["product", "locale"],
                "indexes": [
                    models.Index(
                        fields=["product", "locale"], name="catalog_clo_product_643bd3_idx"
                    )
                ],
                "unique_together": {("product", "locale")},
            },
        ),
        migrations.CreateModel(
            name="ElectronicsProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Переведенное описание товара электроники",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.electronicsproduct",
                        verbose_name="Товар электроники",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод товара электроники",
                "verbose_name_plural": "Переводы товаров электроники",
                "ordering": ["product", "locale"],
                "indexes": [
                    models.Index(
                        fields=["product", "locale"], name="catalog_ele_product_6c1de8_idx"
                    )
                ],
                "unique_together": {("product", "locale")},
            },
        ),
        migrations.AddIndex(
            model_name="furnitureproduct",
            index=models.Index(fields=["external_id"], name="catalog_fur_externa_dcf93f_idx"),
        ),
        migrations.AddIndex(
            model_name="furnitureproduct",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_fur_is_acti_12b04e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="furnitureproduct",
            index=models.Index(fields=["category", "brand"], name="catalog_fur_categor_5f0aa8_idx"),
        ),
        migrations.AddIndex(
            model_name="furnitureproduct",
            index=models.Index(fields=["price"], name="catalog_fur_price_d4e6ed_idx"),
        ),
        migrations.AddIndex(
            model_name="furnitureproducttranslation",
            index=models.Index(fields=["product", "locale"], name="catalog_fur_product_6f8fe2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="furnitureproducttranslation",
            unique_together={("product", "locale")},
        ),
        migrations.AddIndex(
            model_name="furniturevariant",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_fur_product_824ddb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="furniturevariant",
            index=models.Index(fields=["slug"], name="catalog_fur_slug_512794_idx"),
        ),
        migrations.AddIndex(
            model_name="furniturevariant",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_fur_is_acti_0796f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="furniturevariantimage",
            index=models.Index(
                fields=["variant", "sort_order"], name="catalog_fur_variant_8a0cf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["external_id"], name="catalog_ser_externa_e94631_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["is_active"], name="catalog_ser_is_acti_43a295_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["category"], name="catalog_ser_categor_4331f9_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["price"], name="catalog_ser_price_4d064f_idx"),
        ),
        migrations.AddIndex(
            model_name="servicetranslation",
            index=models.Index(fields=["service", "locale"], name="catalog_ser_service_bc51a9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="servicetranslation",
            unique_together={("service", "locale")},
        ),
        migrations.AddIndex(
            model_name="shoeproducttranslation",
            index=models.Index(fields=["product", "locale"], name="catalog_sho_product_e649cc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="shoeproducttranslation",
            unique_together={("product", "locale")},
        ),
    ]
