# Generated by Django 5.2.9 on 2025-12-15 01:12

from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    """Удаляет дубликаты категорий по комбинации (name, parent)."""
    Category = apps.get_model('catalog', 'Category')
    
    # Находим все подкатегории (с родителем), сортируем по ID (первая = самая старая)
    categories = Category.objects.filter(parent__isnull=False).order_by('id')
    
    seen = {}
    duplicates_to_remove = []
    
    for cat in categories:
        key = (cat.name, cat.parent_id)
        if key in seen:
            # Это дубликат - оставляем первую запись (с меньшим ID), удаляем новую
            duplicates_to_remove.append(cat.id)
        else:
            seen[key] = cat
    
    # Удаляем дубликаты
    if duplicates_to_remove:
        Category.objects.filter(id__in=duplicates_to_remove).delete()
        print(f'Удалено {len(duplicates_to_remove)} дубликатов категорий')


def reverse_remove_duplicates(apps, schema_editor):
    """Обратная операция - ничего не делаем, так как дубликаты уже удалены."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0055_furnitureproduct_furnitureproducttranslation_and_more"),
    ]

    operations = [
        # Сначала удаляем дубликаты
        migrations.RunPython(remove_duplicates, reverse_remove_duplicates, atomic=False),
    ]
