# Generated by Django 5.2.9 on 2025-12-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0056_remove_category_duplicates_and_add_unique_constraint"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "parent")},
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name", "parent"], name="catalog_cat_name_37c1be_idx"),
        ),
    ]
