# Generated by Django 5.2.9 on 2025-12-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0057_add_category_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryServices",
            fields=[],
            options={
                "verbose_name": "Категория — Услуги",
                "verbose_name_plural": "Категории — Услуги",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
    ]
