# Generated by Django 5.2.9 on 2025-12-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0059_footersettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FooterSettings",
        ),
    ]
