# Generated by Django 5.2.10 on 2026-01-19 21:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0061_remove_product_name_en_description_en"),
    ]

    operations = [
        migrations.CreateModel(
            name="JewelryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("GBP", "GBP"),
                            ("USDT", "USDT"),
                        ],
                        default="RUB",
                        help_text="Выбирается из списка расчётных валют, используемых в прайсах.",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                (
                    "jewelry_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ring", "Кольцо"),
                            ("bracelet", "Браслет"),
                            ("necklace", "Цепь/ожерелье"),
                            ("earrings", "Серьги"),
                            ("pendant", "Подвеска"),
                        ],
                        help_text="ring, bracelet, necklace, earrings, pendant",
                        max_length=32,
                        verbose_name="Тип украшения",
                    ),
                ),
                ("material", models.CharField(blank=True, max_length=100, verbose_name="Материал")),
                (
                    "metal_purity",
                    models.CharField(blank=True, max_length=50, verbose_name="Проба металла"),
                ),
                (
                    "stone_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Тип камня"),
                ),
                (
                    "carat_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Вес камней, карат",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                ("main_image", models.URLField(blank=True, verbose_name="Главное изображение")),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jewelry_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jewelry_products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар — Украшения",
                "verbose_name_plural": "Товары — Украшения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.jewelryproduct",
                        verbose_name="Товар украшений",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара украшений",
                "verbose_name_plural": "Изображения товаров украшений",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Переведенное описание товара украшений",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.jewelryproduct",
                        verbose_name="Товар украшений",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод товара украшений",
                "verbose_name_plural": "Переводы товаров украшений",
                "ordering": ["product", "locale"],
            },
        ),
        migrations.CreateModel(
            name="JewelryVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="Название варианта"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Автогенерация по названию/цвету/материалу, можно переопределить.",
                        max_length=600,
                        unique=True,
                        verbose_name="Slug варианта",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                (
                    "material",
                    models.CharField(blank=True, max_length=100, verbose_name="Материал варианта"),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="Используйте таблицу размеров ниже; поле оставлено для совместимости.",
                        max_length=50,
                        verbose_name="Размер (устарело)",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                ("barcode", models.CharField(blank=True, max_length=100, verbose_name="Штрихкод")),
                ("gtin", models.CharField(blank=True, max_length=100, verbose_name="GTIN")),
                ("mpn", models.CharField(blank=True, max_length=100, verbose_name="MPN")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("GBP", "GBP"),
                            ("USDT", "USDT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(blank=True, verbose_name="Главное изображение варианта"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.jewelryproduct",
                        verbose_name="Товар украшений (родитель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант украшения",
                "verbose_name_plural": "Варианты украшений",
                "ordering": ["product", "sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.jewelryvariant",
                        verbose_name="Вариант украшения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта украшения",
                "verbose_name_plural": "Изображения вариантов украшений",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="JewelryVariantSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "size_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Числовое значение (например 16.5).",
                        max_digits=6,
                        null=True,
                        verbose_name="Значение размера",
                    ),
                ),
                (
                    "size_unit",
                    models.CharField(
                        choices=[
                            ("mm", "Миллиметры"),
                            ("cm", "Сантиметры"),
                            ("standard", "Стандарт"),
                        ],
                        default="standard",
                        max_length=16,
                        verbose_name="Единица",
                    ),
                ),
                (
                    "size_type",
                    models.CharField(
                        choices=[
                            ("ring_size", "Размер кольца"),
                            ("bracelet_length", "Длина браслета"),
                            ("necklace_length", "Длина цепи/ожерелья"),
                            ("standard", "Стандарт"),
                        ],
                        default="standard",
                        max_length=32,
                        verbose_name="Тип размера",
                    ),
                ),
                (
                    "size_display",
                    models.CharField(
                        blank=True,
                        help_text="Например: '16 мм', 'US 7', '18 см', 'Стандарт'.",
                        max_length=50,
                        verbose_name="Отображаемый размер",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Остаток"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="catalog.jewelryvariant",
                        verbose_name="Вариант украшения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер варианта украшения",
                "verbose_name_plural": "Размеры варианта украшения",
                "ordering": ["variant", "sort_order", "size_display"],
            },
        ),
        migrations.AddIndex(
            model_name="jewelryproduct",
            index=models.Index(fields=["external_id"], name="catalog_jew_externa_a4a552_idx"),
        ),
        migrations.AddIndex(
            model_name="jewelryproduct",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_jew_is_acti_2690e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jewelryproduct",
            index=models.Index(fields=["category", "brand"], name="catalog_jew_categor_2fef25_idx"),
        ),
        migrations.AddIndex(
            model_name="jewelryproduct",
            index=models.Index(fields=["price"], name="catalog_jew_price_a760d7_idx"),
        ),
        migrations.AddIndex(
            model_name="jewelryproduct",
            index=models.Index(fields=["jewelry_type"], name="catalog_jew_jewelry_4b33e8_idx"),
        ),
        migrations.AddIndex(
            model_name="jewelryproductimage",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_jew_product_bdb9fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jewelryproducttranslation",
            index=models.Index(fields=["product", "locale"], name="catalog_jew_product_583b0e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="jewelryproducttranslation",
            unique_together={("product", "locale")},
        ),
        migrations.AddIndex(
            model_name="jewelryvariant",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_jew_product_5f50ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jewelryvariant",
            index=models.Index(fields=["slug"], name="catalog_jew_slug_23cfc7_idx"),
        ),
        migrations.AddIndex(
            model_name="jewelryvariant",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_jew_is_acti_654966_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jewelryvariantimage",
            index=models.Index(
                fields=["variant", "sort_order"], name="catalog_jew_variant_b601db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jewelryvariantsize",
            index=models.Index(
                fields=["variant", "sort_order"], name="catalog_jew_variant_8c4537_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jewelryvariantsize",
            index=models.Index(
                fields=["variant", "size_display"], name="catalog_jew_variant_1c4c7f_idx"
            ),
        ),
    ]
