# Generated by Django 5.2.10 on 2026-01-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0062_jewelryproduct_jewelryproductimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBooks",
            fields=[],
            options={
                "verbose_name": "Товар — Книги",
                "verbose_name_plural": "Товары — Книги",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.AddField(
            model_name="product",
            name="cover_type",
            field=models.CharField(
                blank=True,
                help_text="Твердая, мягкая и т.д.",
                max_length=50,
                verbose_name="Тип обложки",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_bestseller",
            field=models.BooleanField(default=False, verbose_name="Бестселлер"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AddField(
            model_name="product",
            name="isbn",
            field=models.CharField(
                blank=True, help_text="ISBN книги", max_length=20, verbose_name="ISBN"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="language",
            field=models.CharField(
                blank=True, default="Русский", max_length=50, verbose_name="Язык"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pages",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество страниц"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="publication_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата публикации"),
        ),
        migrations.AddField(
            model_name="product",
            name="publisher",
            field=models.CharField(blank=True, max_length=200, verbose_name="Издательство"),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Рейтинг книги от 0 до 5",
                max_digits=3,
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество отзывов"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("medicines", "Медицина"),
                    ("supplements", "БАДы"),
                    ("medical_equipment", "Медтехника"),
                    ("clothing", "Одежда"),
                    ("underwear", "Нижнее бельё"),
                    ("headwear", "Головные уборы"),
                    ("shoes", "Обувь"),
                    ("electronics", "Электроника"),
                    ("furniture", "Мебель"),
                    ("tableware", "Посуда"),
                    ("accessories", "Аксессуары"),
                    ("jewelry", "Украшения"),
                    ("books", "Книги"),
                ],
                db_index=True,
                default="medicines",
                max_length=32,
                verbose_name="Тип товара",
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "photo",
                    models.URLField(
                        blank=True, help_text="URL фотографии автора", verbose_name="Фото"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"], name="catalog_aut_last_na_73102a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="catalog.author",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_authors",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор книги",
                "verbose_name_plural": "Авторы книг",
                "indexes": [
                    models.Index(
                        fields=["product", "author"], name="catalog_pro_product_621ec8_idx"
                    )
                ],
                "unique_together": {("product", "author")},
            },
        ),
    ]
