# Generated by Django 5.2.10 on 2026-01-24 17:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0063_productbooks_product_cover_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="Название варианта"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Автогенерация по названию/формату",
                        max_length=600,
                        unique=True,
                        verbose_name="Slug варианта",
                    ),
                ),
                (
                    "cover_type",
                    models.CharField(
                        blank=True,
                        help_text="Твердая, мягкая, суперобложка",
                        max_length=50,
                        verbose_name="Тип обложки",
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        blank=True,
                        help_text="Твердый, мягкий, электронный",
                        max_length=50,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="ISBN для конкретного варианта",
                        max_length=20,
                        verbose_name="ISBN",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                ("barcode", models.CharField(blank=True, max_length=100, verbose_name="Штрихкод")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("GBP", "GBP"),
                            ("USDT", "USDT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(blank=True, verbose_name="Главное изображение варианта"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_variants",
                        to="catalog.product",
                        verbose_name="Книга (родитель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант книги",
                "verbose_name_plural": "Варианты книг",
                "ordering": ["product", "sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.bookvariant",
                        verbose_name="Вариант книги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта книги",
                "verbose_name_plural": "Изображения вариантов книг",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookVariantSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="Например: Твердая, Мягкая, Электронная, 130x200, 140x215",
                        max_length=50,
                        verbose_name="Формат/размер",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Остаток"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="catalog.bookvariant",
                        verbose_name="Вариант книги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Формат варианта книги",
                "verbose_name_plural": "Форматы вариантов книг",
                "ordering": ["variant", "sort_order", "size"],
            },
        ),
        migrations.AddIndex(
            model_name="bookvariant",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_boo_product_639630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookvariant",
            index=models.Index(fields=["slug"], name="catalog_boo_slug_f1cd4f_idx"),
        ),
        migrations.AddIndex(
            model_name="bookvariant",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_boo_is_acti_240b10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookvariantimage",
            index=models.Index(
                fields=["variant", "sort_order"], name="catalog_boo_variant_c090a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookvariantsize",
            index=models.Index(
                fields=["variant", "sort_order"], name="catalog_boo_variant_edd84d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookvariantsize",
            index=models.Index(fields=["variant", "size"], name="catalog_boo_variant_0e649b_idx"),
        ),
    ]
