# Generated by Django 5.2.10 on 2026-01-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0064_bookvariant_bookvariantimage_bookvariantsize_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryBooks",
            fields=[],
            options={
                "verbose_name": "Категория — Книги",
                "verbose_name_plural": "Категории — Книги (Жанры)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.AlterModelOptions(
            name="productauthor",
            options={
                "ordering": ["sort_order", "created_at"],
                "verbose_name": "Автор книги",
                "verbose_name_plural": "Авторы книг",
            },
        ),
        migrations.AddField(
            model_name="productauthor",
            name="sort_order",
            field=models.IntegerField(
                default=0,
                help_text="Порядок отображения авторов",
                verbose_name="Порядок сортировки",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="primary_category_slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medicines", "medicines"),
                    ("supplements", "supplements"),
                    ("medical-equipment", "medical-equipment"),
                    ("clothing", "clothing"),
                    ("shoes", "shoes"),
                    ("electronics", "electronics"),
                    ("furniture", "furniture"),
                    ("tableware", "tableware"),
                    ("accessories", "accessories"),
                    ("jewelry", "jewelry"),
                    ("underwear", "underwear"),
                    ("headwear", "headwear"),
                    ("books", "books"),
                ],
                help_text="Явно укажите ключевой slug для бренда (clothing, shoes, electronics и т.д.).",
                max_length=64,
                verbose_name="Основная категория (slug)",
            ),
        ),
        migrations.AddIndex(
            model_name="productauthor",
            index=models.Index(fields=["sort_order"], name="catalog_pro_sort_or_073f35_idx"),
        ),
    ]
