# Generated by Django 5.2.10 on 2026-01-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0065_categorybooks_alter_productauthor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.URLField(
                blank=True,
                help_text="URL основного изображения (ссылка на CDN или внутреннее хранилище).",
                max_length=1000,
                verbose_name="Главное изображение",
            ),
        ),
    ]
