# Generated by Django 5.2.10 on 2026-01-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0066_increase_main_image_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingproductimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=1000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsproductimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=1000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproductimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=1000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=1000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="shoeproductimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=1000,
                verbose_name="URL изображения",
            ),
        ),
    ]
