# Generated by Django 5.2.10 on 2026-01-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0067_increase_image_url_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingproductimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="clothingvariantimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsproductimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproductimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryvariantimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.URLField(
                blank=True,
                help_text="URL основного изображения (ссылка на CDN или внутреннее хранилище).",
                max_length=2000,
                verbose_name="Главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="shoeproductimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="shoevariantimage",
            name="image_url",
            field=models.URLField(
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
    ]
