# Generated by Django 5.2.10 on 2026-01-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0068_alter_clothingproductimage_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
    ]
