# Generated by Django 5.2.10 on 2026-01-27 22:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0070_currency_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencyrate",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Курс валют",
                "verbose_name_plural": "Курсы валют",
            },
        ),
        migrations.AlterModelOptions(
            name="currencyupdatelog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Лог обновления курсов",
                "verbose_name_plural": "Логи обновления курсов",
            },
        ),
        migrations.AlterModelOptions(
            name="marginsettings",
            options={
                "ordering": ["currency_pair"],
                "verbose_name": "Настройка маржи",
                "verbose_name_plural": "Настройки маржи",
            },
        ),
        migrations.AlterModelOptions(
            name="productprice",
            options={
                "ordering": ["currency"],
                "verbose_name": "Цена товара",
                "verbose_name_plural": "Цены товаров",
            },
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="from_currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Турецкая лира"),
                    ("RUB", "Российский рубль"),
                    ("KZT", "Казахстанский тенге"),
                    ("USD", "Доллар США"),
                    ("EUR", "Евро"),
                ],
                max_length=3,
                verbose_name="Из валюты",
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="rate",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="source",
            field=models.CharField(
                choices=[
                    ("centralbank_rf", "Центробанк РФ"),
                    ("nationalbank_kz", "Нацбанк Казахстана"),
                    ("centralbank_tr", "Центробанк Турции"),
                    ("openexchangerates", "OpenExchangeRates API"),
                    ("manual", "Ручной ввод"),
                ],
                max_length=50,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="to_currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Турецкая лира"),
                    ("RUB", "Российский рубль"),
                    ("KZT", "Казахстанский тенге"),
                    ("USD", "Доллар США"),
                    ("EUR", "Евро"),
                ],
                max_length=3,
                verbose_name="В валюту",
            ),
        ),
        migrations.AlterField(
            model_name="currencyrate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="currencyupdatelog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="currencyupdatelog",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Ошибка"),
        ),
        migrations.AlterField(
            model_name="currencyupdatelog",
            name="execution_time_seconds",
            field=models.FloatField(blank=True, null=True, verbose_name="Время выполнения (сек)"),
        ),
        migrations.AlterField(
            model_name="currencyupdatelog",
            name="rates_updated",
            field=models.PositiveIntegerField(default=0, verbose_name="Обновлено курсов"),
        ),
        migrations.AlterField(
            model_name="currencyupdatelog",
            name="source",
            field=models.CharField(max_length=50, verbose_name="Источник"),
        ),
        migrations.AlterField(
            model_name="currencyupdatelog",
            name="success",
            field=models.BooleanField(default=True, verbose_name="Успешно"),
        ),
        migrations.AlterField(
            model_name="marginsettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="marginsettings",
            name="currency_pair",
            field=models.CharField(
                help_text="Формат: ИЗ-В (например, TRY-RUB)",
                max_length=10,
                verbose_name="Пара валют",
            ),
        ),
        migrations.AlterField(
            model_name="marginsettings",
            name="description",
            field=models.TextField(
                blank=True, help_text="Описание настройки маржи", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="marginsettings",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="marginsettings",
            name="margin_percentage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Процент маржи (например, 15 для 15%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Маржа (%)",
            ),
        ),
        migrations.AlterField(
            model_name="marginsettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="converted_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена после конвертации",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Конвертированная цена",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Турецкая лира"),
                    ("RUB", "Российский рубль"),
                    ("KZT", "Казахстанский тенге"),
                    ("USD", "Доллар США"),
                    ("EUR", "Евро"),
                ],
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="is_base_price",
            field=models.BooleanField(
                default=False,
                help_text="Является ли это базовой ценой из источника",
                verbose_name="Базовая цена",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена в исходной валюте",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Оригинальная цена",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="price_with_margin",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Финальная цена с учетом маржи",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена с маржой",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="catalog.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
    ]
