# Generated by Django 5.2.10 on 2026-01-27 23:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0071_alter_currencyrate_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productprice",
            options={"verbose_name": "Цены товара", "verbose_name_plural": "Цены товаров"},
        ),
        migrations.AlterUniqueTogether(
            name="productprice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productprice",
            name="air_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Добавка к финальной цене за авиадоставку",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость авиадоставки",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="base_currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Турецкая лира"),
                    ("RUB", "Российский рубль"),
                    ("KZT", "Казахстанский тенге"),
                    ("USD", "Доллар США"),
                    ("EUR", "Евро"),
                ],
                default="TRY",
                max_length=3,
                verbose_name="Базовая валюта",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена в исходной валюте",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Базовая цена",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="eur_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Конвертированная цена в евро",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в EUR",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="eur_price_with_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в EUR с маржой",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="kzt_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Конвертированная цена в тенге",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в KZT",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="kzt_price_with_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в KZT с маржой",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="rub_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Конвертированная цена в рублях",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в RUB",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="rub_price_with_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в RUB с маржой",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="sea_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Добавка к финальной цене за морскую доставку",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость морской доставки",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="usd_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Конвертированная цена в долларах",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в USD",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="usd_price_with_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в USD с маржой",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_info",
                to="catalog.product",
                verbose_name="Товар",
            ),
        ),
        migrations.RemoveField(
            model_name="productprice",
            name="converted_price",
        ),
        migrations.RemoveField(
            model_name="productprice",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="productprice",
            name="is_base_price",
        ),
        migrations.RemoveField(
            model_name="productprice",
            name="original_price",
        ),
        migrations.RemoveField(
            model_name="productprice",
            name="price_with_margin",
        ),
    ]
