# Generated by Django 5.2.10 on 2026-01-27 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0072_update_productprice_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="ground_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Добавка к финальной цене за наземную доставку",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость наземной доставки",
            ),
        ),
    ]
