# Generated by Django 5.2.10 on 2026-01-28 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0073_add_ground_shipping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprice",
            name="air_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фиксированная стоимость доставки в валюте продажи (не в процентах)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость авиадоставки",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="ground_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фиксированная стоимость доставки в валюте продажи (не в процентах)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость наземной доставки",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="sea_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фиксированная стоимость доставки в валюте продажи (не в процентах)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость морской доставки",
            ),
        ),
    ]
