# Generated by Django 5.2.10 on 2026-01-29 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0074_alter_productprice_air_shipping_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="try_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Конвертированная цена в турецких лирах",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в TRY",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="try_price_with_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена в TRY с маржой",
            ),
        ),
    ]
