# Generated by Django 5.2.10 on 2026-01-29 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0075_productprice_try_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencyrate",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "💰 Курс валют",
                "verbose_name_plural": "💰 Валюты — Курсы валют",
            },
        ),
        migrations.AlterModelOptions(
            name="currencyupdatelog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "💰 Лог обновления курсов",
                "verbose_name_plural": "💰 Валюты — Логи обновления курсов",
            },
        ),
        migrations.AlterModelOptions(
            name="marginsettings",
            options={
                "ordering": ["currency_pair"],
                "verbose_name": "💰 Настройка маржи",
                "verbose_name_plural": "💰 Валюты — Настройки маржи",
            },
        ),
        migrations.AlterModelOptions(
            name="productprice",
            options={
                "verbose_name": "💰 Цены товара",
                "verbose_name_plural": "💰 Валюты — Цены товаров",
            },
        ),
    ]
