# Generated by Django 5.2.10 on 2026-01-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0076_alter_currencyrate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookvariant",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="clothingproduct",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                help_text="Выбирается из списка расчётных валют, используемых в прайсах.",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="clothingvariant",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="furnitureproduct",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="furniturevariant",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproduct",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                help_text="Выбирается из списка расчётных валют, используемых в прайсах.",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryvariant",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                help_text="Выбирается из списка расчётных валют, используемых в прайсах.",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                help_text="Выбирается из списка расчётных валют, используемых в прайсах.",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="shoevariant",
            name="currency",
            field=models.CharField(
                choices=[
                    ("RUB", "RUB"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("TRY", "TRY"),
                    ("KZT", "KZT"),
                ],
                default="RUB",
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
    ]
