# Generated by Django 5.2.10 on 2026-02-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0078_clothingproductsize_shoeproductsize"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="clothingproductsize",
            new_name="catalog_clo_product_174dec_idx",
            old_name="catalog_clo_product_94d68d_idx",
        ),
        migrations.RenameIndex(
            model_name="clothingproductsize",
            new_name="catalog_clo_product_ffc704_idx",
            old_name="catalog_clo_product_22d41e_idx",
        ),
        migrations.RenameIndex(
            model_name="shoeproductsize",
            new_name="catalog_sho_product_5531f2_idx",
            old_name="catalog_sho_product_4c1e0d_idx",
        ),
        migrations.RenameIndex(
            model_name="shoeproductsize",
            new_name="catalog_sho_product_396449_idx",
            old_name="catalog_sho_product_93c1aa_idx",
        ),
    ]
