# Generated by Django 5.2.10 on 2026-02-01 15:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0079_rename_catalog_clo_product_94d68d_idx_catalog_clo_product_174dec_idx_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.UUIDField(verbose_name="ID варианта")),
                (
                    "base_currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Турецкая лира"),
                            ("RUB", "Российский рубль"),
                            ("KZT", "Казахстанский тенге"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                        ],
                        default="TRY",
                        max_length=3,
                        verbose_name="Базовая валюта",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Цена в исходной валюте",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "rub_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в рублях",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в RUB",
                    ),
                ),
                (
                    "rub_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в RUB с маржой",
                    ),
                ),
                (
                    "usd_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в долларах",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в USD",
                    ),
                ),
                (
                    "usd_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в USD с маржой",
                    ),
                ),
                (
                    "kzt_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в тенге",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в KZT",
                    ),
                ),
                (
                    "kzt_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в KZT с маржой",
                    ),
                ),
                (
                    "eur_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в евро",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в EUR",
                    ),
                ),
                (
                    "eur_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в EUR с маржой",
                    ),
                ),
                (
                    "try_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в турецких лирах",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в TRY",
                    ),
                ),
                (
                    "try_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в TRY с маржой",
                    ),
                ),
                (
                    "air_shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Фиксированная стоимость доставки в валюте продажи (не в процентах)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость авиадоставки",
                    ),
                ),
                (
                    "sea_shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Фиксированная стоимость доставки в валюте продажи (не в процентах)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость морской доставки",
                    ),
                ),
                (
                    "ground_shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Фиксированная стоимость доставки в валюте продажи (не в процентах)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость наземной доставки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип варианта",
                    ),
                ),
            ],
            options={
                "verbose_name": "💰 Цены варианта товара",
                "verbose_name_plural": "💰 Валюты — Цены вариантов товаров",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="catalog_pro_content_5d538d_idx"
                    )
                ],
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
