# Generated by Django 5.2.10 on 2026-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0080_productvariantprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/main/",
                verbose_name="Главное изображение (файл)",
            ),
        ),
    ]
