# Generated by Django 5.2.10 on 2026-02-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0081_add_product_main_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/books/variants/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/clothing/main/",
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="clothingproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/clothing/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="clothingvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/variants/",
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AddField(
            model_name="clothingvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/variants/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/electronics/main/",
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="electronicsproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/electronics/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/furniture/main/",
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="furniturevariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/furniture/variants/",
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AddField(
            model_name="furniturevariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/furniture/variants/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/jewelry/main/",
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="jewelryproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/jewelry/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="jewelryvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/jewelry/variants/",
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AddField(
            model_name="jewelryvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/jewelry/variants/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/shoes/main/",
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="shoeproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/shoes/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="shoevariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/shoes/variants/",
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AddField(
            model_name="shoevariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/shoes/variants/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
    ]
