# Generated by Django 5.2.10 on 2026-02-02 23:25

import apps.catalog.models
import apps.catalog.utils.storage_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0082_bookvariantimage_image_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="card_media",
            field=models.FileField(
                blank=True,
                help_text="Изображение, GIF или видео для карточки категории (до 50 МБ).",
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_category_card_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                            "gif",
                            "mp4",
                            "mov",
                            "webm",
                        ]
                    ),
                    apps.catalog.models.validate_card_media_file_size,
                ],
                verbose_name="Медиа для карточки",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_image_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
    ]
