# Generated by Django 5.2.10 on 2026-02-03 00:23

import apps.catalog.utils.storage_paths
import django.core.validators
from django.db import migrations, models


def column_exists(cursor, table, column):
    cursor.execute(
        """
        SELECT 1 FROM information_schema.columns
        WHERE table_name = %s AND column_name = %s
        """,
        [table, column],
    )
    return cursor.fetchone() is not None


def add_columns_if_missing(apps, schema_editor):
    """Добавляет колонки только если их ещё нет (идемпотентность при повторном migrate)."""
    with schema_editor.connection.cursor() as cursor:
        if not column_exists(cursor, "catalog_product", "main_video_file"):
            cursor.execute(
                'ALTER TABLE "catalog_product" ADD COLUMN "main_video_file" varchar(100) NULL'
            )
        if not column_exists(cursor, "catalog_productimage", "video_file"):
            cursor.execute(
                'ALTER TABLE "catalog_productimage" ADD COLUMN "video_file" varchar(100) NULL'
            )
        if not column_exists(cursor, "catalog_productimage", "video_url"):
            cursor.execute(
                'ALTER TABLE "catalog_productimage" ADD COLUMN "video_url" varchar(2000) NOT NULL DEFAULT \'\''
            )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0083_alter_category_card_media_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="product",
                    name="main_video_file",
                    field=models.FileField(
                        blank=True,
                        help_text="Видео-файл товара (загружается в R2/локальное хранилище).",
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                            )
                        ],
                        verbose_name="Главное видео (файл)",
                    ),
                ),
                migrations.AddField(
                    model_name="productimage",
                    name="video_file",
                    field=models.FileField(
                        blank=True,
                        help_text="Видео-файл (загружается в R2/локальное хранилище).",
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_product_image_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                            )
                        ],
                        verbose_name="Видео (файл)",
                    ),
                ),
                migrations.AddField(
                    model_name="productimage",
                    name="video_url",
                    field=models.URLField(
                        blank=True,
                        help_text="URL видео (Instagram, YouTube и т.д.).",
                        max_length=2000,
                        verbose_name="URL видео",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_columns_if_missing, migrations.RunPython.noop),
            ],
        ),
    ]
