# Generated by Django 5.2.10 on 2026-02-03 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0084_product_main_video_file_productimage_video_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="products/clothing/main/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram). При сохранении скачивается в хранилище.",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
    ]
