# Generated by Django 5.2.10 on 2026-02-03 19:42

import apps.catalog.models
import apps.catalog.utils.storage_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0085_clothingproduct_main_video_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannermedia",
            name="gif_file",
            field=models.FileField(
                blank=True,
                help_text="Локальный GIF файл",
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_banner_gif_upload_path,
                verbose_name="GIF файл",
            ),
        ),
        migrations.AlterField(
            model_name="bannermedia",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Изображение для баннера (JPG, PNG)",
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_banner_image_upload_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="bannermedia",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Локальный видеофайл (MP4, WebM)",
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_banner_video_upload_path,
                verbose_name="Видеофайл",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="card_media",
            field=models.FileField(
                blank=True,
                help_text="Изображение, GIF или видео для карточки бренда (до 50 МБ).",
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_brand_card_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                            "gif",
                            "mp4",
                            "mov",
                            "webm",
                        ]
                    ),
                    apps.catalog.models.validate_card_media_file_size,
                ],
                verbose_name="Медиа для карточки",
            ),
        ),
    ]
