# Generated by Django 5.2.10 on 2026-02-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0086_alter_bannermedia_gif_file_alter_bannermedia_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
    ]
