# Generated by Django 5.2.10 on 2026-02-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0087_alter_productimage_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="keywords",
            field=models.JSONField(blank=True, default=list, verbose_name="Ключевые слова"),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="SEO описание"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_title",
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name="SEO заголовок"
            ),
        ),
    ]
