# Generated by Django 5.2.11 on 2026-02-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0088_product_keywords_product_seo_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bannermedia",
            options={
                "ordering": ["banner", "sort_order", "id"],
                "verbose_name": "Медиа баннера",
                "verbose_name_plural": "Медиа баннеров",
            },
        ),
    ]
