# Generated by Django 5.2.11 on 2026-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0089_alter_bannermedia_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="position",
            field=models.CharField(
                choices=[
                    ("main", "1 — Главный"),
                    ("after_brands", "2 — Второй"),
                    ("before_footer", "3 — Третий"),
                    ("after_popular_products", "4 — Четвертый"),
                ],
                db_index=True,
                default="main",
                max_length=50,
                verbose_name="Позиция баннера",
            ),
        ),
    ]
