# Generated by Django 5.2.11 on 2026-02-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0090_alter_banner_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryPerfumery",
            fields=[],
            options={
                "verbose_name": "Категория — Парфюмерия",
                "verbose_name_plural": "Категории — Парфюмерия",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="ProductPerfumery",
            fields=[],
            options={
                "verbose_name": "Товар — Парфюмерия",
                "verbose_name_plural": "Товары — Парфюмерия",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.product",),
        ),
        migrations.AlterField(
            model_name="brand",
            name="primary_category_slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medicines", "medicines"),
                    ("supplements", "supplements"),
                    ("medical-equipment", "medical-equipment"),
                    ("clothing", "clothing"),
                    ("shoes", "shoes"),
                    ("electronics", "electronics"),
                    ("furniture", "furniture"),
                    ("tableware", "tableware"),
                    ("accessories", "accessories"),
                    ("jewelry", "jewelry"),
                    ("underwear", "underwear"),
                    ("headwear", "headwear"),
                    ("books", "books"),
                    ("perfumery", "perfumery"),
                ],
                help_text="Явно укажите ключевой slug для бренда (clothing, shoes, electronics и т.д.).",
                max_length=64,
                verbose_name="Основная категория (slug)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("medicines", "Медицина"),
                    ("supplements", "БАДы"),
                    ("medical_equipment", "Медтехника"),
                    ("clothing", "Одежда"),
                    ("underwear", "Нижнее бельё"),
                    ("headwear", "Головные уборы"),
                    ("shoes", "Обувь"),
                    ("electronics", "Электроника"),
                    ("furniture", "Мебель"),
                    ("tableware", "Посуда"),
                    ("accessories", "Аксессуары"),
                    ("jewelry", "Украшения"),
                    ("books", "Книги"),
                    ("perfumery", "Парфюмерия"),
                ],
                db_index=True,
                default="medicines",
                max_length=32,
                verbose_name="Тип товара",
            ),
        ),
    ]
