# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0091_categoryperfumery_productperfumery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="primary_category_slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medicines", "medicines"),
                    ("supplements", "supplements"),
                    ("medical-equipment", "medical-equipment"),
                    ("clothing", "clothing"),
                    ("shoes", "shoes"),
                    ("electronics", "electronics"),
                    ("furniture", "furniture"),
                    ("tableware", "tableware"),
                    ("accessories", "accessories"),
                    ("jewelry", "jewelry"),
                    ("underwear", "underwear"),
                    ("headwear", "headwear"),
                    ("books", "books"),
                    ("perfumery", "perfumery"),
                    ("uslugi", "uslugi"),
                    ("sports", "sports"),
                    ("auto-parts", "auto-parts"),
                    ("islamic-clothing", "islamic-clothing"),
                    ("incense", "incense"),
                ],
                help_text="Явно укажите ключевой slug для бренда (clothing, shoes, electronics и т.д.).",
                max_length=64,
                verbose_name="Основная категория (slug)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("medicines", "Медицина"),
                    ("supplements", "БАДы"),
                    ("medical_equipment", "Медтехника"),
                    ("clothing", "Одежда"),
                    ("underwear", "Нижнее бельё"),
                    ("headwear", "Головные уборы"),
                    ("shoes", "Обувь"),
                    ("electronics", "Электроника"),
                    ("furniture", "Мебель"),
                    ("tableware", "Посуда"),
                    ("accessories", "Аксессуары"),
                    ("jewelry", "Украшения"),
                    ("books", "Книги"),
                    ("perfumery", "Парфюмерия"),
                    ("uslugi", "Услуги"),
                    ("sports", "Спорттовары"),
                    ("auto_parts", "Автозапчасти"),
                    ("islamic_clothing", "Исламская одежда"),
                    ("incense", "Благовония"),
                ],
                db_index=True,
                default="medicines",
                max_length=32,
                verbose_name="Тип товара",
            ),
        ),
    ]
