# Generated by Django 5.2.11 on 2026-02-14 23:49

import apps.catalog.utils.storage_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0093_add_jewelry_video_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewelryproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_jewelry_main_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_jewelry_main_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_jewelry_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_jewelry_variant_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_jewelry_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
    ]
