# Generated by Django 5.2.11 on 2026-02-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0098_add_product_genre"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productgenre",
            new_name="catalog_pro_product_de59a5_idx",
            old_name="catalog_pro_product_23f2b7_idx",
        ),
        migrations.RenameIndex(
            model_name="productgenre",
            new_name="catalog_pro_sort_or_29965e_idx",
            old_name="catalog_pro_sort_or_1c6f30_idx",
        ),
    ]
