# Generated by Django 5.2.11 on 2026-02-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0099_rename_catalog_pro_product_23f2b7_idx_catalog_pro_product_de59a5_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="furnitureproduct",
            name="furniture_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chairs", "Стулья"),
                    ("tables", "Столы"),
                    ("wardrobes", "Шкафы"),
                    ("sofas", "Диваны"),
                ],
                max_length=100,
                verbose_name="Тип мебели",
            ),
        ),
    ]
