# Generated by Django 5.2.11 on 2026-02-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0100_alter_furnitureproduct_furniture_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingproduct",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
    ]
