# Generated by Django 5.2.11 on 2026-02-18 00:36

import apps.catalog.utils.storage_paths
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0103_backfill_furniture_prices"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("KZT", "KZT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="Главное изображение"
                    ),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Главное изображение (файл)",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="ISBN"),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Издательство"
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата публикации"),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество страниц"
                    ),
                ),
                (
                    "language",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Язык"),
                ),
                (
                    "cover_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Тип обложки"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(default=0, verbose_name="Количество отзывов"),
                ),
                ("is_bestseller", models.BooleanField(default=False, verbose_name="Бестселлер")),
                (
                    "base_product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="book_item",
                        to="catalog.product",
                        verbose_name="Базовый товар (shadow)",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар — Книга",
                "verbose_name_plural": "Товары — Книги",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL изображения"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/books/gallery/",
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.bookproduct",
                        verbose_name="Книга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение книги",
                "verbose_name_plural": "Изображения книг",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.bookproduct",
                        verbose_name="Книга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод книги",
                "verbose_name_plural": "Переводы книг",
                "ordering": ["product", "locale"],
            },
        ),
        migrations.CreateModel(
            name="PerfumeryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("KZT", "KZT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="Главное изображение"
                    ),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Главное изображение (файл)",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "volume",
                    models.CharField(
                        blank=True,
                        help_text="Например: '50ml', '100ml'",
                        max_length=50,
                        verbose_name="Объём",
                    ),
                ),
                (
                    "fragrance_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("edp", "Eau de Parfum"),
                            ("edt", "Eau de Toilette"),
                            ("edc", "Eau de Cologne"),
                            ("parfum", "Parfum"),
                            ("body_mist", "Body Mist"),
                        ],
                        max_length=20,
                        verbose_name="Тип аромата",
                    ),
                ),
                (
                    "fragrance_family",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("floral", "Цветочные"),
                            ("woody", "Древесные"),
                            ("oriental", "Восточные"),
                            ("fresh", "Свежие"),
                            ("citrus", "Цитрусовые"),
                            ("aquatic", "Водные"),
                            ("gourmand", "Гурманские"),
                            ("aromatic", "Ароматические"),
                        ],
                        max_length=20,
                        verbose_name="Семейство аромата",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("men", "Мужской"), ("women", "Женский"), ("unisex", "Унисекс")],
                        max_length=10,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "top_notes",
                    models.CharField(blank=True, max_length=500, verbose_name="Верхние ноты"),
                ),
                (
                    "heart_notes",
                    models.CharField(blank=True, max_length=500, verbose_name="Средние ноты"),
                ),
                (
                    "base_notes",
                    models.CharField(blank=True, max_length=500, verbose_name="Базовые ноты"),
                ),
                (
                    "base_product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perfumery_item",
                        to="catalog.product",
                        verbose_name="Базовый товар (shadow)",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар — Парфюмерия",
                "verbose_name_plural": "Товары — Парфюмерия",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerfumeryProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL изображения"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/perfumery/gallery/",
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.perfumeryproduct",
                        verbose_name="Парфюмерия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение парфюмерии",
                "verbose_name_plural": "Изображения парфюмерии",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerfumeryProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.perfumeryproduct",
                        verbose_name="Парфюмерия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод парфюмерии",
                "verbose_name_plural": "Переводы парфюмерии",
                "ordering": ["product", "locale"],
            },
        ),
        migrations.CreateModel(
            name="PerfumeryVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="Название варианта"),
                ),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=500, verbose_name="Название (англ.)"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Автогенерация, можно переопределить.",
                        max_length=600,
                        unique=True,
                        verbose_name="Slug варианта",
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True,
                        help_text="Например: '30ml', '50ml', '100ml'",
                        max_length=50,
                        verbose_name="Объём",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                ("barcode", models.CharField(blank=True, max_length=100, verbose_name="Штрихкод")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("KZT", "KZT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(blank=True, verbose_name="Главное изображение варианта"),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/perfumery/variants/",
                        verbose_name="Главное изображение варианта (файл)",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.perfumeryproduct",
                        verbose_name="Товар парфюмерии (родитель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант парфюмерии",
                "verbose_name_plural": "Варианты парфюмерии",
                "ordering": ["product", "sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerfumeryVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Ссылка на изображение.", verbose_name="URL изображения"
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/perfumery/variants/gallery/",
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.perfumeryvariant",
                        verbose_name="Вариант парфюмерии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта парфюмерии",
                "verbose_name_plural": "Изображения вариантов парфюмерии",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ProductBooks",
        ),
        migrations.DeleteModel(
            name="ProductPerfumery",
        ),
        migrations.AlterField(
            model_name="bookvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_variants",
                to="catalog.bookproduct",
                verbose_name="Книга (родитель)",
            ),
        ),
        migrations.AlterField(
            model_name="productauthor",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_authors",
                to="catalog.bookproduct",
                verbose_name="Книга",
            ),
        ),
        migrations.AlterField(
            model_name="productgenre",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_genres",
                to="catalog.bookproduct",
                verbose_name="Книга",
            ),
        ),
        migrations.AddIndex(
            model_name="bookproduct",
            index=models.Index(fields=["external_id"], name="catalog_boo_externa_b1d4a3_idx"),
        ),
        migrations.AddIndex(
            model_name="bookproduct",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_boo_is_acti_6d2ae8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookproduct",
            index=models.Index(fields=["category", "brand"], name="catalog_boo_categor_58c072_idx"),
        ),
        migrations.AddIndex(
            model_name="bookproduct",
            index=models.Index(fields=["price"], name="catalog_boo_price_158710_idx"),
        ),
        migrations.AddIndex(
            model_name="bookproduct",
            index=models.Index(fields=["isbn"], name="catalog_boo_isbn_0b80c2_idx"),
        ),
        migrations.AddIndex(
            model_name="bookproduct",
            index=models.Index(fields=["publisher"], name="catalog_boo_publish_20da5d_idx"),
        ),
        migrations.AddIndex(
            model_name="bookproduct",
            index=models.Index(fields=["rating"], name="catalog_boo_rating_3d4911_idx"),
        ),
        migrations.AddIndex(
            model_name="bookproductimage",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_boo_product_78b5fe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookproducttranslation",
            unique_together={("product", "locale")},
        ),
        migrations.AddIndex(
            model_name="perfumeryproduct",
            index=models.Index(fields=["external_id"], name="catalog_per_externa_84af39_idx"),
        ),
        migrations.AddIndex(
            model_name="perfumeryproduct",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_per_is_acti_5b9c18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="perfumeryproduct",
            index=models.Index(fields=["category", "brand"], name="catalog_per_categor_be5d8d_idx"),
        ),
        migrations.AddIndex(
            model_name="perfumeryproduct",
            index=models.Index(fields=["price"], name="catalog_per_price_ab9f36_idx"),
        ),
        migrations.AddIndex(
            model_name="perfumeryproduct",
            index=models.Index(fields=["fragrance_type"], name="catalog_per_fragran_6de094_idx"),
        ),
        migrations.AddIndex(
            model_name="perfumeryproduct",
            index=models.Index(fields=["gender"], name="catalog_per_gender_672b96_idx"),
        ),
        migrations.AddIndex(
            model_name="perfumeryproductimage",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_per_product_5888f2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="perfumeryproducttranslation",
            unique_together={("product", "locale")},
        ),
        migrations.AddIndex(
            model_name="perfumeryvariant",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_per_product_69ea4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="perfumeryvariant",
            index=models.Index(fields=["slug"], name="catalog_per_slug_27bf10_idx"),
        ),
        migrations.AddIndex(
            model_name="perfumeryvariant",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_per_is_acti_e366a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="perfumeryvariantimage",
            index=models.Index(
                fields=["variant", "sort_order"], name="catalog_per_variant_a76d64_idx"
            ),
        ),
    ]
