# Generated by Django 5.2.11 on 2026-02-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0105_wave2_domain_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAccessories',
        ),
        migrations.DeleteModel(
            name='ProductMedicalEquipment',
        ),
        migrations.DeleteModel(
            name='ProductMedicines',
        ),
        migrations.DeleteModel(
            name='ProductSupplements',
        ),
        migrations.DeleteModel(
            name='ProductTableware',
        ),
    ]
