# Generated by Django 5.2.11 on 2026-02-18 01:09

import apps.catalog.utils.storage_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0106_remove_wave2_proxy_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingproduct',
            name='base_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_item', to='catalog.product', verbose_name='Базовый товар (shadow)'),
        ),
        migrations.AddField(
            model_name='electronicsproduct',
            name='base_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronics_item', to='catalog.product', verbose_name='Базовый товар (shadow)'),
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='base_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jewelry_item', to='catalog.product', verbose_name='Базовый товар (shadow)'),
        ),
        migrations.AddField(
            model_name='shoeproduct',
            name='base_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoe_item', to='catalog.product', verbose_name='Базовый товар (shadow)'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('KZT', 'KZT')], default='RUB', max_length=5, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='main_image',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='main_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=apps.catalog.utils.storage_paths.get_product_upload_path, verbose_name='Главное изображение (файл)'),
        ),
        migrations.AlterField(
            model_name='electronicsproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='electronicsproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='electronicsproduct',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('KZT', 'KZT')], default='RUB', max_length=5, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='electronicsproduct',
            name='main_image',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='electronicsproduct',
            name='main_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=apps.catalog.utils.storage_paths.get_product_upload_path, verbose_name='Главное изображение (файл)'),
        ),
        migrations.AlterField(
            model_name='furnitureproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='furnitureproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='furnitureproduct',
            name='main_image',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='furnitureproduct',
            name='main_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=apps.catalog.utils.storage_paths.get_product_upload_path, verbose_name='Главное изображение (файл)'),
        ),
        migrations.AlterField(
            model_name='jewelryproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='jewelryproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='jewelryproduct',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('KZT', 'KZT')], default='RUB', max_length=5, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='jewelryproduct',
            name='main_image',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='shoeproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='shoeproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shoeproduct',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('KZT', 'KZT')], default='RUB', max_length=5, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='shoeproduct',
            name='main_image',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='shoeproduct',
            name='main_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=apps.catalog.utils.storage_paths.get_product_upload_path, verbose_name='Главное изображение (файл)'),
        ),
    ]
