# Generated by Django 5.2.11 on 2026-02-18 01:27

import apps.catalog.utils.storage_paths
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0107_refactor_wave1_domains"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("KZT", "KZT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="Главное изображение"
                    ),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Главное изображение (файл)",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "part_number",
                    models.CharField(blank=True, max_length=100, verbose_name="Артикул"),
                ),
                (
                    "car_brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Марка авто"),
                ),
                (
                    "car_model",
                    models.CharField(blank=True, max_length=100, verbose_name="Модель авто"),
                ),
                (
                    "compatibility_years",
                    models.CharField(blank=True, max_length=50, verbose_name="Годы совместимости"),
                ),
                (
                    "base_product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_part_item",
                        to="catalog.product",
                        verbose_name="Базовый товар (shadow)",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автозапчасть",
                "verbose_name_plural": "Автозапчасти",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutoPartProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        max_length=500,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Файл изображения",
                    ),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.autopartproduct",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение автозапчасти",
                "verbose_name_plural": "Изображения автозапчастей",
                "ordering": ["-is_main", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoPartProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский"), ("tr", "Турецкий")],
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.autopartproduct",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод автозапчасти",
                "verbose_name_plural": "Переводы автозапчастей",
            },
        ),
        migrations.CreateModel(
            name="AutoPartVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "Новая"), ("used", "Б/У"), ("rebuilt", "Восстановленная")],
                        default="new",
                        max_length=50,
                        verbose_name="Состояние",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="Артикул")),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, verbose_name="Производитель"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Цена"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Старая цена",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.autopartproduct",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант автозапчасти",
                "verbose_name_plural": "Варианты автозапчастей",
            },
        ),
        migrations.CreateModel(
            name="AutoPartVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        max_length=500,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Файл изображения",
                    ),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.autopartvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта",
                "verbose_name_plural": "Изображения вариантов",
            },
        ),
        migrations.CreateModel(
            name="SportsProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "RUB"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("TRY", "TRY"),
                            ("KZT", "KZT"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="Главное изображение"
                    ),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Главное изображение (файл)",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Внешний ID"),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "sport_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Вид спорта"),
                ),
                (
                    "equipment_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Тип инвентаря"),
                ),
                ("material", models.CharField(blank=True, max_length=100, verbose_name="Материал")),
                ("size", models.CharField(blank=True, max_length=50, verbose_name="Размер")),
                (
                    "base_product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sports_item",
                        to="catalog.product",
                        verbose_name="Базовый товар (shadow)",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спорттовар",
                "verbose_name_plural": "Спорттовары",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SportsProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        max_length=500,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Файл изображения",
                    ),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.sportsproduct",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение спорттовара",
                "verbose_name_plural": "Изображения спорттоваров",
                "ordering": ["-is_main", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SportsProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский"), ("tr", "Турецкий")],
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.sportsproduct",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод спорттовара",
                "verbose_name_plural": "Переводы спорттоваров",
            },
        ),
        migrations.CreateModel(
            name="SportsVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                ("size", models.CharField(blank=True, max_length=50, verbose_name="Размер")),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="Артикул")),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Цена"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Старая цена",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.sportsproduct",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант спорттовара",
                "verbose_name_plural": "Варианты спорттоваров",
            },
        ),
        migrations.CreateModel(
            name="SportsVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        max_length=500,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Файл изображения",
                    ),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.sportsvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта",
                "verbose_name_plural": "Изображения вариантов",
            },
        ),
        migrations.AddIndex(
            model_name="autopartproduct",
            index=models.Index(fields=["external_id"], name="catalog_aut_externa_fc1c24_idx"),
        ),
        migrations.AddIndex(
            model_name="autopartproduct",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_aut_is_acti_1885ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autopartproduct",
            index=models.Index(fields=["category", "brand"], name="catalog_aut_categor_13a423_idx"),
        ),
        migrations.AddIndex(
            model_name="autopartproduct",
            index=models.Index(fields=["price"], name="catalog_aut_price_f8dfae_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="autopartproducttranslation",
            unique_together={("product", "locale")},
        ),
        migrations.AddIndex(
            model_name="sportsproduct",
            index=models.Index(fields=["external_id"], name="catalog_spo_externa_c91e31_idx"),
        ),
        migrations.AddIndex(
            model_name="sportsproduct",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_spo_is_acti_adaca2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sportsproduct",
            index=models.Index(fields=["category", "brand"], name="catalog_spo_categor_41f00c_idx"),
        ),
        migrations.AddIndex(
            model_name="sportsproduct",
            index=models.Index(fields=["price"], name="catalog_spo_price_3ab11e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="sportsproducttranslation",
            unique_together={("product", "locale")},
        ),
    ]
