# Generated by Django 5.2.11 on 2026-02-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0108_autopartproduct_autopartproductimage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sportsproduct",
            name="size",
        ),
    ]
