# Generated by Django 5.2.11 on 2026-02-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0109_remove_sportsproduct_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cover_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_bestseller",
        ),
        migrations.RemoveField(
            model_name="product",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="product",
            name="language",
        ),
        migrations.RemoveField(
            model_name="product",
            name="pages",
        ),
        migrations.RemoveField(
            model_name="product",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="product",
            name="reviews_count",
        ),
    ]
