# Generated by Django 5.2.11 on 2026-02-18 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0110_remove_product_cover_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FurnitureProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                        max_length=2000,
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/furniture/gallery/",
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.furnitureproduct",
                        verbose_name="Товар мебели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара мебели",
                "verbose_name_plural": "Изображения товаров мебели",
                "ordering": ["sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "sort_order"], name="catalog_fur_product_97b04d_idx"
                    )
                ],
            },
        ),
    ]
