# Generated by Django 5.2.11 on 2026-02-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0111_furnitureproductimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductFurniture",
        ),
        migrations.DeleteModel(
            name="ProductHeadwear",
        ),
        migrations.DeleteModel(
            name="ProductJewelry",
        ),
        migrations.DeleteModel(
            name="ProductUnderwear",
        ),
        migrations.AddField(
            model_name="autopartproducttranslation",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="sportsproducttranslation",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Название"),
        ),
    ]
