# Generated by Django 5.2.11 on 2026-02-18 04:03

import apps.catalog.utils.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0112_delete_productfurniture_delete_productheadwear_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autopartproductimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="Альтернативный текст"),
        ),
        migrations.AddField(
            model_name="autopartproductimage",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, verbose_name="URL изображения"),
        ),
        migrations.AddField(
            model_name="autopartproductimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
        ),
        migrations.AddField(
            model_name="sportsproductimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="Альтернативный текст"),
        ),
        migrations.AddField(
            model_name="sportsproductimage",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, verbose_name="URL изображения"),
        ),
        migrations.AddField(
            model_name="sportsproductimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
        ),
        migrations.AlterField(
            model_name="autopartproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Файл изображения",
            ),
        ),
        migrations.AlterField(
            model_name="sportsproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Файл изображения",
            ),
        ),
    ]
