# Generated by Django 5.2.11 on 2026-02-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0113_autopartproductimage_alt_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessoryproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO description для карточки товара.",
                max_length=500,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для индексации (англ.).",
                max_length=500,
                verbose_name="Meta Keywords",
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                max_length=255,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="og_description",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph description (англ.) для социальных сетей.",
                max_length=500,
                verbose_name="OG Description",
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="OpenGraph title (англ.), если отличается от meta title.",
                max_length=255,
                verbose_name="OG Title",
            ),
        ),
    ]
