# Generated by Django 5.2.11 on 2026-03-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0116_create_perfumery_product_from_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to="products/books/gallery/",
                verbose_name="Изображение (файл)",
            ),
        ),
    ]
