# Generated by Django 5.2.11 on 2026-03-05 05:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0118_productprice_usdt_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalCurrencySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "default_margin_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        help_text="Используется если для конкретной пары валют не задана своя маржа (по умолчанию 15%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Маржа по умолчанию (%)",
                    ),
                ),
                (
                    "usdt_markup_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3.00"),
                        help_text="На сколько процентов USDT дороже базового USD (по умолчанию 3%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Наценка USDT (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "глобальная настройка валют",
                "verbose_name_plural": "🌐 Настройки: Валюты и Маржа",
            },
        ),
    ]
