# Generated by Django 5.2.12 on 2026-03-09 09:52

import apps.catalog.utils.storage_paths
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0119_globalcurrencysettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="gif_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите GIF для услуги.",
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_service_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["gif"])
                ],
                verbose_name="GIF (файл)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите основное изображение для услуги.",
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_service_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите основное видео для услуги.",
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_service_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="Ссылка на основное видео.", verbose_name="URL видео"
            ),
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_service_image_upload_path,
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Внешняя ссылка (если есть)",
                        verbose_name="URL изображения",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=255, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение услуги",
                "verbose_name_plural": "Изображения услуг",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServicePrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Турецкая лира"),
                            ("RUB", "Российский рубль"),
                            ("KZT", "Казахстанский тенге"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("USDT", "Tether (USDT)"),
                        ],
                        default="TRY",
                        max_length=4,
                        verbose_name="Базовая валюта",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Цена в исходной валюте",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "rub_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в рублях",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в RUB",
                    ),
                ),
                (
                    "rub_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в RUB с маржой",
                    ),
                ),
                (
                    "usd_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в долларах",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в USD",
                    ),
                ),
                (
                    "usd_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в USD с маржой",
                    ),
                ),
                (
                    "kzt_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в тенге",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в KZT",
                    ),
                ),
                (
                    "kzt_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в KZT с маржой",
                    ),
                ),
                (
                    "eur_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в евро",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в EUR",
                    ),
                ),
                (
                    "eur_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в EUR с маржой",
                    ),
                ),
                (
                    "try_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в турецких лирах",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в TRY",
                    ),
                ),
                (
                    "try_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в TRY с маржой",
                    ),
                ),
                (
                    "usdt_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Конвертированная цена в USDT",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в USDT",
                    ),
                ),
                (
                    "usdt_price_with_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена в USDT с маржой",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_info",
                        to="catalog.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "💰 Цены услуги",
                "verbose_name_plural": "💰 Валюты — Цены услуг",
            },
        ),
    ]
