# Generated by Django 5.2.12 on 2026-03-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0120_service_gif_file_service_main_image_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("area_sqm", "Площадь (м²)"),
                            ("duration_days", "Срок выполнения"),
                            ("work_type", "Вид работ"),
                            ("work_region", "Регион / район"),
                            ("weight_kg", "Вес груза (кг)"),
                            ("volume_m3", "Объём груза (м³)"),
                            ("cargo_type", "Тип груза"),
                            ("distance_km", "Расстояние (км)"),
                            ("duration_hours", "Длительность (часов)"),
                            ("format", "Формат (онлайн/очно)"),
                            ("language", "Язык консультации"),
                            ("specialist", "Специалист"),
                            ("rooms_count", "Количество комнат"),
                            ("frequency", "Периодичность"),
                            ("guarantee", "Гарантия"),
                            ("includes", "Что входит"),
                            ("excludes", "Что не входит"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Ключ атрибута",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Например: '50 м²', '3-5 дней', 'онлайн/очно'",
                        max_length=500,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_attributes",
                        to="catalog.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут услуги",
                "verbose_name_plural": "Атрибуты услуг",
                "ordering": ["sort_order", "key"],
                "indexes": [
                    models.Index(
                        fields=["service", "sort_order"], name="catalog_ser_service_c818e8_idx"
                    )
                ],
                "unique_together": {("service", "key")},
            },
        ),
    ]
