# Generated by Django 5.2.12 on 2026-03-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0121_add_service_attribute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="service",
            name="service_type",
        ),
    ]
