# Generated by Django 5.2.12 on 2026-03-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0122_remove_service_duration_remove_service_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetranslation",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Переведенное название услуги",
                max_length=500,
                verbose_name="Название услуги",
            ),
        ),
    ]
