# Generated by Django 5.2.12 on 2026-03-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0123_servicetranslation_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serviceattribute",
            options={
                "ordering": ["sort_order", "attribute_key"],
                "verbose_name": "Атрибут услуги",
                "verbose_name_plural": "Атрибуты услуг",
            },
        ),
        migrations.AlterField(
            model_name="serviceattribute",
            name="key",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Ключ атрибута (устарело)"
            ),
        ),
        migrations.CreateModel(
            name="ServiceAttributeKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор (например, 'ceiling_height').",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Категории услуг, для которых доступен этот атрибут.",
                        limit_choices_to={"children__isnull": True},
                        related_name="service_attribute_keys",
                        to="catalog.category",
                        verbose_name="Категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип атрибута услуги",
                "verbose_name_plural": "Типы атрибутов услуг",
                "ordering": ["sort_order", "slug"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="serviceattribute",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="serviceattribute",
            name="attribute_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_attributes",
                to="catalog.serviceattributekey",
                verbose_name="Тип атрибута",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceattribute",
            unique_together={("service", "attribute_key")},
        ),
        migrations.CreateModel(
            name="ServiceAttributeKeyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("locale", models.CharField(db_index=True, max_length=10, verbose_name="Язык")),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "key_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.serviceattributekey",
                        verbose_name="Тип атрибута",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод типа атрибута",
                "verbose_name_plural": "Переводы типов атрибутов",
                "unique_together": {("key_obj", "locale")},
            },
        ),
    ]
