# Generated by Django 5.2.12 on 2026-03-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0125_migrate_service_attributes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceattribute",
            name="key",
        ),
        migrations.AlterField(
            model_name="serviceattribute",
            name="attribute_key",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_attributes",
                to="catalog.serviceattributekey",
                verbose_name="Тип атрибута",
            ),
        ),
    ]
