# Generated by Django 5.2.12 on 2026-03-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0126_remove_serviceattribute_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceattributekeytranslation",
            name="locale",
            field=models.CharField(
                choices=[("ru", "Русский"), ("en", "Английский"), ("tr", "Турецкий")],
                db_index=True,
                default="ru",
                max_length=10,
                verbose_name="Язык",
            ),
        ),
    ]
