# Generated by Django 5.2.12 on 2026-03-09 14:39 (исправлено вручную)

import django.db.models.deletion
from django.db import migrations, models


def copy_serviceattributekey_to_global(apps, schema_editor):
    """Копируем данные из ServiceAttributeKey в GlobalAttributeKey."""
    ServiceAttributeKey = apps.get_model('catalog', 'ServiceAttributeKey')
    GlobalAttributeKey = apps.get_model('catalog', 'GlobalAttributeKey')
    GlobalAttributeKeyTranslation = apps.get_model('catalog', 'GlobalAttributeKeyTranslation')

    for old_key in ServiceAttributeKey.objects.all():
        new_key, _ = GlobalAttributeKey.objects.get_or_create(
            id=old_key.id,
            defaults={
                'slug': old_key.slug,
                'sort_order': old_key.sort_order,
            }
        )
        if not _:
            new_key.slug = old_key.slug
            new_key.sort_order = old_key.sort_order
            new_key.save()
        # Категории — ManyToMany
        new_key.categories.set(old_key.categories.all())

        # Обновляем FK в трансляциях
        GlobalAttributeKeyTranslation.objects.filter(key_obj_id=old_key.id).update(key_obj_id=new_key.id)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0127_alter_serviceattributekeytranslation_locale"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        # 1. Меняем опции ProductAttribute
        migrations.AlterModelOptions(
            name="productattribute",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Атрибут товара (статичный)",
                "verbose_name_plural": "📦 Атрибуты товаров (статика)",
            },
        ),
        # 2. Переименовываем транслейшн-модель (данные сохраняются)
        migrations.RenameModel(
            old_name="ServiceAttributeKeyTranslation",
            new_name="GlobalAttributeKeyTranslation",
        ),
        # 3. Создаём новую модель GlobalAttributeKey (пока без FK-переноса)
        migrations.CreateModel(
            name="GlobalAttributeKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор (например, 'ceiling_height').",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Категории товаров или услуг, для которых доступен этот атрибут.",
                        related_name="global_attribute_keys",
                        to="catalog.category",
                        verbose_name="Категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип динамического атрибута",
                "verbose_name_plural": "🛠️ Типы динамических атрибутов",
                "ordering": ["sort_order", "slug"],
            },
        ),
        # 4. Копируем данные из ServiceAttributeKey в GlobalAttributeKey
        migrations.RunPython(
            copy_serviceattributekey_to_global,
            migrations.RunPython.noop,
        ),
        # 5. Теперь безопасно меняем FK в трансляциях
        migrations.AlterField(
            model_name="globalattributekeytranslation",
            name="key_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="catalog.globalattributekey",
                verbose_name="Тип атрибута",
            ),
        ),
        # 6. Меняем FK в ServiceAttribute
        migrations.AlterField(
            model_name="serviceattribute",
            name="attribute_key",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_values",
                to="catalog.globalattributekey",
                verbose_name="Тип атрибута",
            ),
        ),
        # 7. Удаляем старую модель ServiceAttributeKey
        migrations.DeleteModel(
            name="ServiceAttributeKey",
        ),
        # 8. Создаём ProductAttributeValue
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("value", models.CharField(max_length=500, verbose_name="Значение")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "attribute_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_values",
                        to="catalog.globalattributekey",
                        verbose_name="Тип атрибута",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "🛠️ Динамический атрибут товара",
                "verbose_name_plural": "🛠️ Динамические атрибуты товаров",
                "ordering": ["sort_order", "attribute_key"],
            },
        ),
        # 9. Добавляем индекс
        migrations.AddIndex(
            model_name="productattributevalue",
            index=models.Index(
                fields=["content_type", "object_id"], name="catalog_pro_content_841dfa_idx"
            ),
        ),
    ]
