# Generated by Django 5.0.2 on 2026-03-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0128_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
