# Generated by Django 5.0.2 on 2026-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0129_delete_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineproduct',
            name='origin_country',
            field=models.CharField(blank=True, max_length=200, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='medicineproduct',
            name='volume',
            field=models.CharField(blank=True, help_text='Например: 50 мл, 20 таб.', max_length=100, verbose_name='Объем/Количество'),
        ),
        migrations.AddField(
            model_name='medicineproducttranslation',
            name='contraindications',
            field=models.TextField(blank=True, verbose_name='Противопоказания'),
        ),
        migrations.AddField(
            model_name='medicineproducttranslation',
            name='side_effects',
            field=models.TextField(blank=True, verbose_name='Побочные действия'),
        ),
        migrations.AddField(
            model_name='medicineproducttranslation',
            name='storage_conditions',
            field=models.TextField(blank=True, verbose_name='Условия хранения'),
        ),
        migrations.AddField(
            model_name='medicineproducttranslation',
            name='usage_instructions',
            field=models.TextField(blank=True, verbose_name='Способ применения'),
        ),
    ]
