# Generated by Django 5.2.12 on 2026-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0130_medicineproduct_origin_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="SEO описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seo_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SEO заголовок"
            ),
        ),
    ]
