# Generated by Django 5.2.12 on 2026-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0131_alter_product_seo_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="active_ingredient",
            field=models.CharField(blank=True, max_length=300, verbose_name="Действующее вещество"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="dosage_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tablet", "Таблетки"),
                    ("capsule", "Капсулы"),
                    ("syrup", "Сироп"),
                    ("drops", "Капли"),
                    ("ointment", "Мазь"),
                    ("cream", "Крем"),
                    ("gel", "Гель"),
                    ("injection", "Инъекция"),
                    ("powder", "Порошок"),
                    ("spray", "Спрей"),
                    ("suppository", "Суппозитории"),
                    ("other", "Прочее"),
                ],
                max_length=20,
                verbose_name="Лекарственная форма",
            ),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="origin_country",
            field=models.CharField(blank=True, max_length=200, verbose_name="Страна производства"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="volume",
            field=models.CharField(blank=True, max_length=100, verbose_name="Объем/Количество"),
        ),
    ]
