# Generated by Django 5.2.12 on 2026-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0132_medicineproducttranslation_active_ingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicineproducttranslation",
            name="locale",
            field=models.CharField(
                choices=[("ru", "Русский"), ("en", "Английский")],
                max_length=10,
                verbose_name="Локаль",
            ),
        ),
        migrations.AlterField(
            model_name="supplementproducttranslation",
            name="locale",
            field=models.CharField(
                choices=[("ru", "Русский"), ("en", "Английский")],
                max_length=10,
                verbose_name="Локаль",
            ),
        ),
    ]
