# Generated by Django 5.2.12 on 2026-03-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0133_alter_medicineproducttranslation_locale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplementproducttranslation",
            name="active_ingredient",
            field=models.CharField(blank=True, max_length=500, verbose_name="Активный ингредиент"),
        ),
        migrations.AddField(
            model_name="supplementproducttranslation",
            name="dosage_form",
            field=models.CharField(blank=True, max_length=100, verbose_name="Форма выпуска"),
        ),
        migrations.AddField(
            model_name="supplementproducttranslation",
            name="serving_size",
            field=models.CharField(blank=True, max_length=200, verbose_name="Размер порции"),
        ),
    ]
