# Generated by Django 5.2.12 on 2026-03-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0134_supplementproducttranslation_active_ingredient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothingproduct",
            name="material",
        ),
        migrations.RemoveField(
            model_name="clothingproduct",
            name="season",
        ),
        migrations.RemoveField(
            model_name="shoeproduct",
            name="heel_height",
        ),
        migrations.RemoveField(
            model_name="shoeproduct",
            name="material",
        ),
        migrations.RemoveField(
            model_name="shoeproduct",
            name="sole_type",
        ),
    ]
