# Generated by Django 5.2.12 on 2026-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0135_remove_material_season_from_clothing_shoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattributevalue",
            name="value_en",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Значение (EN)"
            ),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="value_ru",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Значение (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="value",
            field=models.CharField(max_length=500, verbose_name="Значение (по умолчанию)"),
        ),
    ]
