# Generated by Django 5.2.12 on 2026-03-13 08:47

from django.db import migrations, models


def add_gender_columns_if_not_exists(apps, schema_editor):
    """Добавляет колонку gender в таблицы, если её ещё нет (идемпотентность)."""
    from django.db import connection
    tables = [
        "catalog_accessoryproduct",
        "catalog_autopartproduct",
        "catalog_bookproduct",
        "catalog_clothingproduct",
        "catalog_electronicsproduct",
        "catalog_furnitureproduct",
        "catalog_incenseproduct",
        "catalog_medicalequipmentproduct",
        "catalog_medicineproduct",
        "catalog_product",
        "catalog_shoeproduct",
        "catalog_sportsproduct",
        "catalog_supplementproduct",
        "catalog_tablewareproduct",
    ]
    with connection.cursor() as cursor:
        for table in tables:
            cursor.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = %s AND column_name = 'gender'
                """,
                [table],
            )
            if cursor.fetchone():
                continue
            cursor.execute(
                f'ALTER TABLE "{table}" ADD COLUMN gender VARCHAR(10) NULL'
            )
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "{table}_gender_idx" ON "{table}" (gender)'
            )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0136_productattributevalue_value_en_and_more"),
    ]

    operations = [
        migrations.RunPython(add_gender_columns_if_not_exists, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="perfumeryproduct",
            name="catalog_per_gender_672b96_idx",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="accessoryproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="autopartproduct",
                    name="gender",
                    field=models.CharField(
                blank=True,
                choices=[
                    ("men", "Мужская"),
                    ("women", "Женская"),
                    ("unisex", "Унисекс"),
                    ("kids", "Детская"),
                ],
                db_index=True,
                help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                            model_name="bookproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="clothingproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="electronicsproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="furnitureproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="incenseproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="medicalequipmentproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="medicineproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="product",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Синхронизируется из доменного товара или берётся из категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="shoeproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="sportsproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="supplementproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AddField(
                    model_name="tablewareproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AlterField(
                    model_name="jewelryproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                migrations.AlterField(
                    model_name="perfumeryproduct",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
