# Generated by Django 5.2.12 on 2026-03-13 09:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0137_add_gender_to_abstract_domain_and_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="category_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=64),
                blank=True,
                default=list,
                help_text="Список slug категорий, в которых представлен бренд (clothing, shoes, sports и т.д.). Puma — clothing, shoes, sports.",
                size=None,
                verbose_name="Категории бренда",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="primary_category_slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medicines", "medicines"),
                    ("supplements", "supplements"),
                    ("medical-equipment", "medical-equipment"),
                    ("clothing", "clothing"),
                    ("shoes", "shoes"),
                    ("electronics", "electronics"),
                    ("furniture", "furniture"),
                    ("tableware", "tableware"),
                    ("accessories", "accessories"),
                    ("jewelry", "jewelry"),
                    ("underwear", "underwear"),
                    ("headwear", "headwear"),
                    ("books", "books"),
                    ("perfumery", "perfumery"),
                    ("uslugi", "uslugi"),
                    ("sports", "sports"),
                    ("auto-parts", "auto-parts"),
                    ("islamic-clothing", "islamic-clothing"),
                    ("incense", "incense"),
                ],
                help_text="Основная категория для отображения (например, при переходе на страницу бренда).",
                max_length=64,
                verbose_name="Основная категория (slug)",
            ),
        ),
    ]
