# Generated by Django 5.0.2 on 2026-03-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0138_add_brand_category_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shoe_type',
        ),
    ]
