# Generated by Django 5.2.12 on 2026-03-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0141_increase_url_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessoryproduct",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="accessoryproduct",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="accessoryproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="autopartproduct",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="autopartproduct",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="autopartproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="bookproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="bookvariant",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="bookvariant",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="category",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="clothingproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="clothingvariant",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="clothingvariant",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="electronicsproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="furnitureproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="furniturevariant",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="furniturevariant",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="incenseproduct",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="incenseproduct",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="incenseproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryvariant",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="jewelryvariant",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="medicalequipmentproduct",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="medicalequipmentproduct",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="medicalequipmentproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="dosage_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tablet", "Таблетки"),
                    ("capsule", "Капсулы"),
                    ("syrup", "Сироп"),
                    ("drops", "Капли"),
                    ("ointment", "Мазь"),
                    ("cream", "Крем"),
                    ("gel", "Гель"),
                    ("injection", "Инъекция"),
                    ("powder", "Порошок"),
                    ("spray", "Спрей"),
                    ("suppository", "Суппозитории"),
                    ("other", "Прочее"),
                ],
                max_length=20,
                verbose_name="Лекарственная форма",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryvariant",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="perfumeryvariant",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="product",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="shoeproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="shoevariant",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="shoevariant",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="sportsproduct",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="sportsproduct",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="sportsproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="supplementproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="tablewareproduct",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
        ),
        migrations.AlterField(
            model_name="tablewareproduct",
            name="external_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="tablewareproduct",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
    ]
