# Generated by Django 5.2.12 on 2026-03-25 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0143_cleanup_product_fields_lengths"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineproduct",
            name="administration_route",
            field=models.CharField(
                blank=True,
                help_text="Например: Интравенозный, Интрамышечный, Перорально, Топикально.",
                max_length=100,
                verbose_name="Путь введения",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="atc_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Международная классификация (напр.: B02BD08). Объединяет аналоги.",
                max_length=20,
                verbose_name="Код АТХ",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Ключ для поиска медиа и мёрджа данных из разных источников.",
                max_length=50,
                verbose_name="Штрих-код (EAN/GTIN)",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="prescription_type",
            field=models.CharField(
                blank=True,
                help_text="Например: Turuncu Reçete, Beyaz Reçete, Mor Reçete.",
                max_length=100,
                verbose_name="Тип рецепта",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="sgk_status",
            field=models.CharField(
                blank=True,
                help_text="Например: Bedeli Ödenir / Bedeli Ödenmez.",
                max_length=100,
                verbose_name="Статус оплаты СГК",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="shelf_life",
            field=models.CharField(
                blank=True,
                help_text="Например: 24 месяца.",
                max_length=50,
                verbose_name="Срок годности",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="special_notes",
            field=models.TextField(
                blank=True,
                help_text="Дополнительные предупреждения (ОЗЕЛ БИЛГИЛЕР).",
                verbose_name="Особые сведения",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="storage_conditions",
            field=models.CharField(
                blank=True,
                help_text="Краткое описание условий хранения (температура, свет и т.д.).",
                max_length=500,
                verbose_name="Условия хранения",
            ),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="indications",
            field=models.TextField(blank=True, verbose_name="Показания к применению"),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="dosage_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tablet", "Таблетки"),
                    ("capsule", "Капсулы"),
                    ("syrup", "Сироп"),
                    ("drops", "Капли"),
                    ("ointment", "Мазь"),
                    ("cream", "Крем"),
                    ("gel", "Гель"),
                    ("injection", "Инъекция"),
                    ("powder", "Порошок"),
                    ("spray", "Спрей"),
                    ("suppository", "Суппозитории"),
                    ("other", "Прочее"),
                ],
                max_length=20,
                verbose_name="Лекарственная форма",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproducttranslation",
            name="dosage_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tablet", "Таблетки"),
                    ("capsule", "Капсулы"),
                    ("syrup", "Сироп"),
                    ("drops", "Капли"),
                    ("ointment", "Мазь"),
                    ("cream", "Крем"),
                    ("gel", "Гель"),
                    ("injection", "Инъекция"),
                    ("powder", "Порошок"),
                    ("spray", "Спрей"),
                    ("suppository", "Суппозитории"),
                    ("other", "Прочее"),
                ],
                max_length=20,
                verbose_name="Лекарственная форма",
            ),
        ),
        # og_image_url у product уже расширен до 2000 в migration 0143 — пропускаем
        migrations.AlterField(
            model_name="supplementproduct",
            name="dosage_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tablet", "Таблетки"),
                    ("capsule", "Капсулы"),
                    ("syrup", "Сироп"),
                    ("drops", "Капли"),
                    ("ointment", "Мазь"),
                    ("cream", "Крем"),
                    ("gel", "Гель"),
                    ("injection", "Инъекция"),
                    ("powder", "Порошок"),
                    ("spray", "Спрей"),
                    ("suppository", "Суппозитории"),
                    ("other", "Прочее"),
                ],
                max_length=20,
                verbose_name="Форма выпуска",
            ),
        ),
        migrations.AlterField(
            model_name="supplementproducttranslation",
            name="dosage_form",
            field=models.CharField(blank=True, max_length=100, verbose_name="Форма выпуска"),
        ),
        migrations.CreateModel(
            name="MedicineAnalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, verbose_name="Штрих-код"
                    ),
                ),
                ("atc_code", models.CharField(blank=True, max_length=20, verbose_name="Код АТХ")),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=200, verbose_name="Внешний ID"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="ilacfiyati, ilacabak, и т.д.",
                        max_length=100,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analogs",
                        to="catalog.medicineproduct",
                        verbose_name="Препарат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аналог препарата",
                "verbose_name_plural": "Аналоги препарата",
                "ordering": ["name"],
                "unique_together": {("product", "barcode", "source")},
            },
        ),
    ]
