# Generated by Django 5.2.12 on 2026-03-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0145_alter_product_og_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                max_length=2000,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                verbose_name="OG Image URL",
            ),
        ),
    ]
