# Generated by Django 5.2.12 on 2026-03-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0146_alter_product_og_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessoryproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="autopartproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="bookproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="clothingproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="furnitureproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="incenseproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="medicalequipmentproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="shoeproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="sportsproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="supplementproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="tablewareproduct",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
    ]
