# Generated by Django 5.2.12 on 2026-03-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0147_alter_accessoryproduct_og_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineproduct",
            name="nfc_code",
            field=models.CharField(blank=True, max_length=50, verbose_name="NFC Код"),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="sgk_active_ingredient_code",
            field=models.CharField(blank=True, max_length=50, verbose_name="SGK Etkin Madde Kodu"),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="sgk_equivalent_code",
            field=models.CharField(blank=True, max_length=50, verbose_name="SGK Eşdeğer Kodu"),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="sgk_public_no",
            field=models.CharField(blank=True, max_length=50, verbose_name="SGK Kamu No"),
        ),
    ]
