# Generated by Django 5.2.12 on 2026-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0148_medicineproduct_nfc_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="administration_route",
            field=models.CharField(blank=True, max_length=100, verbose_name="Путь введения"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="prescription_type",
            field=models.CharField(blank=True, max_length=100, verbose_name="Вид рецепта"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="sgk_status",
            field=models.CharField(blank=True, max_length=100, verbose_name="Статус SGK"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="shelf_life",
            field=models.CharField(blank=True, max_length=50, verbose_name="Срок годности"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="special_notes",
            field=models.TextField(blank=True, verbose_name="Особые отметки (SUT / Medula)"),
        ),
    ]
