# Generated by Django 5.2.12 on 2026-03-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0149_medicineproducttranslation_administration_route_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicineproduct",
            name="administration_route",
            field=models.CharField(
                blank=True,
                help_text="Например: Интравенозный, Интрамышечный, Перорально, Топикально.",
                max_length=500,
                verbose_name="Путь введения",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="atc_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Международная классификация (напр.: B02BD08). Объединяет аналоги.",
                max_length=100,
                verbose_name="Код АТХ",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Ключ для поиска медиа и мёрджа данных из разных источников.",
                max_length=100,
                verbose_name="Штрих-код (EAN/GTIN)",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="nfc_code",
            field=models.CharField(blank=True, max_length=100, verbose_name="NFC Код"),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="origin_country",
            field=models.CharField(blank=True, max_length=500, verbose_name="Страна производства"),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="prescription_type",
            field=models.CharField(
                blank=True,
                help_text="Например: Turuncu Reçete, Beyaz Reçete, Mor Reçete.",
                max_length=500,
                verbose_name="Тип рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="sgk_active_ingredient_code",
            field=models.CharField(blank=True, max_length=100, verbose_name="SGK Etkin Madde Kodu"),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="sgk_equivalent_code",
            field=models.CharField(blank=True, max_length=100, verbose_name="SGK Eşdeğer Kodu"),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="sgk_public_no",
            field=models.CharField(blank=True, max_length=100, verbose_name="SGK Kamu No"),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="sgk_status",
            field=models.CharField(
                blank=True,
                help_text="Например: Bedeli Ödenir / Bedeli Ödenmez.",
                max_length=500,
                verbose_name="Статус оплаты СГК",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="shelf_life",
            field=models.CharField(
                blank=True,
                help_text="Например: 24 месяца.",
                max_length=200,
                verbose_name="Срок годности",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproducttranslation",
            name="administration_route",
            field=models.CharField(blank=True, max_length=500, verbose_name="Путь введения"),
        ),
        migrations.AlterField(
            model_name="medicineproducttranslation",
            name="origin_country",
            field=models.CharField(blank=True, max_length=500, verbose_name="Страна производства"),
        ),
        migrations.AlterField(
            model_name="medicineproducttranslation",
            name="prescription_type",
            field=models.CharField(blank=True, max_length=500, verbose_name="Вид рецепта"),
        ),
        migrations.AlterField(
            model_name="medicineproducttranslation",
            name="sgk_status",
            field=models.CharField(blank=True, max_length=500, verbose_name="Статус SGK"),
        ),
        migrations.AlterField(
            model_name="medicineproducttranslation",
            name="shelf_life",
            field=models.CharField(blank=True, max_length=200, verbose_name="Срок годности"),
        ),
    ]
