# Generated by Django 5.2.12 on 2026-03-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0150_alter_medicineproduct_administration_route_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.URLField(
                blank=True,
                max_length=2000,
                verbose_name="Главное изображение",
                help_text="URL основного изображения (ссылка на CDN или внутреннее хранилище).",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="video_url",
            field=models.URLField(
                blank=True,
                max_length=2000,
                verbose_name="URL видео",
                help_text="URL видео для товара (например, из Instagram постов).",
            ),
        ),
    ]
