# Generated by Django 5.2.12 on 2026-03-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0151_increase_product_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                max_length=2000,
                verbose_name="OG Image URL",
            ),
        ),
    ]
