# Generated by Django 5.2.10 on 2026-03-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0152_alter_product_og_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Хэш изображения'),
        ),
    ]
