# Generated by Django 5.2.12 on 2026-03-29 17:16

import apps.catalog.utils.storage_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0154_medicineproductimage_image_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessoryproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="accessoryproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="autopartproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="bookproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="clothingproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="electronicsproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="furnitureproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="incenseproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="jewelryproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="medicalequipmentproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="medicineproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="perfumeryproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="shoeproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="sportsproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="gtin",
            field=models.CharField(blank=True, max_length=64, verbose_name="GTIN"),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="mpn",
            field=models.CharField(blank=True, max_length=64, verbose_name="MPN"),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="URL видео для товара (например, из Instagram постов или IKEA).",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="weight_unit",
            field=models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="weight_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
            ),
        ),
        migrations.AddField(
            model_name="tablewareproduct",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
            ),
        ),
    ]
