# Generated by Django 5.2.12 on 2026-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0155_accessoryproduct_dimensions_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="furnitureproduct",
            name="dimensions",
            field=models.CharField(
                blank=True,
                help_text="Например: 200x100x80 см",
                max_length=500,
                verbose_name="Размеры",
            ),
        ),
        migrations.AlterField(
            model_name="furnitureproduct",
            name="furniture_type",
            field=models.CharField(blank=True, max_length=255, verbose_name="Тип мебели"),
        ),
        migrations.AlterField(
            model_name="furnitureproduct",
            name="material",
            field=models.CharField(blank=True, max_length=1000, verbose_name="Материал"),
        ),
    ]
