# Generated by Django 5.2.12 on 2026-03-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0157_medicineproduct_media_enrichment_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplementproduct",
            name="media_enrichment_error",
            field=models.TextField(blank=True, null=True, verbose_name="Ошибка обогащения"),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="media_enrichment_last_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата последнего обогащения"
            ),
        ),
        migrations.AddField(
            model_name="supplementproduct",
            name="media_enrichment_status",
            field=models.CharField(
                choices=[
                    ("pending", "В очереди"),
                    ("processing", "Обработка"),
                    ("completed", "Завершено"),
                    ("failed", "Ошибка"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус медиа",
            ),
        ),
    ]
