# Generated by Django 5.2.12 on 2026-03-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0158_supplementproduct_media_enrichment_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplementproductimage",
            name="image_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, verbose_name="Хэш изображения"
            ),
        ),
    ]
