# Generated by Django 5.2.12 on 2026-04-01 02:46

import apps.catalog.utils.storage_paths
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0159_supplementproductimage_image_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeadwearProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Турецкая лира"),
                            ("RUB", "Российский рубль"),
                            ("KZT", "Казахстанский тенге"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("USDT", "Tether (USDT)"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="Главное изображение"
                    ),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Главное изображение (файл)",
                    ),
                ),
                ("gtin", models.CharField(blank=True, max_length=64, verbose_name="GTIN")),
                ("mpn", models.CharField(blank=True, max_length=64, verbose_name="MPN")),
                (
                    "weight_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
                    ),
                ),
                (
                    "dimensions_unit",
                    models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                        max_length=255,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Англоязычный SEO description для карточки товара.",
                        max_length=500,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова для индексации (англ.).",
                        max_length=500,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="OpenGraph title (англ.), если отличается от meta title.",
                        max_length=255,
                        verbose_name="OG Title",
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        help_text="OpenGraph description (англ.) для социальных сетей.",
                        max_length=500,
                        verbose_name="OG Description",
                    ),
                ),
                (
                    "og_image_url",
                    models.CharField(
                        blank=True,
                        help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                        max_length=2000,
                        verbose_name="OG Image URL",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("size", models.CharField(blank=True, max_length=20, verbose_name="Размер")),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                (
                    "video_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL видео"),
                ),
                (
                    "main_video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="products/headwear/main/",
                        verbose_name="Главное видео (файл)",
                    ),
                ),
                (
                    "base_product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headwear_item",
                        to="catalog.product",
                        verbose_name="Базовый товар (shadow)",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Головной убор",
                "verbose_name_plural": "Головные уборы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeadwearProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL изображения"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/headwear/gallery/",
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.headwearproduct",
                        verbose_name="Головной убор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение Головной убор",
                "verbose_name_plural": "Изображения Головные уборы",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeadwearProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50, verbose_name="Размер")),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Остаток"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="catalog.headwearproduct",
                        verbose_name="Головной убор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер товара: Головной убор",
                "verbose_name_plural": "Размеры: Головные уборы",
                "ordering": ["product", "sort_order", "size"],
            },
        ),
        migrations.CreateModel(
            name="HeadwearProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.headwearproduct",
                        verbose_name="Головной убор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод: Головной убор",
                "verbose_name_plural": "Переводы: Головные уборы",
                "ordering": ["product", "locale"],
            },
        ),
        migrations.CreateModel(
            name="HeadwearVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="Название варианта"),
                ),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=500, verbose_name="Название (англ.)"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=600, unique=True, verbose_name="Slug варианта"),
                ),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                (
                    "size",
                    models.CharField(blank=True, max_length=50, verbose_name="Размер (устарело)"),
                ),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                ("barcode", models.CharField(blank=True, max_length=100, verbose_name="Штрихкод")),
                ("gtin", models.CharField(blank=True, max_length=100, verbose_name="GTIN")),
                ("mpn", models.CharField(blank=True, max_length=100, verbose_name="MPN")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Турецкая лира"),
                            ("RUB", "Российский рубль"),
                            ("KZT", "Казахстанский тенге"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("USDT", "Tether (USDT)"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(blank=True, verbose_name="Главное изображение варианта"),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/headwear/variants/",
                        verbose_name="Главное изображение варианта (файл)",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.headwearproduct",
                        verbose_name="Головной убор (родитель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант: Головной убор",
                "verbose_name_plural": "Варианты: Головные уборы",
                "ordering": ["product", "sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeadwearVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL изображения"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/headwear/variants/gallery/",
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.headwearvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта: Головной убор",
                "verbose_name_plural": "Изображения вариантов: Головные уборы",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeadwearVariantSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50, verbose_name="Размер")),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Остаток"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="catalog.headwearvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер варианта: Головной убор",
                "verbose_name_plural": "Размеры вариантов: Головные уборы",
                "ordering": ["variant", "sort_order", "size"],
            },
        ),
        migrations.CreateModel(
            name="IslamicClothingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Турецкая лира"),
                            ("RUB", "Российский рубль"),
                            ("KZT", "Казахстанский тенге"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("USDT", "Tether (USDT)"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="Главное изображение"
                    ),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Главное изображение (файл)",
                    ),
                ),
                ("gtin", models.CharField(blank=True, max_length=64, verbose_name="GTIN")),
                ("mpn", models.CharField(blank=True, max_length=64, verbose_name="MPN")),
                (
                    "weight_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
                    ),
                ),
                (
                    "dimensions_unit",
                    models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                        max_length=255,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Англоязычный SEO description для карточки товара.",
                        max_length=500,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова для индексации (англ.).",
                        max_length=500,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="OpenGraph title (англ.), если отличается от meta title.",
                        max_length=255,
                        verbose_name="OG Title",
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        help_text="OpenGraph description (англ.) для социальных сетей.",
                        max_length=500,
                        verbose_name="OG Description",
                    ),
                ),
                (
                    "og_image_url",
                    models.CharField(
                        blank=True,
                        help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                        max_length=2000,
                        verbose_name="OG Image URL",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("size", models.CharField(blank=True, max_length=20, verbose_name="Размер")),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                (
                    "video_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL видео"),
                ),
                (
                    "main_video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="products/islamic_clothing/main/",
                        verbose_name="Главное видео (файл)",
                    ),
                ),
                (
                    "base_product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="islamic_clothing_item",
                        to="catalog.product",
                        verbose_name="Базовый товар (shadow)",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исламская одежда",
                "verbose_name_plural": "Исламская одежда",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IslamicClothingProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL изображения"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/islamic_clothing/gallery/",
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.islamicclothingproduct",
                        verbose_name="Исламская одежда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение Исламская одежда",
                "verbose_name_plural": "Изображения Исламская одежда",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="IslamicClothingProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50, verbose_name="Размер")),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Остаток"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="catalog.islamicclothingproduct",
                        verbose_name="Исламская одежда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер товара: Исламская одежда",
                "verbose_name_plural": "Размеры: Исламская одежда",
                "ordering": ["product", "sort_order", "size"],
            },
        ),
        migrations.CreateModel(
            name="IslamicClothingProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.islamicclothingproduct",
                        verbose_name="Исламская одежда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод: Исламская одежда",
                "verbose_name_plural": "Переводы: Исламская одежда",
                "ordering": ["product", "locale"],
            },
        ),
        migrations.CreateModel(
            name="IslamicClothingVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="Название варианта"),
                ),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=500, verbose_name="Название (англ.)"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=600, unique=True, verbose_name="Slug варианта"),
                ),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                (
                    "size",
                    models.CharField(blank=True, max_length=50, verbose_name="Размер (устарело)"),
                ),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                ("barcode", models.CharField(blank=True, max_length=100, verbose_name="Штрихкод")),
                ("gtin", models.CharField(blank=True, max_length=100, verbose_name="GTIN")),
                ("mpn", models.CharField(blank=True, max_length=100, verbose_name="MPN")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Турецкая лира"),
                            ("RUB", "Российский рубль"),
                            ("KZT", "Казахстанский тенге"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("USDT", "Tether (USDT)"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(blank=True, verbose_name="Главное изображение варианта"),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/islamic_clothing/variants/",
                        verbose_name="Главное изображение варианта (файл)",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.islamicclothingproduct",
                        verbose_name="Исламская одежда (родитель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант: Исламская одежда",
                "verbose_name_plural": "Варианты: Исламская одежда",
                "ordering": ["product", "sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IslamicClothingVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL изображения"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/islamic_clothing/variants/gallery/",
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.islamicclothingvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта: Исламская одежда",
                "verbose_name_plural": "Изображения вариантов: Исламская одежда",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="IslamicClothingVariantSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50, verbose_name="Размер")),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Остаток"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="catalog.islamicclothingvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер варианта: Исламская одежда",
                "verbose_name_plural": "Размеры вариантов: Исламская одежда",
                "ordering": ["variant", "sort_order", "size"],
            },
        ),
        migrations.CreateModel(
            name="UnderwearProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField(max_length=500, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Мужская"),
                            ("women", "Женская"),
                            ("unisex", "Унисекс"),
                            ("kids", "Детская"),
                        ],
                        db_index=True,
                        help_text="Мужская, женская, унисекс, детская. При пустом — используется пол категории.",
                        max_length=10,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Турецкая лира"),
                            ("RUB", "Российский рубль"),
                            ("KZT", "Казахстанский тенге"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("USDT", "Tether (USDT)"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="Главное изображение"
                    ),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                        verbose_name="Главное изображение (файл)",
                    ),
                ),
                ("gtin", models.CharField(blank=True, max_length=64, verbose_name="GTIN")),
                ("mpn", models.CharField(blank=True, max_length=64, verbose_name="MPN")),
                (
                    "weight_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Вес"
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(default="g", max_length=10, verbose_name="Единица веса"),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Длина"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True, verbose_name="Высота"
                    ),
                ),
                (
                    "dimensions_unit",
                    models.CharField(default="cm", max_length=10, verbose_name="Единица размера"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Англоязычный SEO title, используется на всех фронтенд-страницах.",
                        max_length=255,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Англоязычный SEO description для карточки товара.",
                        max_length=500,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова для индексации (англ.).",
                        max_length=500,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="OpenGraph title (англ.), если отличается от meta title.",
                        max_length=255,
                        verbose_name="OG Title",
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        help_text="OpenGraph description (англ.) для социальных сетей.",
                        max_length=500,
                        verbose_name="OG Description",
                    ),
                ),
                (
                    "og_image_url",
                    models.CharField(
                        blank=True,
                        help_text="Ссылка на изображение для OpenGraph, если оно отличается от основного.",
                        max_length=2000,
                        verbose_name="OG Image URL",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуемый")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("size", models.CharField(blank=True, max_length=20, verbose_name="Размер")),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                (
                    "video_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL видео"),
                ),
                (
                    "main_video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="products/underwear/main/",
                        verbose_name="Главное видео (файл)",
                    ),
                ),
                (
                    "base_product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="underwear_item",
                        to="catalog.product",
                        verbose_name="Базовый товар (shadow)",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Нижнее бельё (товар)",
                "verbose_name_plural": "Нижнее бельё",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnderwearProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL изображения"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/underwear/gallery/",
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.underwearproduct",
                        verbose_name="Нижнее бельё (товар)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение Нижнее бельё (товар)",
                "verbose_name_plural": "Изображения Нижнее бельё",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnderwearProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50, verbose_name="Размер")),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Остаток"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="catalog.underwearproduct",
                        verbose_name="Нижнее бельё (товар)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер товара: Нижнее бельё (товар)",
                "verbose_name_plural": "Размеры: Нижнее бельё",
                "ordering": ["product", "sort_order", "size"],
            },
        ),
        migrations.CreateModel(
            name="UnderwearProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "Английский")],
                        db_index=True,
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.underwearproduct",
                        verbose_name="Нижнее бельё (товар)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод: Нижнее бельё (товар)",
                "verbose_name_plural": "Переводы: Нижнее бельё",
                "ordering": ["product", "locale"],
            },
        ),
        migrations.CreateModel(
            name="UnderwearVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=500, verbose_name="Название варианта"),
                ),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=500, verbose_name="Название (англ.)"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=600, unique=True, verbose_name="Slug варианта"),
                ),
                ("color", models.CharField(blank=True, max_length=50, verbose_name="Цвет")),
                (
                    "size",
                    models.CharField(blank=True, max_length=50, verbose_name="Размер (устарело)"),
                ),
                ("sku", models.CharField(blank=True, max_length=100, verbose_name="SKU")),
                ("barcode", models.CharField(blank=True, max_length=100, verbose_name="Штрихкод")),
                ("gtin", models.CharField(blank=True, max_length=100, verbose_name="GTIN")),
                ("mpn", models.CharField(blank=True, max_length=100, verbose_name="MPN")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Турецкая лира"),
                            ("RUB", "Российский рубль"),
                            ("KZT", "Казахстанский тенге"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("USDT", "Tether (USDT)"),
                        ],
                        default="RUB",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Старая цена",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="В наличии")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "main_image",
                    models.URLField(blank=True, verbose_name="Главное изображение варианта"),
                ),
                (
                    "main_image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/underwear/variants/",
                        verbose_name="Главное изображение варианта (файл)",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=500, verbose_name="Внешний ID"),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="Внешняя ссылка"),
                ),
                (
                    "external_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Внешние данные"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.underwearproduct",
                        verbose_name="Нижнее бельё (товар) (родитель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант: Нижнее бельё (товар)",
                "verbose_name_plural": "Варианты: Нижнее бельё",
                "ordering": ["product", "sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnderwearVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=2000, verbose_name="URL изображения"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/underwear/variants/gallery/",
                        verbose_name="Изображение (файл)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Alt текст"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="Главное изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.underwearvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение варианта: Нижнее бельё (товар)",
                "verbose_name_plural": "Изображения вариантов: Нижнее бельё",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnderwearVariantSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50, verbose_name="Размер")),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Остаток"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="catalog.underwearvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер варианта: Нижнее бельё (товар)",
                "verbose_name_plural": "Размеры вариантов: Нижнее бельё",
                "ordering": ["variant", "sort_order", "size"],
            },
        ),
        migrations.AddIndex(
            model_name="headwearproduct",
            index=models.Index(fields=["external_id"], name="catalog_hea_externa_2d3613_idx"),
        ),
        migrations.AddIndex(
            model_name="headwearproduct",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_hea_is_acti_4b74e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="headwearproduct",
            index=models.Index(fields=["category", "brand"], name="catalog_hea_categor_d4b8a8_idx"),
        ),
        migrations.AddIndex(
            model_name="headwearproduct",
            index=models.Index(fields=["price"], name="catalog_hea_price_1e2b92_idx"),
        ),
        migrations.AddIndex(
            model_name="headwearproductsize",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_hea_product_7a143d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="headwearproductsize",
            index=models.Index(fields=["product", "size"], name="catalog_hea_product_cdb0ac_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="headwearproducttranslation",
            unique_together={("product", "locale")},
        ),
        migrations.AddIndex(
            model_name="headwearvariant",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_hea_product_db6967_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="headwearvariant",
            index=models.Index(fields=["slug"], name="catalog_hea_slug_59bbcd_idx"),
        ),
        migrations.AddIndex(
            model_name="headwearvariant",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_hea_is_acti_185368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="islamicclothingproduct",
            index=models.Index(fields=["external_id"], name="catalog_isl_externa_84c357_idx"),
        ),
        migrations.AddIndex(
            model_name="islamicclothingproduct",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_isl_is_acti_bce311_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="islamicclothingproduct",
            index=models.Index(fields=["category", "brand"], name="catalog_isl_categor_9b00da_idx"),
        ),
        migrations.AddIndex(
            model_name="islamicclothingproduct",
            index=models.Index(fields=["price"], name="catalog_isl_price_ed925e_idx"),
        ),
        migrations.AddIndex(
            model_name="islamicclothingproductsize",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_isl_product_13b35c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="islamicclothingproductsize",
            index=models.Index(fields=["product", "size"], name="catalog_isl_product_80bd33_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="islamicclothingproducttranslation",
            unique_together={("product", "locale")},
        ),
        migrations.AddIndex(
            model_name="islamicclothingvariant",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_isl_product_530973_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="islamicclothingvariant",
            index=models.Index(fields=["slug"], name="catalog_isl_slug_a1c426_idx"),
        ),
        migrations.AddIndex(
            model_name="islamicclothingvariant",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_isl_is_acti_150aed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="underwearproduct",
            index=models.Index(fields=["external_id"], name="catalog_und_externa_204eab_idx"),
        ),
        migrations.AddIndex(
            model_name="underwearproduct",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_und_is_acti_fa2d9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="underwearproduct",
            index=models.Index(fields=["category", "brand"], name="catalog_und_categor_d450b8_idx"),
        ),
        migrations.AddIndex(
            model_name="underwearproduct",
            index=models.Index(fields=["price"], name="catalog_und_price_f925b1_idx"),
        ),
        migrations.AddIndex(
            model_name="underwearproductsize",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_und_product_5c17d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="underwearproductsize",
            index=models.Index(fields=["product", "size"], name="catalog_und_product_dd3cbf_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="underwearproducttranslation",
            unique_together={("product", "locale")},
        ),
        migrations.AddIndex(
            model_name="underwearvariant",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_und_product_06b1c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="underwearvariant",
            index=models.Index(fields=["slug"], name="catalog_und_slug_480269_idx"),
        ),
        migrations.AddIndex(
            model_name="underwearvariant",
            index=models.Index(
                fields=["is_active", "is_available"], name="catalog_und_is_acti_222a0a_idx"
            ),
        ),
    ]
