# Generated by Django 5.2.12 on 2026-04-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0160_headwearproduct_headwearproductimage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="headwearproduct",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Головной убор",
                "verbose_name_plural": "Товары — Головные уборы",
            },
        ),
        migrations.AlterModelOptions(
            name="islamicclothingproduct",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Исламская одежда",
                "verbose_name_plural": "Товары — Исламская одежда",
            },
        ),
        migrations.AlterModelOptions(
            name="underwearproduct",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Нижнее бельё (товар)",
                "verbose_name_plural": "Товары — Нижнее бельё",
            },
        ),
    ]
