# Generated by Django 5.2.12 on 2026-04-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0164_bookproductimage_video_url_video_file"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bannermediatranslation",
            new_name="catalog_ban_banner__0b3ee2_idx",
            old_name="catalog_ban_banner_m_8b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="bannertranslation",
            new_name="catalog_ban_banner__c2e95c_idx",
            old_name="catalog_ban_banner__f3a1_idx",
        ),
    ]
