# Generated by Django 5.2.12 on 2026-04-05 22:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0166_globalcurrencysettings_shipping_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalcurrencysettings",
            name="free_shipping_min_subtotal_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Порог по сумме товаров в заказе (субтотал без доставки), в USD. Не путать со стоимостью доставки: при субтотале ≥ порога доставка в API = 0. Пусто — правило отключено.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Бесплатная доставка от суммы заказа (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="globalcurrencysettings",
            name="usdt_markup_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("3.00"),
                help_text="Наценка магазина к паритету USDT/USD (1:1). Используется при расчёте любых курсов с USDT; ручные строки USDT в «Курс валют» для ценообразования не применяются. Дополнительная маржа — в настройках маржи по парам валют.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Наценка USDT (%)",
            ),
        ),
    ]
