# Generated by Django 5.2.12 on 2026-04-06 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0167_alter_globalcurrencysettings_usdt_help"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="favorite",
            name="chosen_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Для обуви/одежды с сеткой размеров — как в корзине; иначе пусто.",
                max_length=50,
                verbose_name="Выбранный размер",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={
                ("session_key", "content_type", "object_id", "chosen_size"),
                ("user", "content_type", "object_id", "chosen_size"),
            },
        ),
    ]
