# Generated by Django 5.2.12 on 2026-04-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0168_favorite_chosen_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="VKCategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("clothing", "Одежда"),
                            ("shoes", "Обувь"),
                            ("jewelry", "Ювелирные украшения"),
                            ("electronics", "Электроника"),
                            ("furniture", "Мебель"),
                            ("books", "Книги"),
                            ("perfumery", "Парфюмерия"),
                            ("medicines", "Лекарства"),
                            ("supplements", "БАДы"),
                            ("medical_equipment", "Медицинская техника"),
                            ("tableware", "Посуда"),
                            ("accessories", "Аксессуары"),
                            ("incense", "Благовония"),
                            ("sports", "Спортивные товары"),
                            ("auto_parts", "Автозапчасти"),
                            ("headwear", "Головные уборы"),
                            ("underwear", "Нижнее бельё"),
                            ("islamic_clothing", "Исламская одежда"),
                        ],
                        help_text="Значение product_type товара (из поля Product.product_type).",
                        max_length=60,
                        unique=True,
                        verbose_name="Тип товара (product_type)",
                    ),
                ),
                (
                    "vk_category_path",
                    models.CharField(
                        help_text="Полный путь категории через ' > '. Пример: 'Здоровье > Витамины и БАД'",
                        max_length=500,
                        verbose_name="Путь категории ВК",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Необязательное поле: откуда взят путь, особенности.",
                        verbose_name="Примечания",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Маппинг категории ВК",
                "verbose_name_plural": "Маппинги категорий ВК",
                "ordering": ["product_type"],
            },
        ),
    ]
