# Generated by Django 5.2.12 on 2026-04-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0169_vk_category_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="furnitureproduct",
            name="material",
            field=models.TextField(blank=True, verbose_name="Материал"),
        ),
    ]
