# Generated by Django 5.2.12 on 2026-04-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0170_alter_furnitureproduct_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Описание страницы категории для поисковых систем (до 500 символов).",
                max_length=500,
                verbose_name="SEO описание",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ключевые слова через запятую.",
                max_length=500,
                verbose_name="Ключевые слова",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Заголовок для поисковых систем (до 255 символов). Если пусто — используется название категории.",
                max_length=255,
                verbose_name="SEO заголовок",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="og_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Описание для социальных сетей (Open Graph).",
                max_length=500,
                verbose_name="OG описание",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL изображения для превью в социальных сетях.",
                max_length=500,
                verbose_name="OG изображение (URL)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="og_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Заголовок для социальных сетей (Open Graph). Если пусто — используется SEO заголовок.",
                max_length=255,
                verbose_name="OG заголовок",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Описание страницы услуги для поисковых систем (до 500 символов).",
                max_length=500,
                verbose_name="SEO описание",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ключевые слова через запятую.",
                max_length=500,
                verbose_name="Ключевые слова",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Заголовок для поисковых систем (до 255 символов). Если пусто — используется название услуги.",
                max_length=255,
                verbose_name="SEO заголовок",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="og_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Описание для социальных сетей (Open Graph).",
                max_length=500,
                verbose_name="OG описание",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="og_image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL изображения для превью в социальных сетях.",
                max_length=500,
                verbose_name="OG изображение (URL)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="og_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Заголовок для социальных сетей (Open Graph).",
                max_length=255,
                verbose_name="OG заголовок",
            ),
        ),
    ]
