# Generated by Django 5.2.12 on 2026-04-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0171_category_meta_description_category_meta_keywords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceattribute",
            name="value_en",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Значение (EN)"
            ),
        ),
        migrations.AddField(
            model_name="serviceattribute",
            name="value_ru",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Значение (RU)"
            ),
        ),
    ]
