# Generated by Django 5.2.12 on 2026-04-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0172_serviceattribute_value_en_serviceattribute_value_ru"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="serviceattribute",
            unique_together=set(),
        ),
    ]
