# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0173_alter_serviceattribute_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="clothingproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="clothingproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="clothingproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="clothingproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="clothingproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="shoeproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="shoeproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="shoeproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="shoeproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="shoeproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="jewelryproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="jewelryproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="jewelryproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="jewelryproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="jewelryproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="electronicsproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="electronicsproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="electronicsproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="electronicsproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="electronicsproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="furnitureproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="furnitureproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="furnitureproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="furnitureproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="furnitureproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="bookproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="bookproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="bookproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="bookproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="bookproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="perfumeryproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="perfumeryproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="perfumeryproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="perfumeryproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="perfumeryproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="medicineproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="supplementproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="supplementproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="supplementproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="supplementproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="supplementproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="medicalequipmentproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="medicalequipmentproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="medicalequipmentproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="medicalequipmentproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="medicalequipmentproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="tablewareproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="tablewareproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="tablewareproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="tablewareproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="tablewareproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="accessoryproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="accessoryproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="accessoryproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="accessoryproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="accessoryproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="incenseproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="incenseproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="incenseproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="incenseproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="incenseproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="sportsproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="sportsproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="sportsproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="sportsproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="sportsproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="autopartproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="autopartproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="autopartproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="autopartproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="autopartproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="headwearproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="headwearproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="headwearproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="headwearproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="headwearproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="underwearproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="underwearproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="underwearproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="underwearproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="underwearproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
        migrations.AddField(
            model_name="islamicclothingproducttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Meta Title"),
        ),
        migrations.AddField(
            model_name="islamicclothingproducttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Description"),
        ),
        migrations.AddField(
            model_name="islamicclothingproducttranslation",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, verbose_name="Meta Keywords"),
        ),
        migrations.AddField(
            model_name="islamicclothingproducttranslation",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AddField(
            model_name="islamicclothingproducttranslation",
            name="og_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="OG Description"),
        ),
    ]
