# Generated by Codex on 2026-05-02

import apps.catalog.utils.storage_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0174_product_translation_seo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceimage",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите видео для галереи услуги.",
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_service_image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Видео (файл)",
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Внешняя ссылка на видео для галереи услуги.",
                max_length=2000,
                verbose_name="URL видео",
            ),
        ),
        migrations.AlterModelOptions(
            name="serviceimage",
            options={
                "ordering": ["sort_order", "created_at"],
                "verbose_name": "Медиа услуги",
                "verbose_name_plural": "Медиа услуг",
            },
        ),
    ]
