# Generated by Django 5.2.12 on 2026-05-02 22:49

import apps.catalog.utils.storage_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0179_serviceportfolioitem_translations"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePortfolioMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Изображение/GIF"), ("video", "Видео")],
                        default="image",
                        max_length=10,
                        verbose_name="Тип медиа",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        choices=[("none", "Без плашки"), ("before", "До"), ("after", "После")],
                        default="none",
                        max_length=10,
                        verbose_name="Плашка",
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        help_text="Изображение, GIF или видео.",
                        null=True,
                        upload_to=apps.catalog.utils.storage_paths.get_service_image_upload_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на видео (YouTube) или картинку, если файл не загружается напрямую.",
                        max_length=2000,
                        verbose_name="Внешний URL",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
            ],
            options={
                "verbose_name": "Медиафайл кейса",
                "verbose_name_plural": "Медиафайлы кейса",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.RenameIndex(
            model_name="serviceportfolioitem",
            new_name="catalog_ser_categor_2f7581_idx",
            old_name="catalog_ser_categor_34033f_idx",
        ),
        migrations.RenameIndex(
            model_name="serviceportfolioitem",
            new_name="catalog_ser_service_20ed99_idx",
            old_name="catalog_ser_service_eb8300_idx",
        ),
        migrations.AddField(
            model_name="serviceportfoliomedia",
            name="portfolio_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_items",
                to="catalog.serviceportfolioitem",
                verbose_name="Кейс",
            ),
        ),
    ]
