# Generated by Django 5.2.12 on 2026-05-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0180_serviceportfoliomedia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceportfolioitem",
            name="after_image_file",
        ),
        migrations.RemoveField(
            model_name="serviceportfolioitem",
            name="after_image_url",
        ),
        migrations.RemoveField(
            model_name="serviceportfolioitem",
            name="before_image_file",
        ),
        migrations.RemoveField(
            model_name="serviceportfolioitem",
            name="before_image_url",
        ),
        migrations.RemoveField(
            model_name="serviceportfolioitem",
            name="image_file",
        ),
        migrations.RemoveField(
            model_name="serviceportfolioitem",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="serviceportfolioitem",
            name="video_file",
        ),
        migrations.RemoveField(
            model_name="serviceportfolioitem",
            name="video_url",
        ),
    ]
