# Generated by Django 5.2.12 on 2026-05-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0181_remove_serviceportfolioitem_after_image_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceportfolioitem",
            name="city_en",
            field=models.CharField(blank=True, max_length=120, verbose_name="Город (EN)"),
        ),
    ]
