# Generated by Django 5.2.10 on 2026-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0183_medicineanalog_explicit_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineproduct',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Фирма-производитель препарата (Firma). Не путать с торговой маркой (Brand).', max_length=500, verbose_name='Производитель'),
        ),
    ]
