# Generated by Django 5.2.12 on 2026-06-13 10:45

import apps.catalog.utils.storage_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0186_fix_globalattributekey_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessoryproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="bookproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="bookvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="clothingproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_main_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="clothingproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="clothingvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="clothingvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="furnitureproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="furniturevariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="furniturevariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="headwearproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_main_upload_path,
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="headwearproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="headwearvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="headwearvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="incenseproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="islamicclothingproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_main_upload_path,
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="islamicclothingproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="islamicclothingvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="islamicclothingvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="medicalequipmentproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="shoeproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="shoevariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="shoevariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="supplementproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="tablewareproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="underwearproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_main_upload_path,
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="underwearproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="underwearvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="underwearvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
    ]
