# Generated by Django 5.2.12 on 2026-06-13 19:49

import apps.catalog.utils.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0187_alter_accessoryproductimage_image_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceportfoliomedia",
            name="media_file",
            field=models.FileField(
                blank=True,
                help_text="Изображение, GIF или видео.",
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_service_portfolio_media_upload_path,
                verbose_name="Файл",
            ),
        ),
    ]
