# Generated by Django 5.2.12 on 2026-06-13 21:31

import apps.catalog.models
import apps.catalog.utils.storage_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0189_alter_serviceportfoliomedia_media_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessoryproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="accessoryproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="accessoryproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="autopartproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="autopartproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="bannermedia",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Локальный видеофайл (MP4, WebM)",
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_banner_video_upload_path,
                verbose_name="Видеофайл",
            ),
        ),
        migrations.AlterField(
            model_name="bookproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="bookproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="bookvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="clothingproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="clothingproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_main_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="clothingproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="clothingvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="clothingvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="electronicsproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="furnitureproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="furnitureproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="furnitureproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="furniturevariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="furniturevariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="headwearproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="incenseproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="incenseproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="incenseproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="islamicclothingproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_jewelry_main_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_jewelry_main_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_jewelry_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_jewelry_variant_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_jewelry_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="medicalequipmentproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="medicalequipmentproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="medicalequipmentproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="medicineproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryvariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeryvariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                help_text="Видео-файл товара (загружается в R2/локальное хранилище).",
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_image_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Видео-файл (загружается в R2/локальное хранилище).",
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите основное изображение для услуги. Можно использовать и GIF. Если главным медиа выбрано видео, это изображение будет использоваться как превью.",
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_service_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите основное видео для услуги. Поддерживаются MP4, MOV, WEBM, M4V, AVI, MKV до 100 МБ. Для корректного превью в карточке также заполните поле главного изображения.",
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_service_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "m4v", "avi", "mkv"]
                    ),
                    apps.catalog.models.validate_service_video_file_size,
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                help_text="Изображение или GIF для галереи услуги.",
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_service_image_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите видео для галереи услуги. Поддерживаются MP4, MOV, WEBM, M4V, AVI, MKV до 100 МБ.",
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_service_image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "m4v", "avi", "mkv"]
                    ),
                    apps.catalog.models.validate_service_video_file_size,
                ],
                verbose_name="Видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="shoeproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="shoeproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="shoeproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="shoevariant",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_main_upload_path,
                verbose_name="Главное изображение варианта (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="shoevariantimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_variant_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="sportsproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="sportsproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="supplementproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="supplementproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="supplementproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="tablewareproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="tablewareproduct",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv"]
                    )
                ],
                verbose_name="Главное видео (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="tablewareproductimage",
            name="image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_domain_gallery_upload_path,
                verbose_name="Изображение (файл)",
            ),
        ),
        migrations.AlterField(
            model_name="underwearproduct",
            name="main_image_file",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.catalog.utils.storage_paths.get_product_upload_path,
                verbose_name="Главное изображение (файл)",
            ),
        ),
    ]
