# Generated by Django 5.2.12 on 2026-06-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0190_alter_accessoryproduct_main_image_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceportfolioitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Если не указана, подтягивается из связанной услуги при сохранении.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_portfolio_items",
                to="catalog.category",
                verbose_name="Категория услуг",
            ),
        ),
    ]
