# Generated by Django 5.2.12 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0192_brand_homepage_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewelryproductimage",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="jewelryvariantimage",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение (CDN или медиа-хостинг); файл не сохраняется в проекте.",
                max_length=2000,
                verbose_name="URL изображения",
            ),
        ),
    ]
