# Generated by Django 5.2.12 on 2026-07-13 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0196_global_margin_is_product_markup"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="air_shipping_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="База авиадоставки, USD",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="air_shipping_rate_per_kg_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Авиа за кг, USD",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="air_shipping_rate_per_m3_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Авиа за м³, USD",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="free_shipping_eligible",
            field=models.BooleanField(
                default=True,
                help_text="Отключите для лекарств с особым режимом, крупногабаритных и других дорогих отправлений.",
                verbose_name="Участвует в бесплатной доставке",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="ground_shipping_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="База наземной доставки, USD",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="ground_shipping_rate_per_kg_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Наземная за кг, USD",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="ground_shipping_rate_per_m3_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Наземная за м³, USD",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="sea_shipping_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="База морской доставки, USD",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="sea_shipping_rate_per_kg_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Море за кг, USD",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="sea_shipping_rate_per_m3_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Море за м³, USD",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="shipping_calculation",
            field=models.CharField(
                choices=[
                    ("inherit", "Наследовать"),
                    ("fixed", "Фиксированная цена за единицу"),
                    ("weight", "По оплачиваемому весу"),
                    ("volume", "По объёму"),
                    ("quote", "Цена по запросу"),
                ],
                default="inherit",
                help_text="Наследуется от ближайшей родительской категории; если нигде не задано — используются глобальные фиксированные тарифы.",
                max_length=16,
                verbose_name="Расчёт доставки",
            ),
        ),
        migrations.AddField(
            model_name="globalcurrencysettings",
            name="shipping_volumetric_divisor",
            field=models.PositiveIntegerField(
                default=5000,
                help_text="Для весового расчёта: объёмный вес = Д×Ш×В в сантиметрах / делитель.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Делитель объёмного веса (см³/кг)",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="air_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фиксированная стоимость за единицу в USD; перекрывает категорию и глобальный тариф",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость авиадоставки",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="ground_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фиксированная стоимость за единицу в USD; перекрывает категорию и глобальный тариф",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость наземной доставки",
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="sea_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фиксированная стоимость за единицу в USD; перекрывает категорию и глобальный тариф",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость морской доставки",
            ),
        ),
        migrations.AlterField(
            model_name="productvariantprice",
            name="air_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фиксированная стоимость за единицу в USD; перекрывает категорию и глобальный тариф",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость авиадоставки",
            ),
        ),
        migrations.AlterField(
            model_name="productvariantprice",
            name="ground_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фиксированная стоимость за единицу в USD; перекрывает категорию и глобальный тариф",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость наземной доставки",
            ),
        ),
        migrations.AlterField(
            model_name="productvariantprice",
            name="sea_shipping_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Фиксированная стоимость за единицу в USD; перекрывает категорию и глобальный тариф",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость морской доставки",
            ),
        ),
    ]
