# Generated by Django 5.2.12 on 2026-07-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0197_category_shipping_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalShippingSettings",
            fields=[],
            options={
                "verbose_name": "глобальная настройка доставки",
                "verbose_name_plural": "🚚 Настройки: Доставка",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.globalcurrencysettings",),
        ),
        migrations.AlterModelOptions(
            name="globalcurrencysettings",
            options={
                "verbose_name": "глобальная настройка валют",
                "verbose_name_plural": "🌐 Настройки: Валюты и товарная маржа",
            },
        ),
    ]
