# Generated by Django 5.2.5 on 2025-08-19 12:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_brand_margin_percent_category_margin_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScraperConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название")),
                ("parser_class", models.CharField(max_length=200, verbose_name="Класс парсера")),
                ("base_url", models.URLField(verbose_name="Базовый URL")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("inactive", "Неактивен"),
                            ("error", "Ошибка"),
                            ("maintenance", "На обслуживании"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Включен")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Чем меньше число, тем выше приоритет",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "delay_min",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(60.0),
                        ],
                        verbose_name="Минимальная задержка (сек)",
                    ),
                ),
                (
                    "delay_max",
                    models.FloatField(
                        default=3.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(60.0),
                        ],
                        verbose_name="Максимальная задержка (сек)",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Таймаут запроса (сек)",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Максимум повторов",
                    ),
                ),
                (
                    "max_pages_per_run",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="Макс. страниц за запуск",
                    ),
                ),
                (
                    "max_products_per_run",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Макс. товаров за запуск",
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(default=True, verbose_name="Автосинхронизация"),
                ),
                (
                    "sync_interval_hours",
                    models.PositiveIntegerField(
                        default=24,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                        verbose_name="Интервал синхронизации (часы)",
                    ),
                ),
                (
                    "use_proxy",
                    models.BooleanField(default=False, verbose_name="Использовать прокси"),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=500, verbose_name="User-Agent"),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные заголовки"
                    ),
                ),
                ("cookies", models.JSONField(blank=True, default=dict, verbose_name="Cookies")),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последний запуск"),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний успешный запуск"
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последняя ошибка"),
                ),
                (
                    "last_error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "total_runs",
                    models.PositiveIntegerField(default=0, verbose_name="Всего запусков"),
                ),
                (
                    "successful_runs",
                    models.PositiveIntegerField(default=0, verbose_name="Успешных запусков"),
                ),
                (
                    "total_products_scraped",
                    models.PositiveIntegerField(default=0, verbose_name="Всего товаров спаршено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Конфигурация парсера",
                "verbose_name_plural": "Конфигурации парсеров",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("running", "Выполняется"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(blank=True, max_length=100, verbose_name="ID задачи Celery"),
                ),
                ("start_url", models.URLField(blank=True, verbose_name="Начальный URL")),
                (
                    "max_pages",
                    models.PositiveIntegerField(default=10, verbose_name="Макс. страниц"),
                ),
                (
                    "max_products",
                    models.PositiveIntegerField(default=100, verbose_name="Макс. товаров"),
                ),
                (
                    "pages_processed",
                    models.PositiveIntegerField(default=0, verbose_name="Обработано страниц"),
                ),
                (
                    "products_found",
                    models.PositiveIntegerField(default=0, verbose_name="Найдено товаров"),
                ),
                (
                    "products_created",
                    models.PositiveIntegerField(default=0, verbose_name="Создано товаров"),
                ),
                (
                    "products_updated",
                    models.PositiveIntegerField(default=0, verbose_name="Обновлено товаров"),
                ),
                (
                    "products_skipped",
                    models.PositiveIntegerField(default=0, verbose_name="Пропущено товаров"),
                ),
                (
                    "errors_count",
                    models.PositiveIntegerField(default=0, verbose_name="Количество ошибок"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Начало")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Окончание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "log_messages",
                    models.JSONField(blank=True, default=list, verbose_name="Сообщения лога"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Сообщение об ошибке")),
                (
                    "scraper_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="scrapers.scraperconfig",
                        verbose_name="Конфигурация парсера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия парсинга",
                "verbose_name_plural": "Сессии парсинга",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_category_name",
                    models.CharField(max_length=200, verbose_name="Внешнее название категории"),
                ),
                (
                    "external_category_url",
                    models.URLField(blank=True, verbose_name="URL внешней категории"),
                ),
                (
                    "external_category_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID внешней категории"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                ("priority", models.PositiveIntegerField(default=100, verbose_name="Приоритет")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "internal_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                        verbose_name="Внутренняя категория",
                    ),
                ),
                (
                    "scraper_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_mappings",
                        to="scrapers.scraperconfig",
                        verbose_name="Конфигурация парсера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маппинг категории",
                "verbose_name_plural": "Маппинги категорий",
                "ordering": ["priority", "external_category_name"],
                "unique_together": {("scraper_config", "external_category_name")},
            },
        ),
        migrations.CreateModel(
            name="BrandMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_brand_name",
                    models.CharField(max_length=200, verbose_name="Внешнее название бренда"),
                ),
                (
                    "external_brand_url",
                    models.URLField(blank=True, verbose_name="URL внешнего бренда"),
                ),
                (
                    "external_brand_id",
                    models.CharField(blank=True, max_length=100, verbose_name="ID внешнего бренда"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                ("priority", models.PositiveIntegerField(default=100, verbose_name="Приоритет")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "internal_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.brand",
                        verbose_name="Внутренний бренд",
                    ),
                ),
                (
                    "scraper_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_mappings",
                        to="scrapers.scraperconfig",
                        verbose_name="Конфигурация парсера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маппинг бренда",
                "verbose_name_plural": "Маппинги брендов",
                "ordering": ["priority", "external_brand_name"],
                "unique_together": {("scraper_config", "external_brand_name")},
            },
        ),
        migrations.CreateModel(
            name="ScrapedProductLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=200, verbose_name="Внешний ID")),
                ("external_url", models.URLField(verbose_name="Внешний URL")),
                ("product_name", models.CharField(max_length=500, verbose_name="Название товара")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("updated", "Обновлен"),
                            ("skipped", "Пропущен"),
                            ("error", "Ошибка"),
                            ("duplicate", "Дубликат"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "scraped_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Спарсенные данные"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_logs",
                        to="scrapers.scrapingsession",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог товара",
                "verbose_name_plural": "Логи товаров",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "action"], name="scrapers_sc_session_6575b8_idx"
                    ),
                    models.Index(fields=["external_id"], name="scrapers_sc_externa_918021_idx"),
                    models.Index(fields=["created_at"], name="scrapers_sc_created_6ac29e_idx"),
                ],
            },
        ),
    ]
