# Generated by Django 5.2.10 on 2026-01-27 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramScraperTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "instagram_username",
                    models.CharField(
                        help_text="Введите username без @ (например: book.warrior)",
                        max_length=100,
                        verbose_name="Instagram username",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("books", "Книги"),
                            ("clothing", "Одежда"),
                            ("shoes", "Обувь"),
                            ("electronics", "Электроника"),
                            ("supplements", "Добавки"),
                            ("medical-equipment", "Медицинское оборудование"),
                            ("furniture", "Мебель"),
                            ("tableware", "Посуда"),
                            ("accessories", "Аксессуары"),
                            ("jewelry", "Ювелирные изделия"),
                            ("underwear", "Нижнее белье"),
                            ("headwear", "Головные уборы"),
                        ],
                        default="books",
                        max_length=50,
                        verbose_name="Категория товаров",
                    ),
                ),
                (
                    "max_posts",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Количество постов для парсинга (не критично если больше чем есть)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="Максимум постов",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("running", "Выполняется"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "products_created",
                    models.PositiveIntegerField(default=0, verbose_name="Создано товаров"),
                ),
                (
                    "products_updated",
                    models.PositiveIntegerField(default=0, verbose_name="Обновлено товаров"),
                ),
                (
                    "products_skipped",
                    models.PositiveIntegerField(default=0, verbose_name="Пропущено товаров"),
                ),
                ("log_output", models.TextField(blank=True, verbose_name="Лог выполнения")),
                ("error_message", models.TextField(blank=True, verbose_name="Сообщение об ошибке")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начало выполнения"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Завершено"),
                ),
            ],
            options={
                "verbose_name": "Задача парсинга Instagram",
                "verbose_name_plural": "Задачи парсинга Instagram",
                "ordering": ["-created_at"],
            },
        ),
    ]
