# Generated by Django 5.2.11 on 2026-02-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0002_instagramscrapertask"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperconfig",
            name="scraper_password",
            field=models.CharField(
                blank=True,
                help_text="Пароль для авторизации парсера на сайте (если нужно)",
                max_length=100,
                verbose_name="Пароль парсера",
            ),
        ),
        migrations.AddField(
            model_name="scraperconfig",
            name="scraper_username",
            field=models.CharField(
                blank=True,
                help_text="Логин для авторизации парсера на сайте (если нужно)",
                max_length=100,
                verbose_name="Логин парсера",
            ),
        ),
    ]
