# Generated by Django 5.2.11 on 2026-02-19 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0114_accessoryproduct_meta_description_and_more"),
        ("scrapers", "0006_instagram_post_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperconfig",
            name="default_category",
            field=models.ForeignKey(
                default=81,
                help_text="Категория-домен для всех товаров этого парсера (обязательно)",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.category",
                verbose_name="Категория по умолчанию",
            ),
        ),
    ]
