# Generated by Django 5.2.11 on 2026-03-01 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0116_create_perfumery_product_from_base"),
        ("scrapers", "0008_alter_scraperconfig_default_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingsession",
            name="target_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Категория, в которую сохранять товары из этой сессии",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scraping_sessions",
                to="catalog.category",
                verbose_name="Целевая категория",
            ),
        ),
        migrations.AddField(
            model_name="sitescrapertask",
            name="target_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Категория, в которую сохранять товары. Переопределяет категорию по умолчанию из конфигурации парсера.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_scraper_tasks",
                to="catalog.category",
                verbose_name="Целевая категория",
            ),
        ),
    ]
