# Generated by Django 5.2.11 on 2026-03-03 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0117_alter_bookproductimage_image_file"),
        ("scrapers", "0010_instagram_task_target_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagramscrapertask",
            name="target_subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="Опционально. Узкая подкатегория (например, жанр книги или тип одежды). Если выбрано, товары будут сохранены сюда.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instagram_tasks_sub",
                to="catalog.category",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.AddField(
            model_name="sitescrapertask",
            name="target_subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="Опционально. Узкая подкатегория (например, жанр книги или тип одежды). Если выбрано, товары будут сохранены сюда.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_tasks_sub",
                to="catalog.category",
                verbose_name="Подкатегория",
            ),
        ),
    ]
