# Generated by Django 5.2.12 on 2026-03-29 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0156_alter_furnitureproduct_dimensions_and_more"),
        ("scrapers", "0011_instagramscrapertask_target_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperconfig",
            name="default_brand",
            field=models.ForeignKey(
                blank=True,
                help_text="Бренд для всех товаров этого парсера (например, IKEA). Приоритетнее чем данные парсера.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.brand",
                verbose_name="Бренд по умолчанию",
            ),
        ),
    ]
