# Generated by Django 5.2.12 on 2026-04-05 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0167_alter_globalcurrencysettings_usdt_help"),
        ("scrapers", "0012_scraperconfig_default_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scraperconfig",
            name="default_category",
            field=models.ForeignKey(
                help_text="Категория-домен для всех товаров этого парсера (обязательно). В админке пункты отсортированы по полному пути (Корень › Подкатегория › …).",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.category",
                verbose_name="Категория по умолчанию",
            ),
        ),
    ]
