# Generated by Django 5.2.12 on 2026-05-14 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0184_medicineproduct_manufacturer"),
        ("scrapers", "0016_sitescrapertask_task_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDuplicateCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pair_key",
                    models.CharField(max_length=64, unique=True, verbose_name="Ключ пары"),
                ),
                (
                    "canonical_product_name",
                    models.CharField(max_length=500, verbose_name="Название основного товара"),
                ),
                (
                    "duplicate_product_name",
                    models.CharField(max_length=500, verbose_name="Название товара-дубликата"),
                ),
                ("score", models.FloatField(default=0.0, verbose_name="Оценка совпадения")),
                (
                    "reasons",
                    models.JSONField(blank=True, default=list, verbose_name="Причины совпадения"),
                ),
                (
                    "signals",
                    models.JSONField(blank=True, default=dict, verbose_name="Сигналы сравнения"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает модерации"),
                            ("approved", "Одобрено к объединению"),
                            ("rejected", "Отклонено"),
                            ("merged", "Объединено"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "moderator_note",
                    models.TextField(blank=True, verbose_name="Комментарий модератора"),
                ),
                (
                    "detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата обнаружения"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата решения"),
                ),
                (
                    "merged_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата объединения"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "canonical_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicate_candidates_as_canonical",
                        to="catalog.product",
                        verbose_name="Основной товар",
                    ),
                ),
                (
                    "duplicate_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicate_candidates_as_duplicate",
                        to="catalog.product",
                        verbose_name="Товар-кандидат на объединение",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_duplicate_candidates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кандидат в дубликаты",
                "verbose_name_plural": "Кандидаты в дубликаты",
                "ordering": ["status", "-score", "-detected_at"],
                "indexes": [
                    models.Index(fields=["status", "-score"], name="scrapers_pr_status_4df9e9_idx"),
                    models.Index(
                        fields=["canonical_product"], name="scrapers_pr_canonic_237384_idx"
                    ),
                    models.Index(
                        fields=["duplicate_product"], name="scrapers_pr_duplica_874acf_idx"
                    ),
                ],
            },
        ),
    ]
