# Generated by Django 5.2.12 on 2026-06-12 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0017_alter_sitescrapertask_max_pages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitescrapertask",
            name="max_pages",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Сколько страниц обрабатывать в одном запуске Celery. Для ilacfiyati рекомендуется 20–50 (≈30–60 мин). При больших каталогах задачи выстраиваются в цепочку автоматически.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Страниц за один запуск",
            ),
        ),
        migrations.AlterField(
            model_name="sitescrapertask",
            name="max_products",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Суммарный лимит товаров по всей цепочке запусков. Для полного каталога ilacfiyati ~10 000–30 000.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="Макс. товаров (всего)",
            ),
        ),
    ]
