# Generated by Django 5.2.10 on 2026-06-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0019_sitescrapertask_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitescrapertask',
            name='resume_page',
            field=models.PositiveIntegerField(default=1, help_text='С какой страницы продолжить после паузы (только для парсеров с постраничной пагинацией). Обновляется автоматически по ходу обхода.', verbose_name='Страница для продолжения'),
        ),
        migrations.AlterField(
            model_name='sitescrapertask',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('paused', 'На паузе'), ('cancelled', 'Остановлено'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
