# Generated by Django 5.2.17 on 2026-09-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0024_sitescrapertask_stub_cursor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitescrapertask',
            name='run_token',
            field=models.UUIDField(blank=True, editable=False, help_text='Меняется при новом проходе каталога; сохраняется между чанками и после паузы.', null=True, verbose_name='ID прохода'),
        ),
    ]
