# Generated by Django 5.2.11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0091_categoryperfumery_productperfumery_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingCategory",
            fields=[],
            options={
                "verbose_name": "Подкатегория товара",
                "verbose_name_plural": "Маркетинг — Подкатегории товаров",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="MarketingRootCategory",
            fields=[],
            options={
                "verbose_name": "Корневая категория",
                "verbose_name_plural": "Маркетинг — Корневые категории",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.category",),
        ),
        migrations.CreateModel(
            name="MarketingBrand",
            fields=[],
            options={
                "verbose_name": "Популярный бренд",
                "verbose_name_plural": "Маркетинг — Популярные бренды",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.brand",),
        ),
        migrations.CreateModel(
            name="MarketingBanner",
            fields=[],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Маркетинг — Баннеры",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.banner",),
        ),
        migrations.CreateModel(
            name="MarketingBannerMedia",
            fields=[],
            options={
                "verbose_name": "Медиа баннеров",
                "verbose_name_plural": "Маркетинг — Медиа баннеров",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.bannermedia",),
        ),
    ]
