# Generated by Django 5.2.12 on 2026-03-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CookieConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Идентификатор сессии"
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        help_text="True — пользователь принял все cookie, False — только необходимые.",
                        verbose_name="Согласие дано",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-адрес"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время"),
                ),
            ],
            options={
                "verbose_name": "Согласие на cookie",
                "verbose_name_plural": "Согласия на cookie",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="marketing_c_created_d95bf9_idx")
                ],
            },
        ),
    ]
