# Generated by Django 5.2.9 on 2025-12-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="+90 552 582 14 97",
                        max_length=50,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="fulani.dev@gmail.com",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Стамбул, Турция", max_length=200, verbose_name="Адрес"
                    ),
                ),
                ("telegram_url", models.URLField(blank=True, verbose_name="Ссылка на Telegram")),
                ("whatsapp_url", models.URLField(blank=True, verbose_name="Ссылка на WhatsApp")),
                ("vk_url", models.URLField(blank=True, verbose_name="Ссылка на VK")),
                ("instagram_url", models.URLField(blank=True, verbose_name="Ссылка на Instagram")),
                (
                    "crypto_payment_text",
                    models.CharField(
                        blank=True,
                        default="Возможна оплата криптовалютой",
                        max_length=200,
                        verbose_name="Текст про оплату криптовалютой",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Настройки футера",
                "verbose_name_plural": "Настройки футера",
            },
        ),
    ]
