# Generated by Django 5.2.10 on 2026-01-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footersettings",
            options={
                "verbose_name": "📄 Настройки футера",
                "verbose_name_plural": "📄 Контент — Настройки футера",
            },
        ),
    ]
