# Generated by Django 5.2.12 on 2026-03-19 22:10

import apps.settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_alter_footersettings_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footersettings",
            name="email",
            field=models.EmailField(
                blank=True,
                default=apps.settings.models._default_footer_email,
                max_length=254,
                verbose_name="Email",
            ),
        ),
    ]
